// src/tools/FileRenamer.vue
<template>
  <div class="min-h-screen bg-gray-50 p-6">
    <div class="max-w-6xl mx-auto space-y-6">
      <!-- Header -->
      <div class="text-center mb-8">
        <h1 class="text-3xl font-bold text-gray-900 mb-2">{{ $t('tools.fileRenamer.title') }}</h1>
        <p class="text-gray-600">{{ $t('tools.fileRenamer.subtitle') }}</p>
      </div>

      <!-- Upload Area -->
      <div class="bg-white p-6 rounded-lg shadow-sm border">
        <div
          class="border-2 border-dashed rounded-lg p-8 text-center transition-colors"
          :class="{
            'border-blue-500 bg-blue-50': isDragging,
            'border-gray-300 hover:border-gray-400': !isDragging,
          }"
          @dragover.prevent
          @dragenter.prevent="isDragging = true"
          @dragleave.prevent="isDragging = false"
          @drop="handleFileDrop"
        >
          <div class="text-4xl mb-3">📁</div>
          <h3 class="text-lg font-medium text-gray-900 mb-1">
            {{ $t('tools.fileRenamer.uploadArea.title') }}
          </h3>
          <p class="text-gray-500 mb-4">{{ $t('tools.fileRenamer.uploadArea.subtitle') }}</p>
          <button
            @click="fileInputClick"
            class="px-4 py-2 bg-blue-600 text-white rounded-lg hover:bg-blue-700 transition-colors"
          >
            {{ $t('tools.fileRenamer.uploadArea.selectFiles') }}
          </button>
          <input ref="fileInput" type="file" multiple @change="handleFileSelect" class="hidden" />
        </div>
      </div>

      <!-- File List and Options -->
      <div v-if="files.length > 0" class="bg-white p-6 rounded-lg shadow-sm border">
        <!-- File Count and Sorting -->
        <div class="flex flex-col sm:flex-row sm:items-center justify-between gap-4 mb-6">
          <div class="text-lg font-medium text-gray-900">
            {{ $t('tools.fileRenamer.fileCount', { count: files.length }) }}
          </div>

          <!-- Sorting Options -->
          <div class="flex flex-wrap items-center gap-2">
            <span class="text-sm font-medium text-gray-700">
              {{ $t('tools.fileRenamer.sorting.title') }}:
            </span>
            <div class="flex flex-wrap gap-2">
              <button
                v-for="option in sortingOptions"
                :key="option.id"
                @click="sortFiles(option.id)"
                class="px-3 py-1 text-sm rounded transition-colors"
                :class="{
                  'bg-blue-100 text-blue-800 border border-blue-300': sortType === option.id,
                  'bg-gray-100 text-gray-700 hover:bg-gray-200 border border-gray-200':
                    sortType !== option.id,
                }"
              >
                {{ option.label }}
              </button>
            </div>
          </div>
        </div>

        <!-- Tabs -->
        <div class="border-b border-gray-200 mb-6">
          <nav class="-mb-px flex space-x-8 overflow-x-auto">
            <button
              v-for="tab in renamingTabs"
              :key="tab.id"
              @click="activeTab = tab.id"
              class="whitespace-nowrap py-2 px-1 border-b-2 font-medium text-sm transition-colors"
              :class="{
                'border-blue-500 text-blue-600': activeTab === tab.id,
                'border-transparent text-gray-500 hover:text-gray-700 hover:border-gray-300':
                  activeTab !== tab.id,
              }"
            >
              {{ $t(`tools.fileRenamer.tabs.${tab.id}`) }}
            </button>
          </nav>
        </div>

        <!-- Tab Content -->
        <div class="mb-6">
          <!-- Sequential Tab -->
          <div v-if="activeTab === 'sequential'">
            <div class="grid grid-cols-1 md:grid-cols-3 gap-4">
              <div>
                <label class="block text-sm font-medium text-gray-700 mb-1">
                  {{ $t('tools.fileRenamer.sequential.prefix') }}
                </label>
                <input
                  v-model="sequentialOptions.prefix"
                  :placeholder="$t('tools.fileRenamer.sequential.prefixPlaceholder')"
                  class="w-full px-3 py-2 border border-gray-300 rounded-md shadow-sm focus:outline-none focus:ring-blue-500 focus:border-blue-500"
                />
              </div>
              <div>
                <label class="block text-sm font-medium text-gray-700 mb-1">
                  {{ $t('tools.fileRenamer.sequential.startNumber') }}
                </label>
                <input
                  v-model.number="sequentialOptions.startNumber"
                  type="number"
                  min="0"
                  class="w-full px-3 py-2 border border-gray-300 rounded-md shadow-sm focus:outline-none focus:ring-blue-500 focus:border-blue-500"
                />
              </div>
              <div>
                <label class="block text-sm font-medium text-gray-700 mb-1">
                  {{ $t('tools.fileRenamer.sequential.padding') }}
                </label>
                <input
                  v-model.number="sequentialOptions.padding"
                  type="number"
                  min="1"
                  max="10"
                  class="w-full px-3 py-2 border border-gray-300 rounded-md shadow-sm focus:outline-none focus:ring-blue-500 focus:border-blue-500"
                />
              </div>
            </div>
          </div>

          <!-- Replace Tab -->
          <div v-if="activeTab === 'replace'">
            <div class="grid grid-cols-1 md:grid-cols-2 gap-4">
              <div>
                <label class="block text-sm font-medium text-gray-700 mb-1">
                  {{ $t('tools.fileRenamer.replace.findText') }}
                </label>
                <input
                  v-model="replaceOptions.findText"
                  :placeholder="$t('tools.fileRenamer.replace.findPlaceholder')"
                  class="w-full px-3 py-2 border border-gray-300 rounded-md shadow-sm focus:outline-none focus:ring-blue-500 focus:border-blue-500"
                />
              </div>
              <div>
                <label class="block text-sm font-medium text-gray-700 mb-1">
                  {{ $t('tools.fileRenamer.replace.replaceText') }}
                </label>
                <input
                  v-model="replaceOptions.replaceText"
                  :placeholder="$t('tools.fileRenamer.replace.replacePlaceholder')"
                  class="w-full px-3 py-2 border border-gray-300 rounded-md shadow-sm focus:outline-none focus:ring-blue-500 focus:border-blue-500"
                />
              </div>
            </div>
            <div class="mt-3">
              <label class="flex items-center">
                <input
                  v-model="replaceOptions.caseSensitive"
                  type="checkbox"
                  class="rounded border-gray-300 text-blue-600 shadow-sm focus:border-blue-300 focus:ring focus:ring-blue-200 focus:ring-opacity-50"
                />
                <span class="ml-2 text-sm text-gray-600">
                  {{ $t('tools.fileRenamer.replace.caseSensitive') }}
                </span>
              </label>
            </div>
          </div>

          <!-- Case Tab -->
          <div v-if="activeTab === 'case'">
            <div class="grid grid-cols-1 md:grid-cols-3 gap-4">
              <label
                class="flex items-center p-3 border border-gray-200 rounded-lg cursor-pointer hover:bg-gray-50"
              >
                <input
                  v-model="caseOptions.type"
                  type="radio"
                  value="uppercase"
                  class="h-4 w-4 text-blue-600 border-gray-300 focus:ring-blue-500"
                />
                <span class="ml-3 text-sm text-gray-700">
                  {{ $t('tools.fileRenamer.case.uppercase') }}
                </span>
              </label>
              <label
                class="flex items-center p-3 border border-gray-200 rounded-lg cursor-pointer hover:bg-gray-50"
              >
                <input
                  v-model="caseOptions.type"
                  type="radio"
                  value="lowercase"
                  class="h-4 w-4 text-blue-600 border-gray-300 focus:ring-blue-500"
                />
                <span class="ml-3 text-sm text-gray-700">
                  {{ $t('tools.fileRenamer.case.lowercase') }}
                </span>
              </label>
              <label
                class="flex items-center p-3 border border-gray-200 rounded-lg cursor-pointer hover:bg-gray-50"
              >
                <input
                  v-model="caseOptions.type"
                  type="radio"
                  value="capitalize"
                  class="h-4 w-4 text-blue-600 border-gray-300 focus:ring-blue-500"
                />
                <span class="ml-3 text-sm text-gray-700">
                  {{ $t('tools.fileRenamer.case.capitalize') }}
                </span>
              </label>
            </div>
          </div>

          <!-- Insert Tab -->
          <div v-if="activeTab === 'insert'">
            <div class="grid grid-cols-1 md:grid-cols-2 gap-4">
              <div>
                <label class="block text-sm font-medium text-gray-700 mb-1">
                  {{ $t('tools.fileRenamer.insert.text') }}
                </label>
                <input
                  v-model="insertOptions.text"
                  :placeholder="$t('tools.fileRenamer.insert.textPlaceholder')"
                  class="w-full px-3 py-2 border border-gray-300 rounded-md shadow-sm focus:outline-none focus:ring-blue-500 focus:border-blue-500"
                />
              </div>
              <div>
                <label class="block text-sm font-medium text-gray-700 mb-1">
                  {{ $t('tools.fileRenamer.insert.position') }}
                </label>
                <select
                  v-model="insertOptions.position"
                  class="w-full px-3 py-2 border border-gray-300 rounded-md shadow-sm focus:outline-none focus:ring-blue-500 focus:border-blue-500"
                >
                  <option value="prefix">{{ $t('tools.fileRenamer.insert.prefix') }}</option>
                  <option value="suffix">{{ $t('tools.fileRenamer.insert.suffix') }}</option>
                  <option value="index">{{ $t('tools.fileRenamer.insert.atIndex') }}</option>
                </select>
              </div>
            </div>
            <div v-if="insertOptions.position === 'index'" class="mt-3">
              <label class="block text-sm font-medium text-gray-700 mb-1">
                {{ $t('tools.fileRenamer.insert.index') }}
              </label>
              <input
                v-model.number="insertOptions.index"
                type="number"
                min="0"
                class="w-full md:w-1/3 px-3 py-2 border border-gray-300 rounded-md shadow-sm focus:outline-none focus:ring-blue-500 focus:border-blue-500"
              />
            </div>
          </div>

          <!-- Truncate Tab -->
          <div v-if="activeTab === 'truncate'">
            <div class="grid grid-cols-1 md:grid-cols-2 gap-4">
              <div>
                <label class="block text-sm font-medium text-gray-700 mb-1">
                  {{ $t('tools.fileRenamer.truncate.startIndex') }}
                </label>
                <input
                  v-model.number="truncateOptions.startIndex"
                  type="number"
                  min="0"
                  class="w-full px-3 py-2 border border-gray-300 rounded-md shadow-sm focus:outline-none focus:ring-blue-500 focus:border-blue-500"
                />
              </div>
              <div>
                <label class="block text-sm font-medium text-gray-700 mb-1">
                  {{ $t('tools.fileRenamer.truncate.endIndex') }}
                </label>
                <input
                  v-model.number="truncateOptions.endIndex"
                  type="number"
                  min="0"
                  class="w-full px-3 py-2 border border-gray-300 rounded-md shadow-sm focus:outline-none focus:ring-blue-500 focus:border-blue-500"
                />
              </div>
            </div>
            <p class="mt-2 text-sm text-gray-500">
              {{ $t('tools.fileRenamer.truncate.description') }}
            </p>
          </div>
        </div>

        <!-- Action Buttons -->
        <div class="flex flex-wrap gap-3 mb-6">
          <button
            @click="generatePreview"
            class="px-4 py-2 bg-blue-600 text-white rounded-lg hover:bg-blue-700 transition-colors"
          >
            {{ $t('tools.fileRenamer.actions.preview') }}
          </button>
          <button
            v-if="hasPreview"
            @click="applyRename"
            class="px-4 py-2 bg-green-600 text-white rounded-lg hover:bg-green-700 transition-colors"
          >
            {{ $t('tools.fileRenamer.actions.apply') }}
          </button>
          <button
            v-if="hasRenamed"
            @click="downloadFiles"
            class="px-4 py-2 bg-purple-600 text-white rounded-lg hover:bg-purple-700 transition-colors"
          >
            {{ $t('tools.fileRenamer.actions.download') }}
          </button>
          <button
            @click="clearFiles"
            class="px-4 py-2 bg-gray-600 text-white rounded-lg hover:bg-gray-700 transition-colors"
          >
            {{ $t('tools.fileRenamer.actions.clear') }}
          </button>
        </div>

        <!-- File List -->
        <div class="border rounded-lg overflow-hidden">
          <div class="bg-gray-50 px-4 py-3 border-b">
            <h3 class="font-medium text-gray-900">
              {{ $t('tools.fileRenamer.fileList.title') }}
            </h3>
            <p class="text-sm text-gray-500 mt-1">
              {{ $t('tools.fileRenamer.fileList.dragHint') }}
            </p>
          </div>
          <div class="overflow-x-auto">
            <table class="min-w-full divide-y divide-gray-200">
              <thead class="bg-gray-50">
                <tr>
                  <th
                    scope="col"
                    class="px-6 py-3 text-left text-xs font-medium text-gray-500 uppercase tracking-wider"
                  >
                    {{ $t('tools.fileRenamer.fileList.drag') }}
                  </th>
                  <th
                    scope="col"
                    class="px-6 py-3 text-left text-xs font-medium text-gray-500 uppercase tracking-wider"
                  >
                    {{ $t('tools.fileRenamer.fileList.originalName') }}
                  </th>
                  <th
                    scope="col"
                    class="px-6 py-3 text-left text-xs font-medium text-gray-500 uppercase tracking-wider"
                  >
                    {{ $t('tools.fileRenamer.fileList.newName') }}
                  </th>
                  <th
                    scope="col"
                    class="px-6 py-3 text-left text-xs font-medium text-gray-500 uppercase tracking-wider"
                  >
                    {{ $t('tools.fileRenamer.fileList.size') }}
                  </th>
                  <th
                    scope="col"
                    class="px-6 py-3 text-left text-xs font-medium text-gray-500 uppercase tracking-wider"
                  >
                    {{ $t('tools.fileRenamer.fileList.type') }}
                  </th>
                </tr>
              </thead>
              <draggable
                v-model="files"
                tag="tbody"
                item-key="id"
                @start="handleDragStart"
                @end="handleDragEnd"
                :disabled="sortType !== 'manual'"
                class="divide-y divide-gray-200 bg-white"
              >
                <template #item="{ element: file }">
                  <tr
                    :class="{
                      'cursor-move': sortType === 'manual',
                    }"
                  >
                    <td class="px-6 py-4 whitespace-nowrap text-sm text-gray-500">
                      <div
                        v-if="sortType === 'manual'"
                        class="cursor-move text-gray-400 hover:text-gray-600"
                        title="Drag to reorder"
                      >
                        <svg class="w-5 h-5" fill="none" stroke="currentColor" viewBox="0 0 24 24">
                          <path
                            stroke-linecap="round"
                            stroke-linejoin="round"
                            stroke-width="2"
                            d="M7 16V4m0 0L3 8m4-4l4 4m6 0v12m0 0l4-4m-4 4l-4-4"
                          />
                        </svg>
                      </div>
                      <div v-else class="text-gray-300">
                        <svg class="w-5 h-5" fill="none" stroke="currentColor" viewBox="0 0 24 24">
                          <path
                            stroke-linecap="round"
                            stroke-linejoin="round"
                            stroke-width="2"
                            d="M7 16V4m0 0L3 8m4-4l4 4m6 0v12m0 0l4-4m-4 4l-4-4"
                          />
                        </svg>
                      </div>
                    </td>
                    <td class="px-6 py-4 whitespace-nowrap text-sm font-medium text-gray-900">
                      {{ file.originalName }}
                    </td>
                    <td class="px-6 py-4 whitespace-nowrap text-sm text-gray-500">
                      <span
                        :class="{
                          'text-green-600 font-medium':
                            file.newName && file.newName !== file.originalName,
                        }"
                      >
                        {{ file.newName || file.originalName }}
                      </span>
                    </td>
                    <td class="px-6 py-4 whitespace-nowrap text-sm text-gray-500">
                      {{ formatFileSize(file.size) }}
                    </td>
                    <td class="px-6 py-4 whitespace-nowrap text-sm text-gray-500">
                      {{ file.type || '—' }}
                    </td>
                  </tr>
                </template>
              </draggable>
            </table>
          </div>
        </div>
      </div>

      <!-- Empty State -->
      <div v-else class="bg-white p-12 rounded-lg shadow-sm border text-center">
        <div class="text-5xl mb-4">📁</div>
        <h3 class="text-lg font-medium text-gray-900 mb-1">
          {{ $t('tools.fileRenamer.uploadArea.title') }}
        </h3>
        <p class="text-gray-500">
          {{ $t('tools.fileRenamer.uploadArea.subtitle') }}
        </p>
      </div>
    </div>
  </div>
</template>

<script setup lang="ts">
import { ref, computed } from 'vue'
import { useI18n } from 'vue-i18n'
import { useToast } from '@/composables/useToast'
import draggable from 'vuedraggable'

const { t } = useI18n()
const { success, info } = useToast()

interface FileItem {
  id: string
  file: File
  originalName: string
  newName?: string
  size: number
  type: string
  lastModified: number
}

// State
const files = ref<FileItem[]>([])
const isDragging = ref(false)
const activeTab = ref('sequential')
const hasPreview = ref(false)
const hasRenamed = ref(false)
const fileInput = ref<HTMLInputElement | null>(null)
const sortType = ref('natural')

// Computed property for sorted files
const sortedFiles = computed(() => {
  // For manual sorting, we return the files array directly as it's managed by vuedraggable
  if (sortType.value === 'manual') {
    return files.value
  }

  const filesArray = [...files.value]

  switch (sortType.value) {
    case 'natural':
      return filesArray.sort((a, b) =>
        a.originalName.localeCompare(b.originalName, undefined, {
          numeric: true,
          sensitivity: 'base',
        }),
      )
    case 'filename':
      return filesArray.sort((a, b) => a.originalName.localeCompare(b.originalName))
    case 'modifiedTime':
      return filesArray.sort((a, b) => a.lastModified - b.lastModified)
    case 'modifiedTimeDesc':
      return filesArray.sort((a, b) => b.lastModified - a.lastModified)
    case 'random':
      return filesArray.sort(() => Math.random() - 0.5)
    case 'reverse':
      return filesArray.reverse()
    default:
      return filesArray
  }
})

// Renaming options
const sequentialOptions = ref({
  prefix: '',
  startNumber: 1,
  padding: 3,
})

const replaceOptions = ref({
  findText: '',
  replaceText: '',
  caseSensitive: false,
})

const caseOptions = ref({
  type: 'lowercase',
})

const insertOptions = ref({
  text: '',
  position: 'prefix',
  index: 0,
})

const truncateOptions = ref({
  startIndex: 0,
  endIndex: 0,
})

// Tab configuration
const renamingTabs = [
  { id: 'sequential' },
  { id: 'replace' },
  { id: 'case' },
  { id: 'insert' },
  { id: 'truncate' },
]

// Sorting options
const sortingOptions = [
  { id: 'natural', label: t('tools.fileRenamer.sorting.natural') },
  { id: 'filename', label: t('tools.fileRenamer.sorting.filename') },
  { id: 'modifiedTime', label: t('tools.fileRenamer.sorting.modifiedTime') },
  { id: 'modifiedTimeDesc', label: t('tools.fileRenamer.sorting.modifiedTimeDesc') },
  { id: 'random', label: t('tools.fileRenamer.sorting.random') },
  { id: 'reverse', label: t('tools.fileRenamer.sorting.reverse') },
  { id: 'manual', label: t('tools.fileRenamer.sorting.manual') },
]

// File handling
const handleFileDrop = (event: DragEvent) => {
  event.preventDefault()
  isDragging.value = false

  const droppedFiles = Array.from(event.dataTransfer?.files || [])
  processFiles(droppedFiles)
}

const handleFileSelect = (event: Event) => {
  const target = event.target as HTMLInputElement
  const selectedFiles = Array.from(target.files || [])
  processFiles(selectedFiles)
}

const fileInputClick = () => {
  if (fileInput.value) {
    fileInput.value.click()
  }
}

const processFiles = (fileList: File[]) => {
  const newFiles: FileItem[] = fileList.map((file) => ({
    id: `${file.name}-${file.lastModified}-${file.size}`, // Unique ID for each file
    file,
    originalName: file.name,
    size: file.size,
    type: file.type,
    lastModified: file.lastModified,
  }))

  files.value = [...files.value, ...newFiles]
  hasPreview.value = false
  hasRenamed.value = false

  success(t('tools.fileRenamer.messages.filesAdded', { count: newFiles.length }))
}

// Utility functions
const formatFileSize = (bytes: number): string => {
  if (bytes === 0) return '0 Bytes'
  const k = 1024
  const sizes = ['Bytes', 'KB', 'MB', 'GB']
  const i = Math.floor(Math.log(bytes) / Math.log(k))
  return parseFloat((bytes / Math.pow(k, i)).toFixed(2)) + ' ' + sizes[i]
}

const getFileNameWithoutExtension = (filename: string): string => {
  const lastDotIndex = filename.lastIndexOf('.')
  if (lastDotIndex === -1) return filename
  return filename.substring(0, lastDotIndex)
}

const getFileExtension = (filename: string): string => {
  const lastDotIndex = filename.lastIndexOf('.')
  if (lastDotIndex === -1) return ''
  return filename.substring(lastDotIndex)
}

// Sorting function
const sortFiles = (type: string) => {
  sortType.value = type
}

// Renaming functions
const generatePreview = () => {
  sortedFiles.value.forEach((file, index) => {
    let newName = file.originalName

    // Apply sequential renaming
    if (activeTab.value === 'sequential') {
      const nameWithoutExt = getFileNameWithoutExtension(file.originalName) // eslint-disable-line @typescript-eslint/no-unused-vars
      const extension = getFileExtension(file.originalName)
      const number = (sequentialOptions.value.startNumber + index)
        .toString()
        .padStart(sequentialOptions.value.padding, '0')
      newName = `${sequentialOptions.value.prefix}${number}${extension}`
    }

    // Apply replace renaming
    else if (activeTab.value === 'replace' && replaceOptions.value.findText) {
      const flags = replaceOptions.value.caseSensitive ? 'g' : 'gi'
      const regex = new RegExp(
        replaceOptions.value.findText.replace(/[.*+?^${}()|[\]\\]/g, '\\$&'),
        flags,
      )
      newName = file.originalName.replace(regex, replaceOptions.value.replaceText)
    }

    // Apply case transformation
    else if (activeTab.value === 'case') {
      const nameWithoutExt = getFileNameWithoutExtension(file.originalName)
      const extension = getFileExtension(file.originalName)

      let transformedName = nameWithoutExt
      if (caseOptions.value.type === 'uppercase') {
        transformedName = nameWithoutExt.toUpperCase()
      } else if (caseOptions.value.type === 'lowercase') {
        transformedName = nameWithoutExt.toLowerCase()
      } else if (caseOptions.value.type === 'capitalize') {
        transformedName = nameWithoutExt
          .split(' ')
          .map((word) => word.charAt(0).toUpperCase() + word.slice(1).toLowerCase())
          .join(' ')
      }

      newName = `${transformedName}${extension}`
    }

    // Apply text insertion
    else if (activeTab.value === 'insert' && insertOptions.value.text) {
      const nameWithoutExt = getFileNameWithoutExtension(file.originalName)
      const extension = getFileExtension(file.originalName)

      if (insertOptions.value.position === 'prefix') {
        newName = `${insertOptions.value.text}${nameWithoutExt}${extension}`
      } else if (insertOptions.value.position === 'suffix') {
        newName = `${nameWithoutExt}${insertOptions.value.text}${extension}`
      } else if (insertOptions.value.position === 'index') {
        const index = Math.min(insertOptions.value.index, nameWithoutExt.length)
        const before = nameWithoutExt.substring(0, index)
        const after = nameWithoutExt.substring(index)
        newName = `${before}${insertOptions.value.text}${after}${extension}`
      }
    }

    // Apply truncation
    else if (activeTab.value === 'truncate') {
      const nameWithoutExt = getFileNameWithoutExtension(file.originalName)
      const extension = getFileExtension(file.originalName)

      const start = Math.max(0, truncateOptions.value.startIndex)
      const end = truncateOptions.value.endIndex || nameWithoutExt.length
      const truncatedName = nameWithoutExt.substring(start, Math.min(end, nameWithoutExt.length))

      newName = `${truncatedName}${extension}`
    }

    file.newName = newName
  })

  hasPreview.value = true
  success(t('tools.fileRenamer.messages.previewGenerated'))
}

const applyRename = () => {
  sortedFiles.value.forEach((file) => {
    if (file.newName && file.newName !== file.originalName) {
      // Create a new file with the new name
      const newFile = new File([file.file], file.newName, { type: file.file.type })
      file.file = newFile
      file.originalName = file.newName
    }
  })

  hasRenamed.value = true
  hasPreview.value = false
  success(t('tools.fileRenamer.messages.renameApplied'))
}

const downloadFiles = async () => {
  if (!hasRenamed.value) return

  try {
    // Import JSZip dynamically
    const JSZip = (await import('jszip')).default
    const zip = new JSZip()

    sortedFiles.value.forEach((file) => {
      zip.file(file.originalName, file.file)
    })

    const content = await zip.generateAsync({ type: 'blob' })
    const url = URL.createObjectURL(content)
    const a = document.createElement('a')
    a.href = url
    a.download = 'renamed-files.zip'
    document.body.appendChild(a)
    a.click()
    document.body.removeChild(a)
    URL.revokeObjectURL(url)

    success(t('tools.fileRenamer.messages.downloadStarted'))
  } catch (err) {
    console.error('Download error:', err)
    const { error } = useToast()
    error(t('tools.fileRenamer.messages.downloadError'))
  }
}

const clearFiles = () => {
  files.value = []
  hasPreview.value = false
  hasRenamed.value = false
  info(t('tools.fileRenamer.messages.filesCleared'))
}

// Drag and drop event handlers for vue.draggable
const handleDragStart = () => {
  // Can be used for additional logic when dragging starts
}

const handleDragEnd = () => {
  // Can be used for additional logic when dragging ends
  // For manual sorting, we might want to update the preview if it exists
  if (hasPreview.value && sortType.value === 'manual') {
    generatePreview()
  }
}
</script>

// src/pages/tools/Media/FileRenamer.tsx
import React, { useState, useEffect, useMemo } from 'react';
import {
    Card,
    Tabs,
    Input,
    Button,
    Typography,
    Space,
    Upload,
    message,
    Select,
    Checkbox,
    Radio,
    Table,
    Modal
} from 'antd';
import { FormattedMessage, useIntl } from 'react-intl';
import {
    FileAddOutlined,
    DeleteOutlined,
    DownloadOutlined,
    ClearOutlined,
    CodeOutlined,
    MenuOutlined
} from '@ant-design/icons';
import JSZip from 'jszip';
import { DndContext, closestCenter, KeyboardSensor, PointerSensor, useSensor, useSensors } from '@dnd-kit/core';
import { arrayMove, SortableContext, sortableKeyboardCoordinates, verticalListSortingStrategy, useSortable } from '@dnd-kit/sortable';
import { CSS } from '@dnd-kit/utilities';

const { Title, Text } = Typography;
const { Dragger } = Upload;
const { Option } = Select;

// --- Interfaces ---
interface FileInfo {
    id: string;
    file: File;
    originalName: string;
    currentName: string; // The name after applying rename logic (preview)
    size: number;
    type: string;
    lastModified: number;
}

interface SequentialOptions {
    prefix: string;
    startNumber: number;
    padding: number;
}

interface ReplaceOptions {
    findText: string;
    replaceText: string;
    caseSensitive: boolean;
}

interface CaseOptions {
    type: 'uppercase' | 'lowercase' | 'capitalize';
}

interface InsertOptions {
    text: string;
    position: 'prefix' | 'suffix' | 'index';
    index: number;
}

interface TruncateOptions {
    startIndex: number;
    endIndex: number; // 0 means end of string
}

const SortableRow = ({ children, ...props }: any) => {
    const {
        attributes,
        listeners,
        setNodeRef,
        transform,
        transition,
        isDragging,
    } = useSortable({
        id: props['data-row-key'],
    });

    const style: React.CSSProperties = {
        ...props.style,
        transform: CSS.Transform.toString(transform && { ...transform, scaleY: 1 }),
        transition,
        cursor: 'move',
        ...(isDragging ? { position: 'relative', zIndex: 9999 } : {}),
    };

    return (
        <tr {...props} ref={setNodeRef} style={style} {...attributes} {...listeners}>
            {children}
        </tr>
    );
};


const FileRenamer: React.FC = () => {
    const intl = useIntl();
    // --- State ---
    const [files, setFiles] = useState<FileInfo[]>([]);
    const [activeTab, setActiveTab] = useState('sequential');
    const [sortType, setSortType] = useState('natural');
    const [showScriptModal, setShowScriptModal] = useState(false);
    const [scriptType, setScriptType] = useState<'windows' | 'linux'>('windows');

    // Options
    const [sequentialOptions, setSequentialOptions] = useState<SequentialOptions>({ prefix: '', startNumber: 1, padding: 3 });
    const [replaceOptions, setReplaceOptions] = useState<ReplaceOptions>({ findText: '', replaceText: '', caseSensitive: false });
    const [caseOptions, setCaseOptions] = useState<CaseOptions>({ type: 'lowercase' });
    const [insertOptions, setInsertOptions] = useState<InsertOptions>({ text: '', position: 'prefix', index: 0 });
    const [truncateOptions, setTruncateOptions] = useState<TruncateOptions>({ startIndex: 0, endIndex: 0 });

    // --- Helpers ---
    const formatFileSize = (bytes: number): string => {
        if (bytes === 0) return '0 Bytes';
        const k = 1024;
        const sizes = ['Bytes', 'KB', 'MB', 'GB'];
        const i = Math.floor(Math.log(bytes) / Math.log(k));
        return parseFloat((bytes / Math.pow(k, i)).toFixed(2)) + ' ' + sizes[i];
    };

    const getFileNameWithoutExtension = (filename: string): string => {
        const lastDotIndex = filename.lastIndexOf('.');
        if (lastDotIndex === -1) return filename;
        return filename.substring(0, lastDotIndex);
    };

    const getFileExtension = (filename: string): string => {
        const lastDotIndex = filename.lastIndexOf('.');
        if (lastDotIndex === -1) return '';
        return filename.substring(lastDotIndex);
    };

    // --- Core Logic ---
    const generatePreviewName = (file: FileInfo, index: number) => {
        const originalName = file.originalName;
        let tmpName = originalName;

        if (activeTab === 'sequential') {
            const extension = getFileExtension(originalName);
            const number = (sequentialOptions.startNumber + index).toString().padStart(sequentialOptions.padding, '0');
            tmpName = `${sequentialOptions.prefix}${number}${extension}`;
        }
        else if (activeTab === 'replace' && replaceOptions.findText) {
            const flags = replaceOptions.caseSensitive ? 'g' : 'gi';
            try {
                // Escape regex special characters if not intended as regex? 
                // Vue code did: replace(/[.*+?^${}()|[\]\\]/g, '\\$&')
                const safeFind = replaceOptions.findText.replace(/[.*+?^${}()|[\]\\]/g, '\\$&');
                const regex = new RegExp(safeFind, flags);
                tmpName = originalName.replace(regex, replaceOptions.replaceText);
            } catch (e) {
                // ignore invalid regex
            }
        }
        else if (activeTab === 'case') {
            const nameWithoutExt = getFileNameWithoutExtension(originalName);
            const extension = getFileExtension(originalName);
            let transformed = nameWithoutExt;

            if (caseOptions.type === 'uppercase') transformed = nameWithoutExt.toUpperCase();
            else if (caseOptions.type === 'lowercase') transformed = nameWithoutExt.toLowerCase();
            else if (caseOptions.type === 'capitalize') {
                transformed = nameWithoutExt.split(' ')
                    .map(word => word.charAt(0).toUpperCase() + word.slice(1).toLowerCase())
                    .join(' ');
            }
            tmpName = `${transformed}${extension}`;
        }
        else if (activeTab === 'insert' && insertOptions.text) {
            const nameWithoutExt = getFileNameWithoutExtension(originalName);
            const extension = getFileExtension(originalName);

            if (insertOptions.position === 'prefix') {
                tmpName = `${insertOptions.text}${nameWithoutExt}${extension}`;
            } else if (insertOptions.position === 'suffix') {
                tmpName = `${nameWithoutExt}${insertOptions.text}${extension}`;
            } else if (insertOptions.position === 'index') {
                const idx = Math.min(Math.max(0, insertOptions.index), nameWithoutExt.length);
                const before = nameWithoutExt.substring(0, idx);
                const after = nameWithoutExt.substring(idx);
                tmpName = `${before}${insertOptions.text}${after}${extension}`;
            }
        }
        else if (activeTab === 'truncate') {
            const nameWithoutExt = getFileNameWithoutExtension(originalName);
            const extension = getFileExtension(originalName);
            const start = Math.max(0, truncateOptions.startIndex);
            const end = truncateOptions.endIndex || nameWithoutExt.length;
            const truncated = nameWithoutExt.substring(start, Math.min(end, nameWithoutExt.length));
            tmpName = `${truncated}${extension}`;
        }

        return tmpName;
    };

    // Update files with preview names whenever options change
    useEffect(() => {
        setFiles(prev => prev.map((f, i) => ({
            ...f,
            currentName: generatePreviewName(f, i)
        })));
    }, [files.length, activeTab, sequentialOptions, replaceOptions, caseOptions, insertOptions, truncateOptions]);
    // Note: Including 'files.length' and option dependencies. We should NOT include 'files' itself to avoid loop if we updated inside. 
    // actually we need to re-run if order changes or options change. 
    // If we only update `currentName`, we might need a separate state or just derivation.
    // Let's use derivation on render or a specific effect that depends on the *Order* of IDs and Options.

    // Better approach: Derived state.
    // However, we want to persist the 'files' order.
    // Let's create a computed list for rendering.
    const processedFiles = useMemo(() => {
        return files.map((file, index) => ({
            ...file,
            currentName: generatePreviewName(file, index)
        }));
    }, [files, activeTab, sequentialOptions, replaceOptions, caseOptions, insertOptions, truncateOptions]);


    // --- Handlers ---
    const addFiles = (newFiles: File[]) => {
        const fileInfos: FileInfo[] = newFiles.map(f => ({
            id: Math.random().toString(36).substr(2, 9),
            file: f,
            originalName: f.name,
            currentName: f.name,
            size: f.size,
            type: f.type,
            lastModified: f.lastModified
        }));
        setFiles(prev => [...prev, ...fileInfos]);
    };

    const handleClear = () => setFiles([]);

    const handleSort = (type: string) => {
        setSortType(type);
        const sorted = [...files];
        if (type === 'natural') {
            sorted.sort((a, b) => a.originalName.localeCompare(b.originalName, undefined, { numeric: true, sensitivity: 'base' }));
        } else if (type === 'filename') {
            sorted.sort((a, b) => a.originalName.localeCompare(b.originalName));
        } else if (type === 'modifiedTime') {
            sorted.sort((a, b) => a.lastModified - b.lastModified);
        } else if (type === 'modifiedTimeDesc') {
            sorted.sort((a, b) => b.lastModified - a.lastModified);
        } else if (type === 'reverse') {
            sorted.reverse();
        }
        setFiles(sorted);
    };

    const handleDownload = async () => {
        if (processedFiles.length === 0) return;
        const zip = new JSZip();
        processedFiles.forEach(file => {
            // Handle duplicates? JSZip overwrites by default or we can rename.
            // For now assume unique names or overwrite.
            zip.file(file.currentName, file.file);
        });

        try {
            const content = await zip.generateAsync({ type: 'blob' });
            const url = URL.createObjectURL(content);
            const link = document.createElement('a');
            link.href = url;
            link.download = `renamed_files_${Date.now()}.zip`;
            document.body.appendChild(link);
            link.click();
            document.body.removeChild(link);
            URL.revokeObjectURL(url);
            message.success(intl.formatMessage({ id: 'common.downloadSuccess' }));
        } catch (e) {
            console.error(e);
            message.error(intl.formatMessage({ id: 'tools.favicon.zipError' }));
        }
    };

    const generateScript = () => {
        let content = '';
        if (scriptType === 'windows') {
            content = '@echo off\r\n';
            processedFiles.forEach(file => {
                if (file.currentName !== file.originalName) {
                    content += `ren "${file.originalName}" "${file.currentName}"\r\n`;
                }
            });
        } else {
            content = '#!/bin/bash\n';
            processedFiles.forEach(file => {
                if (file.currentName !== file.originalName) {
                    content += `mv "${file.originalName}" "${file.currentName}"\n`;
                }
            });
        }
        return content;
    };

    const handleCopyScript = () => {
        const content = generateScript();
        navigator.clipboard.writeText(content);
        message.success(intl.formatMessage({ id: 'common.copySuccess' }));
    };

    const sensors = useSensors(
        useSensor(PointerSensor),
        useSensor(KeyboardSensor, {
            coordinateGetter: sortableKeyboardCoordinates,
        })
    );

    const handleDragEnd = (event: any) => {
        const { active, over } = event;
        if (active.id !== over?.id) {
            setFiles((items) => {
                const oldIndex = items.findIndex((i) => i.id === active.id);
                const newIndex = items.findIndex((i) => i.id === over?.id);
                return arrayMove(items, oldIndex, newIndex);
            });
        }
    };

    // --- Render ---
    const columns = [
        {
            title: '',
            key: 'sort',
            width: 50,
            render: () => <MenuOutlined style={{ cursor: 'move', color: '#999' }} />,
        },
        { title: <FormattedMessage id="tools.fileRenamer.originalName" />, dataIndex: 'originalName', key: 'originalName', ellipsis: true },
        {
            title: <FormattedMessage id="tools.fileRenamer.newName" />,
            dataIndex: 'currentName',
            key: 'currentName',
            ellipsis: true,
            render: (text: string, record: FileInfo) => (
                <span className={text !== record.originalName ? 'text-green-400 font-medium' : ''}>{text}</span>
            )
        },
        {
            title: <FormattedMessage id="tools.jsonFormatter.stats.size" />,
            dataIndex: 'size',
            key: 'size',
            width: 100,
            render: (size: number) => formatFileSize(size)
        },
        {
            title: <FormattedMessage id="common.action" />,
            key: 'action',
            width: 80,
            render: (_: any, record: FileInfo) => (
                <Button
                    type="text"
                    danger
                    icon={<DeleteOutlined />}
                    onClick={() => setFiles(prev => prev.filter(f => f.id !== record.id))}
                />
            )
        }
    ];

    return (
        <div className="max-w-7xl mx-auto px-4">
            <div className="text-center mb-12">
                <Title level={1} className="text-white mb-4">
                    <FormattedMessage id="tools.fileRenamer.name" />
                </Title>
                <Text className="text-lg">
                    <FormattedMessage id="tools.fileRenamer.description" />
                </Text>
            </div>

            <Space orientation='vertical' style={{ width: "100%" }}>
                {/* Upload Area */}
                <Card className="bg-white/5 border-slate-700 mb-6">
                    <Dragger
                        customRequest={({ file, onSuccess }) => {
                            addFiles([file as File]);
                            setTimeout(() => onSuccess?.("ok"), 0);
                        }}
                        showUploadList={false}
                        multiple
                        className="bg-transparent border-slate-600 hover:border-primary-500"
                    >
                        <p className="ant-upload-drag-icon"><FileAddOutlined className="text-5xl" /></p>
                        <p className="text-xl mt-4"><FormattedMessage id="tools.fileRenamer.uploadText" /></p>
                        <p className="mt-2"><FormattedMessage id="tools.fileRenamer.uploadHint" /></p>
                    </Dragger>
                </Card>
                {files.length > 0 && (
                    <Space orientation='vertical'>
                        {/* Controls */}
                        <Card className="bg-white/5 border-slate-700">
                            <Space className="mb-4 w-full justify-between wrap">
                                <Space wrap>
                                    <FormattedMessage id="tools.imageListProcessor.total" values={{ count: files.length }} /> ({formatFileSize(files.reduce((a, b) => a + b.size, 0))})
                                    <Select value={sortType} onChange={handleSort} style={{ width: 140 }}>
                                        <Option value="natural"><FormattedMessage id="tools.fileRenamer.sort.natural" /></Option>
                                        <Option value="filename"><FormattedMessage id="tools.fileRenamer.sort.filename" /></Option>
                                        <Option value="modifiedTime"><FormattedMessage id="tools.fileRenamer.sort.modifiedTime" /></Option>
                                        <Option value="reverse"><FormattedMessage id="tools.fileRenamer.sort.reverse" /></Option>
                                    </Select>
                                </Space>
                                <Space>
                                    <Button icon={<CodeOutlined />} onClick={() => setShowScriptModal(true)}><FormattedMessage id="tools.fileRenamer.script" /></Button>
                                    <Button icon={<DownloadOutlined />} type="primary" onClick={handleDownload}><FormattedMessage id="tools.fileRenamer.download" /></Button>
                                    <Button icon={<ClearOutlined />} onClick={handleClear}><FormattedMessage id="common.clear" /></Button>
                                </Space>
                            </Space>

                            <Tabs
                                activeKey={activeTab}
                                onChange={setActiveTab}
                                type="card"
                                items={[
                                    {
                                        label: intl.formatMessage({ id: 'tools.fileRenamer.tab.sequential' }), key: 'sequential', children: (
                                            <div className="grid grid-cols-1 md:grid-cols-3 gap-4 pt-4">
                                                <div>
                                                    <div className="mb-1"><FormattedMessage id="tools.fileRenamer.prefix" /></div>
                                                    <Input value={sequentialOptions.prefix} onChange={e => setSequentialOptions({ ...sequentialOptions, prefix: e.target.value })} placeholder="Img_" />
                                                </div>
                                                <div>
                                                    <div className="mb-1"><FormattedMessage id="tools.fileRenamer.startNumber" /></div>
                                                    <Input type="number" value={sequentialOptions.startNumber} onChange={e => setSequentialOptions({ ...sequentialOptions, startNumber: parseInt(e.target.value) || 1 })} />
                                                </div>
                                                <div>
                                                    <div className="mb-1"><FormattedMessage id="tools.fileRenamer.padding" /></div>
                                                    <Input type="number" value={sequentialOptions.padding} onChange={e => setSequentialOptions({ ...sequentialOptions, padding: parseInt(e.target.value) || 1 })} />
                                                </div>
                                            </div>
                                        )
                                    },
                                    {
                                        label: intl.formatMessage({ id: 'tools.fileRenamer.tab.replace' }), key: 'replace', children: (
                                            <div className="grid grid-cols-1 md:grid-cols-2 gap-4 pt-4">
                                                <div>
                                                    <div className="mb-1"><FormattedMessage id="tools.fileRenamer.find" /></div>
                                                    <Input value={replaceOptions.findText} onChange={e => setReplaceOptions({ ...replaceOptions, findText: e.target.value })} />
                                                </div>
                                                <div>
                                                    <div className="mb-1"><FormattedMessage id="tools.fileRenamer.replace" /></div>
                                                    <Input value={replaceOptions.replaceText} onChange={e => setReplaceOptions({ ...replaceOptions, replaceText: e.target.value })} />
                                                </div>
                                                <Checkbox checked={replaceOptions.caseSensitive} onChange={e => setReplaceOptions({ ...replaceOptions, caseSensitive: e.target.checked })}><FormattedMessage id="tools.fileRenamer.caseSensitive" /></Checkbox>
                                            </div>
                                        )
                                    },
                                    {
                                        label: intl.formatMessage({ id: 'tools.fileRenamer.tab.case' }), key: 'case', children: (
                                            <div className="pt-4">
                                                <Radio.Group value={caseOptions.type} onChange={e => setCaseOptions({ ...caseOptions, type: e.target.value })}>
                                                    <Radio.Button value="lowercase">lowercase</Radio.Button>
                                                    <Radio.Button value="uppercase">UPPERCASE</Radio.Button>
                                                    <Radio.Button value="capitalize">Capitalize</Radio.Button>
                                                </Radio.Group>
                                            </div>
                                        )
                                    },
                                    {
                                        label: intl.formatMessage({ id: 'tools.fileRenamer.tab.insert' }), key: 'insert', children: (
                                            <div className="grid grid-cols-1 md:grid-cols-2 gap-4 pt-4">
                                                <div>
                                                    <div className="mb-1"><FormattedMessage id="common.text" /></div>
                                                    <Input value={insertOptions.text} onChange={e => setInsertOptions({ ...insertOptions, text: e.target.value })} />
                                                </div>
                                                <div>
                                                    <div className="mb-1"><FormattedMessage id="tools.fileRenamer.position" /></div>
                                                    <Select value={insertOptions.position} onChange={v => setInsertOptions({ ...insertOptions, position: v })} style={{ width: '100%' }}>
                                                        <Option value="prefix">Prefix</Option>
                                                        <Option value="suffix">Suffix</Option>
                                                        <Option value="index">At Index</Option>
                                                    </Select>
                                                </div>
                                                {insertOptions.position === 'index' && (
                                                    <div>
                                                        <div className="mb-1"><FormattedMessage id="tools.fileRenamer.index" /></div>
                                                        <Input type="number" value={insertOptions.index} onChange={e => setInsertOptions({ ...insertOptions, index: parseInt(e.target.value) || 0 })} />
                                                    </div>
                                                )}
                                            </div>
                                        )
                                    },
                                    {
                                        label: intl.formatMessage({ id: 'tools.fileRenamer.tab.truncate' }), key: 'truncate', children: (
                                            <div className="grid grid-cols-1 md:grid-cols-2 gap-4 pt-4">
                                                <div>
                                                    <div className="mb-1"><FormattedMessage id="tools.fileRenamer.startIndex" /></div>
                                                    <Input type="number" value={truncateOptions.startIndex} onChange={e => setTruncateOptions({ ...truncateOptions, startIndex: parseInt(e.target.value) || 0 })} />
                                                </div>
                                                <div>
                                                    <div className="mb-1"><FormattedMessage id="tools.fileRenamer.endIndex" /></div>
                                                    <Input type="number" value={truncateOptions.endIndex} onChange={e => setTruncateOptions({ ...truncateOptions, endIndex: parseInt(e.target.value) || 0 })} />
                                                </div>
                                            </div>
                                        )
                                    }
                                ]}
                            />
                        </Card>

                        {/* File List */}
                        <Card className="bg-white/5 border-slate-700 overflow-hidden" bodyStyle={{ padding: 0 }}>
                            <DndContext sensors={sensors} collisionDetection={closestCenter} onDragEnd={handleDragEnd}>
                                <SortableContext items={processedFiles.map(f => f.id)} strategy={verticalListSortingStrategy}>
                                    <Table
                                        dataSource={processedFiles}
                                        columns={columns}
                                        rowKey="id"
                                        pagination={false}
                                        components={{
                                            body: {
                                                row: SortableRow,
                                            },
                                        }}
                                        className="ant-table-transparent"
                                    />
                                </SortableContext>
                            </DndContext>
                        </Card>
                    </Space>
                )}
            </Space>

            <Modal
                title={<FormattedMessage id="tools.fileRenamer.script" />}
                open={showScriptModal}
                onCancel={() => setShowScriptModal(false)}
                footer={[
                    <Button key="copy" onClick={handleCopyScript}><FormattedMessage id="common.copy" /></Button>,
                    <Button key="close" onClick={() => setShowScriptModal(false)}><FormattedMessage id="common.cancel" /></Button>
                ]}
            >
                <div className="mb-4">
                    <Select value={scriptType} onChange={setScriptType} style={{ width: 120 }}>
                        <Option value="windows">Windows</Option>
                        <Option value="linux">Linux / Mac</Option>
                    </Select>
                </div>
                <Input.TextArea
                    value={generateScript()}
                    rows={10}
                    readOnly
                    className="font-mono text-green-400"
                />
            </Modal>
        </div>
    );
};

export default FileRenamer;
