// src/tools/image/ImageListProcessor.vue
<template>
  <div class="min-h-screen bg-gray-50 py-8">
    <div class="max-w-7xl mx-auto px-4 sm:px-6 lg:px-8">
      <!-- Header -->
      <div class="bg-white rounded-lg shadow-md p-6 mb-8">
        <h1 class="text-3xl font-bold text-gray-900 mb-4">
          🖼️ {{ $t('tools.imageListProcessor.title') }}
        </h1>
        <p class="text-gray-600 text-lg">
          {{ $t('tools.imageListProcessor.description') }}
        </p>
      </div>

      <!-- Input Section -->
      <div class="bg-white rounded-lg shadow-md p-6 mb-8">
        <h3 class="text-lg font-semibold text-gray-900 mb-4 border-b border-gray-200 pb-2">
          {{ $t('tools.imageListProcessor.inputTitle') }}
        </h3>
        <p class="text-sm text-gray-600 mb-4">
          {{ $t('tools.imageListProcessor.inputNote') }}
        </p>
        <textarea
          v-model="inputData"
          @input="processImages"
          class="w-full h-64 p-4 border border-gray-300 rounded-lg resize-vertical focus:ring-2 focus:ring-blue-500 focus:border-blue-500 font-mono text-sm"
          :placeholder="$t('tools.imageListProcessor.inputPlaceholder')"
        ></textarea>
      </div>

      <!-- Actions -->
      <div class="bg-white rounded-lg shadow-md p-6 mb-8" v-if="imageList.length > 0">
        <div class="flex flex-wrap items-center gap-4">
          <button
            @click="clearAll"
            class="px-6 py-2 bg-gray-600 text-white rounded-lg hover:bg-gray-700 transition-colors"
          >
            🗑️ {{ $t('common.clear') }}
          </button>
          <button
            @click="copyUrls"
            class="px-6 py-2 bg-blue-600 text-white rounded-lg hover:bg-blue-700 transition-colors"
          >
            📋 {{ $t('common.copy') }} URLs
          </button>
          <div class="text-sm text-gray-600">
            {{ $t('common.total') }}: {{ imageList.length }} {{ $t('common.items') }}
          </div>
        </div>
      </div>

      <!-- Image Gallery -->
      <div class="bg-white rounded-lg shadow-md p-6 mb-8" v-if="imageList.length > 0">
        <h3 class="text-lg font-semibold text-gray-900 mb-6 border-b border-gray-200 pb-2">
          {{ $t('tools.imageListProcessor.imagePreview') }}
        </h3>
        <div class="grid grid-cols-1 sm:grid-cols-2 lg:grid-cols-4 gap-6">
          <div
            v-for="(image, index) in imageList"
            :key="index"
            class="bg-gray-50 rounded-lg overflow-hidden shadow-sm hover:shadow-md transition-shadow"
          >
            <div class="aspect-square relative bg-gray-100">
              <img
                referrerpolicy="no-referrer"
                :src="image.url"
                :alt="image.alt || `Image ${index + 1}`"
                @error="handleImageError"
                @load="handleImageLoad"
                class="w-full h-full object-cover cursor-pointer hover:scale-105 transition-transform duration-200"
                @click="openImageModal(image)"
              />
              <div
                v-if="image.loading"
                class="absolute inset-0 bg-gray-200 animate-pulse flex items-center justify-center"
              >
                <div class="text-gray-500 text-sm">{{ $t('common.loading') }}</div>
              </div>
              <div
                v-if="image.error"
                class="absolute inset-0 bg-red-50 flex items-center justify-center p-4"
              >
                <div class="text-red-500 text-sm text-center">
                  ❌ {{ $t('tools.imageListProcessor.imageError') }}
                </div>
              </div>
            </div>
            <div class="p-3">
              <div class="text-xs text-gray-600 truncate" :title="image.url">
                {{ image.filename || extractFilename(image.url) }}
              </div>
              <div class="text-xs text-gray-400 mt-1 truncate" :title="image.url">
                {{ image.url }}
              </div>
            </div>
          </div>
        </div>
      </div>

      <!-- No Results -->
      <div
        v-if="imageList.length === 0 && inputData.trim()"
        class="bg-yellow-50 border border-yellow-200 rounded-lg p-6 text-center"
      >
        <div class="text-yellow-600 text-lg mb-2">⚠️</div>
        <p class="text-yellow-800">{{ $t('tools.imageListProcessor.noResults') }}</p>
      </div>

      <!-- Empty State -->
      <div
        v-if="!inputData.trim()"
        class="bg-gray-50 border-2 border-dashed border-gray-300 rounded-lg p-12 text-center"
      >
        <div class="text-gray-400 text-6xl mb-4">🖼️</div>
        <h3 class="text-lg font-medium text-gray-900 mb-2">
          {{ $t('tools.imageListProcessor.emptyState.title') }}
        </h3>
        <p class="text-gray-600 mb-4">
          {{ $t('tools.imageListProcessor.emptyState.description') }}
        </p>
        <button
          @click="loadExampleUrls"
          class="px-6 py-2 bg-blue-600 text-white rounded-lg hover:bg-blue-700 transition-colors"
        >
          {{ $t('common.loadExample') }}
        </button>
      </div>

      <!-- Features Section -->
      <div class="grid grid-cols-1 md:grid-cols-3 gap-8 mt-12">
        <div class="bg-white p-6 rounded-lg shadow-md border-l-4 border-blue-500">
          <h3 class="text-lg font-semibold text-gray-900 mb-3">
            🔗 {{ $t('tools.imageListProcessor.features.simple.title') }}
          </h3>
          <p class="text-gray-600 text-sm">
            {{ $t('tools.imageListProcessor.features.simple.description') }}
          </p>
        </div>

        <div class="bg-white p-6 rounded-lg shadow-md border-l-4 border-green-500">
          <h3 class="text-lg font-semibold text-gray-900 mb-3">
            🖼️ {{ $t('tools.imageListProcessor.features.gallery.title') }}
          </h3>
          <p class="text-gray-600 text-sm">
            {{ $t('tools.imageListProcessor.features.gallery.description') }}
          </p>
        </div>

        <div class="bg-white p-6 rounded-lg shadow-md border-l-4 border-purple-500">
          <h3 class="text-lg font-semibold text-gray-900 mb-3">
            ⚡ {{ $t('tools.imageListProcessor.features.fast.title') }}
          </h3>
          <p class="text-gray-600 text-sm">
            {{ $t('tools.imageListProcessor.features.fast.description') }}
          </p>
        </div>
      </div>
    </div>
  </div>

  <!-- Image Modal -->
  <div
    v-if="selectedImage"
    class="fixed inset-0 bg-black bg-opacity-75 flex items-center justify-center z-50 p-4"
    @click="closeImageModal"
  >
    <div class="max-w-4xl max-h-full relative">
      <button
        @click="closeImageModal"
        class="absolute -top-10 right-0 text-white hover:text-gray-300 text-2xl"
      >
        ✕
      </button>
      <img
        :src="selectedImage.url"
        :alt="selectedImage.alt || 'Selected image'"
        class="max-w-full max-h-full object-contain"
        @click.stop
      />
      <div class="absolute bottom-0 left-0 right-0 bg-black bg-opacity-75 text-white p-4">
        <div class="text-sm truncate">{{ selectedImage.url }}</div>
      </div>
    </div>
  </div>
</template>

<script setup lang="ts">
import { ref, reactive } from 'vue'
import { useI18n } from 'vue-i18n'
import { useToast } from '@/composables/useToast'

interface ImageInfo {
  url: string
  alt?: string
  filename?: string
  loading?: boolean
  error?: boolean
}

const { t } = useI18n()
const { copySuccess, copyError } = useToast()

const inputData = ref('')
const imageList = ref<ImageInfo[]>([])
const selectedImage = ref<ImageInfo | null>(null)

// Process input data to extract image URLs
function processImages() {
  if (!inputData.value.trim()) {
    imageList.value = []
    return
  }

  const lines = inputData.value
    .split('\n')
    .map((line) => line.trim())
    .filter((line) => line && !line.startsWith('#')) // Filter out empty lines and comments

  const images: ImageInfo[] = []

  for (const line of lines) {
    if (isValidImageUrl(line)) {
      images.push({
        url: line,
        filename: extractFilename(line),
        loading: true,
        error: false,
      })
    }
  }

  // Remove duplicates based on URL
  const uniqueImages = images.filter(
    (image, index, self) => index === self.findIndex((t) => t.url === image.url),
  )

  imageList.value = uniqueImages
}

// Validate if URL is likely an image
function isValidImageUrl(url: string): boolean {
  if (!url) return false

  // Remove whitespace
  url = url.trim()
  if (!url) return false

  // Check if it starts with http/https
  if (!url.startsWith('http://') && !url.startsWith('https://')) {
    return false
  }

  return true
}

function extractFilename(url: string): string {
  try {
    const pathname = new URL(url).pathname
    return pathname.split('/').pop() || ''
  } catch {
    return url.split('/').pop() || url
  }
}

function handleImageError(event: Event) {
  const img = event.target as HTMLImageElement
  const url = img.src
  const imageIndex = imageList.value.findIndex((image) => image.url === url)
  if (imageIndex !== -1) {
    imageList.value[imageIndex].error = true
    imageList.value[imageIndex].loading = false
  }
}

function handleImageLoad(event: Event) {
  const img = event.target as HTMLImageElement
  const url = img.src
  const imageIndex = imageList.value.findIndex((image) => image.url === url)
  if (imageIndex !== -1) {
    imageList.value[imageIndex].loading = false
    imageList.value[imageIndex].error = false
  }
}

function openImageModal(image: ImageInfo) {
  selectedImage.value = image
}

function closeImageModal() {
  selectedImage.value = null
}

// Action functions
function clearAll() {
  inputData.value = ''
  imageList.value = []
}

function copyUrls() {
  if (imageList.value.length === 0) return

  const urls = imageList.value.map((image) => image.url).join('\n')
  navigator.clipboard
    .writeText(urls)
    .then(() => {
      copySuccess()
    })
    .catch(() => {
      copyError()
    })
}

function loadExampleUrls() {
  inputData.value = `https://picsum.photos/400/300?random=1
https://picsum.photos/400/300?random=2
https://picsum.photos/400/300?random=3
https://picsum.photos/400/300?random=4
https://picsum.photos/400/300?random=5
https://picsum.photos/400/300?random=6
https://picsum.photos/400/300?random=7
https://picsum.photos/400/300?random=8`
  processImages()
}
</script>

// src/pages/tools/Media/ImageListProcessor.tsx
import { useCopy } from "@/hooks/useCopy";
import {
  CloudDownloadOutlined,
  CopyOutlined,
  DeleteOutlined,
  DownloadOutlined,
  FileTextOutlined,
} from "@ant-design/icons";
import {
  Button,
  Card,
  Dropdown,
  Image,
  Input,
  Space,
  Typography,
  message,
} from "antd";
import JSZip from "jszip";
import React, { useCallback, useState } from "react";
import { FormattedMessage, useIntl } from "react-intl";

const { TextArea } = Input;
const { Text, Title, Paragraph } = Typography;

interface ImageInfo {
  url: string;
  filename: string;
  loading: boolean;
  error: boolean;
}

const ImageListProcessor: React.FC = () => {
  const intl = useIntl();
  const copy = useCopy();
  const [inputData, setInputData] = useState("");
  const [imageList, setImageList] = useState<ImageInfo[]>([]);
  const [isDownloading, setIsDownloading] = useState(false);

  const extractFilename = (url: string): string => {
    try {
      const pathname = new URL(url).pathname;
      return pathname.split("/").pop() || url;
    } catch {
      return url.split("/").pop() || url;
    }
  };

  const processImages = useCallback((value: string) => {
    setInputData(value);

    if (!value.trim()) {
      setImageList([]);
      return;
    }

    const lines = value
      .split("\n")
      .map((line) => line.trim())
      .filter((line) => line && !line.startsWith("#"));

    const images: ImageInfo[] = [];

    for (const line of lines) {
      // Basic URL validation
      if (line.startsWith("http://") || line.startsWith("https://")) {
        images.push({
          url: line,
          filename: extractFilename(line),
          loading: true,
          error: false,
        });
      }
    }

    // Deduplicate
    const uniqueImages = images.filter(
      (image, index, self) =>
        index === self.findIndex((t) => t.url === image.url)
    );

    setImageList(uniqueImages);
  }, []);

  const handleClear = () => {
    setInputData("");
    setImageList([]);
  };

  const handleCopyUrls = () => {
    if (imageList.length === 0) return;
    const urls = imageList.map((img) => img.url).join("\n");
    copy(urls);
  };

  const handleLoadExample = () => {
    const example = Array.from(
      { length: 8 },
      (_, i) => `https://picsum.photos/400/300?random=${i + 1}`
    ).join("\n");
    processImages(example);
  };

  const handleDownloadAll = async () => {
    if (imageList.length === 0) return;
    setIsDownloading(true);
    try {
      const zip = new JSZip();
      const downloadPromises = imageList.map(async (img, index) => {
        try {
          const response = await fetch(img.url);
          if (!response.ok) throw new Error("Network response was not ok");
          const blob = await response.blob();

          // Try to get extension from content-type if not in URL
          let extension = img.url.split(".").pop()?.split(/[?#]/)[0] || "";
          if (!extension || extension.length > 4) {
            const contentType = response.headers.get("content-type");
            if (contentType?.includes("image/")) {
              extension = contentType.split("/")[1];
            } else {
              extension = "png";
            }
          }

          const baseName = img.filename?.split(".")[0] || `image-${index + 1}`;
          const filename = `${baseName}.${extension}`;
          zip.file(filename, blob);
        } catch (err) {
          console.error(`Failed to download ${img.url}`, err);
        }
      });

      await Promise.all(downloadPromises);

      if (Object.keys(zip.files).length === 0) {
        throw new Error("No images were successfully downloaded");
      }

      const content = await zip.generateAsync({ type: "blob" });
      const url = URL.createObjectURL(content);
      const link = document.createElement("a");
      link.href = url;
      link.download = `images-${Date.now()}.zip`;
      document.body.appendChild(link);
      link.click();
      document.body.removeChild(link);
      URL.revokeObjectURL(url);
      message.success(
        intl.formatMessage(
          { id: "common.success" },
          { defaultMessage: "Success" }
        )
      );
    } catch (err: any) {
      console.error(err);
      message.error(
        err.message ||
          intl.formatMessage({ id: "tools.imageListProcessor.zipError" })
      );
    } finally {
      setIsDownloading(false);
    }
  };

  const handleExportScript = (format: "bat" | "sh") => {
    if (imageList.length === 0) return;

    const commands = imageList.map((img, index) => {
      const fullFilename = img.filename || `image-${index + 1}.png`;

      // Split by last dot to insert index before extension
      const lastDotIndex = fullFilename.lastIndexOf(".");
      let finalFilename;
      if (lastDotIndex !== -1) {
        finalFilename = `${fullFilename.substring(
          0,
          lastDotIndex
        )}_${index + 1}${fullFilename.substring(lastDotIndex)}`;
      } else {
        finalFilename = `${fullFilename}_${index + 1}.png`;
      }

      return `curl -L -k -o "${finalFilename}" "${img.url}"`;
    });

    const content =
      format === "bat"
        ? `@echo off\necho Downloading ${imageList.length} images...\n${commands.join("\n")}\necho Done!\npause`
        : `#!/bin/bash\necho "Downloading ${imageList.length} images..."\n${commands.join("\n")}\necho "Done!"`;

    const blob = new Blob([content], { type: "text/plain" });
    const url = URL.createObjectURL(blob);
    const link = document.createElement("a");
    link.href = url;
    link.download =
      format === "bat" ? "download_images.bat" : "download_images.sh";
    document.body.appendChild(link);
    link.click();
    document.body.removeChild(link);
    URL.revokeObjectURL(url);
    message.success(intl.formatMessage({ id: "common.success" }));
  };

  const handleBatchOpen = () => {
    if (imageList.length === 0) return;
    message.info(
      intl.formatMessage({ id: "tools.imageListProcessor.triggering" })
    );

    imageList.forEach((img, index) => {
      setTimeout(() => {
        const link = document.createElement("a");
        link.href = img.url;
        link.target = "_blank";
        link.setAttribute("download", img.filename || `image-${index + 1}`);
        document.body.appendChild(link);
        link.click();
        document.body.removeChild(link);
      }, index * 300); // 300ms delay to avoid browser blocking
    });
  };

  const downloadMenuItems = [
    {
      key: "zip",
      label: intl.formatMessage({ id: "tools.imageListProcessor.downloadAll" }),
      icon: <CloudDownloadOutlined />,
      onClick: handleDownloadAll,
      disabled: isDownloading,
    },
    {
      type: "divider" as const,
    },
    {
      key: "bat",
      label: "Download Script (Windows .bat)",
      icon: <FileTextOutlined />,
      onClick: () => handleExportScript("bat"),
    },
    {
      key: "sh",
      label: "Download Script (Linux/Mac .sh)",
      icon: <FileTextOutlined />,
      onClick: () => handleExportScript("sh"),
    },
    {
      key: "browser",
      label: intl.formatMessage({ id: "tools.imageListProcessor.openUrls" }),
      icon: <DownloadOutlined />,
      onClick: handleBatchOpen,
    },
  ];

  return (
    <div className="max-w-7xl mx-auto px-4">
      <Space orientation="vertical" style={{ width: "100%" }}>
        <div className="text-center mb-8">
          <Title level={1} className="text-white mb-2">
            <FormattedMessage id="tools.imageListProcessor.name" />
          </Title>
          <Paragraph className="text-slate-400 text-lg">
            <FormattedMessage id="tools.imageListProcessor.description" />
          </Paragraph>
        </div>

        {/* Input Section */}
        <Card
          extra={
            <Space>
              <Button size="small" onClick={handleLoadExample}>
                <FormattedMessage id="common.loadExample" />
              </Button>
              <Button
                size="small"
                danger
                icon={<DeleteOutlined />}
                onClick={handleClear}
              >
                <FormattedMessage id="common.clear" />
              </Button>
              <Button
                size="small"
                type="primary"
                ghost
                icon={<CopyOutlined />}
                onClick={handleCopyUrls}
              >
                <FormattedMessage
                  id="tools.imageListProcessor.copyUrls"
                  defaultMessage="Copy URLs"
                />
              </Button>
              <Dropdown
                menu={{ items: downloadMenuItems }}
                placement="bottomRight"
                disabled={imageList.length === 0}
              >
                <Button
                  size="small"
                  type="primary"
                  icon={<DownloadOutlined />}
                  loading={isDownloading}
                >
                  <FormattedMessage
                    id="tools.imageListProcessor.batchDownload"
                    defaultMessage="Batch Download"
                  />
                </Button>
              </Dropdown>
            </Space>
          }
          className="bg-white/5 border-slate-700 mb-8"
          title={
            <>
              <FormattedMessage
                id="tools.imageListProcessor.inputTitle"
                defaultMessage="Input"
              />
              {imageList.length > 0 && (
                <span className="text-gray-700 ml-2">
                  (
                  <FormattedMessage
                    id="tools.imageListProcessor.total"
                    values={{ count: imageList.length }}
                  />
                  )
                </span>
              )}
            </>
          }
        >
          <TextArea
            value={inputData}
            onChange={(e) => processImages(e.target.value)}
            rows={8}
            placeholder={intl.formatMessage({
              id: "tools.imageListProcessor.placeholder",
            })}
            className="font-mono text-sm border-slate-700 mb-4 bg-slate-900 text-slate-200"
          />
        </Card>

        {/* Gallery Section */}
        {imageList.length > 0 && (
          <Card
            className="bg-white/5 border-slate-700 mb-8"
            title={<FormattedMessage id="tools.imageListProcessor.gallery" />}
          >
            <Image.PreviewGroup>
              <div className="grid grid-cols-2 md:grid-cols-4 lg:grid-cols-5 gap-4">
                {imageList.map((img, idx) => (
                  <div
                    key={idx}
                    className="rounded-lg p-2 border border-slate-700/50 group hover:border-green-500/50 transition-all"
                  >
                    <div className="aspect-square w-full rounded overflow-hidden flex items-center justify-center mb-2 relative">
                      <Image
                        referrerPolicy="no-referrer"
                        src={img.url}
                        alt={img.filename}
                        className="object-contain w-full h-full"
                        fallback="https://placeholder.com/150/000000/FFFFFF?text=Error"
                      />
                    </div>
                    <div className="px-1">
                      <Text
                        className="text-xs block truncate text-slate-300"
                        title={img.filename}
                      >
                        {img.filename}
                      </Text>
                      <Text
                        className="text-slate-500 text-[10px] block truncate"
                        title={img.url}
                      >
                        {img.url}
                      </Text>
                    </div>
                  </div>
                ))}
              </div>
            </Image.PreviewGroup>
          </Card>
        )}
      </Space>
    </div>
  );
};

export default ImageListProcessor;
