// src/pages/tools/Media/QrCodeTool.tsx
import React, { useState, useEffect, useCallback } from 'react';
import {
    Card,
    Input,
    Radio,
    Button,
    Typography,
    Space,
    Upload,
    message,
    Tooltip
} from 'antd';
import {
    QrcodeOutlined,
    ScanOutlined,
    DownloadOutlined,
    CopyOutlined,
    DeleteOutlined,
    FileImageOutlined
} from '@ant-design/icons';
import QRCode from 'qrcode';
import jsQR from 'jsqr';
import JSZip from 'jszip';
import { useCopy } from '@/hooks/useCopy';
import { FormattedMessage, useIntl } from 'react-intl';

const { TextArea } = Input;
const { Title, Text, Paragraph } = Typography;
const { Dragger } = Upload;

// Interfaces
interface GeneratedQR {
    text: string;
    dataUrl: string;
}

interface RecognizedResult {
    fileName: string;
    preview?: string;
    data?: string;
    error?: string;
    status: 'success' | 'error';
}

const QrCodeTool: React.FC = () => {
    const intl = useIntl();
    const copy = useCopy();
    const [activeTab, setActiveTab] = useState('generate');

    // Generate State
    const [generateText, setGenerateText] = useState('');
    const [generateMode, setGenerateMode] = useState<'single' | 'batch'>('single');
    const [generatedQRCodes, setGeneratedQRCodes] = useState<GeneratedQR[]>([]);

    // Recognize State
    const [recognizedResults, setRecognizedResults] = useState<RecognizedResult[]>([]);

    // -------------------------------------------------------------------------
    // GENERATE LOGIC
    // -------------------------------------------------------------------------

    const handleGenerate = async () => {
        if (!generateText.trim()) return;

        try {
            if (generateMode === 'single') {
                const dataUrl = await QRCode.toDataURL(generateText.trim(), {
                    width: 300,
                    margin: 2,
                    color: { dark: '#000000', light: '#ffffff' }
                });
                setGeneratedQRCodes([{ text: generateText.trim(), dataUrl }]);
                message.success(intl.formatMessage({ id: 'tools.qrCodeTool.generateSuccess' }));
            } else {
                const lines = generateText.split('\n').map(l => l.trim()).filter(l => l);
                if (lines.length === 0) {
                    message.warning(intl.formatMessage({ id: 'tools.qrCodeTool.noValidText' }));
                    return;
                }

                const newQRs: GeneratedQR[] = [];
                for (const line of lines) {
                    const dataUrl = await QRCode.toDataURL(line, {
                        width: 300,
                        margin: 2,
                        color: { dark: '#000000', light: '#ffffff' }
                    });
                    newQRs.push({ text: line, dataUrl });
                }
                setGeneratedQRCodes(newQRs);
                message.success(intl.formatMessage({ id: 'tools.qrCodeTool.generateCount' }, { count: lines.length }));
            }
        } catch (err) {
            console.error(err);
            message.error(intl.formatMessage({ id: 'tools.qrCodeTool.generateError' }));
        }
    };

    const clearGenerated = () => {
        setGeneratedQRCodes([]);
        setGenerateText('');
    };

    const downloadSingle = (qr: GeneratedQR, index: number) => {
        const link = document.createElement('a');
        link.href = qr.dataUrl;
        link.download = `qr-code-${index + 1}.png`;
        document.body.appendChild(link);
        link.click();
        document.body.removeChild(link);
    };

    const downloadAll = async () => {
        if (generatedQRCodes.length === 0) return;
        try {
            const zip = new JSZip();
            for (let i = 0; i < generatedQRCodes.length; i++) {
                const qr = generatedQRCodes[i];
                const base64Data = qr.dataUrl.split(',')[1];
                zip.file(`qr-code-${i + 1}.png`, base64Data, { base64: true });
            }
            const content = await zip.generateAsync({ type: 'blob' });
            const url = URL.createObjectURL(content);
            const link = document.createElement('a');
            link.href = url;
            link.download = `qr-codes-${Date.now()}.zip`;
            document.body.appendChild(link);
            link.click();
            document.body.removeChild(link);
            URL.revokeObjectURL(url);
            message.success(intl.formatMessage({ id: 'toast.success' }));
        } catch (err) {
            console.error(err);
            message.error(intl.formatMessage({ id: 'tools.qrCodeTool.zipError' }));
        }
    };

    const copyImage = async (dataUrl: string) => {
        try {
            const blob = await (await fetch(dataUrl)).blob();
            await navigator.clipboard.write([
                new ClipboardItem({ [blob.type]: blob })
            ]);
            message.success(intl.formatMessage({ id: 'common.copySuccess' }));
        } catch (err) {
            message.error(intl.formatMessage({ id: 'tools.qrCodeTool.copyImageError' }));
        }
    };

    // -------------------------------------------------------------------------
    // RECOGNIZE LOGIC
    // -------------------------------------------------------------------------

    const processFiles = async (files: File[]) => {
        const imageFiles = files.filter(f => f.type.startsWith('image/'));
        if (imageFiles.length === 0) {
            message.error(intl.formatMessage({ id: 'tools.qrCodeTool.noImagesFound' }));
            return;
        }

        const results: RecognizedResult[] = [];

        for (const file of imageFiles) {
            const res: RecognizedResult = {
                fileName: file.name,
                status: 'error'
            };

            try {
                // 1. Create Preview
                const preview = await new Promise<string>((resolve, reject) => {
                    const reader = new FileReader();
                    reader.onload = (e) => resolve(e.target?.result as string);
                    reader.onerror = reject;
                    reader.readAsDataURL(file);
                });
                res.preview = preview;

                // 2. Decode
                const img = new Image();
                img.src = preview;
                await new Promise((resolve) => { img.onload = resolve; });

                const canvas = document.createElement('canvas');
                canvas.width = img.width;
                canvas.height = img.height;
                const ctx = canvas.getContext('2d');
                if (!ctx) throw new Error('Canvas context failed');

                ctx.drawImage(img, 0, 0);
                const imageData = ctx.getImageData(0, 0, canvas.width, canvas.height);

                const code = jsQR(imageData.data, imageData.width, imageData.height);

                if (code) {
                    res.data = code.data;
                    res.status = 'success';
                } else {
                    res.error = 'No QR Code found';
                }

            } catch (err) {
                console.error(err);
                res.error = 'Recognition failed';
            }
            results.push(res);
        }

        setRecognizedResults(prev => [...prev, ...results]);
        message.success(intl.formatMessage({ id: 'tools.qrCodeTool.processedCount' }, { count: imageFiles.length }));
    };

    const handleUploadRequest = ({ file, onSuccess }: any) => {
        processFiles([file]);
        setTimeout(() => onSuccess?.("ok"), 0);
    };

    const handlePaste = useCallback((event: ClipboardEvent) => {
        if (activeTab !== 'recognize') return;
        const items = event.clipboardData?.items;
        if (!items) return;

        const files: File[] = [];
        for (const item of items) {
            if (item.type.startsWith('image/')) {
                const f = item.getAsFile();
                if (f) files.push(f);
            }
        }
        if (files.length > 0) processFiles(files);
    }, [activeTab]);

    useEffect(() => {
        document.addEventListener('paste', handlePaste);
        return () => document.removeEventListener('paste', handlePaste);
    }, [handlePaste]);

    const copyAllResults = () => {
        const text = recognizedResults
            .filter(r => r.status === 'success' && r.data)
            .map(r => r.data)
            .join('\n');
        if (text) copy(text);
        else message.warning('No success results to copy');
    };

    // -------------------------------------------------------------------------
    // RENDER
    // -------------------------------------------------------------------------

    return (
        <div className="max-w-7xl mx-auto px-4">
            <div className="text-center mb-12">
                <Title level={1} className="text-white mb-4">
                    <FormattedMessage id="tools.qrCodeTool.name" />
                </Title>
                <Text className="text-lg">
                    <FormattedMessage id="tools.qrCodeTool.description" />
                </Text>
            </div>

            {/* Mode Switcher */}
            <div className="flex justify-center mb-10">
                <Radio.Group
                    value={activeTab}
                    onChange={e => setActiveTab(e.target.value)}
                    optionType="button"
                    buttonStyle="solid"
                >
                    <Radio.Button value="generate"><QrcodeOutlined /> <FormattedMessage id="tools.qrCodeTool.generate" /></Radio.Button>
                    <Radio.Button value="recognize"><ScanOutlined /> <FormattedMessage id="tools.qrCodeTool.recognize" /></Radio.Button>
                </Radio.Group>
            </div>

            {activeTab === 'generate' ? (
                <div className="animate-fade-in space-y-8">
                    <Card
                        extra={
                            <Button size='small' type="default" onClick={clearGenerated} icon={<DeleteOutlined />}>
                                <FormattedMessage id="common.clear" />
                            </Button>
                        }
                        className="bg-white/5 border-slate-700"
                        title={<FormattedMessage id="tools.qrCodeTool.inputSettings" />}
                    >
                        <Space direction="vertical" style={{ width: "100%" }} size="middle">
                            <div>
                                <Paragraph className="text-slate-400 mb-2">
                                    <FormattedMessage id="tools.qrCodeTool.inputDesc" defaultMessage="Text or URLs (supports multiline for batch mode)" />
                                </Paragraph>
                                <TextArea
                                    rows={6}
                                    value={generateText}
                                    onChange={e => setGenerateText(e.target.value)}
                                    placeholder={intl.formatMessage({ id: 'tools.qrCodeTool.inputPlaceholder' })}
                                    className="mb-4 border-slate-600 text-slate-100 placeholder-slate-500 bg-slate-900"
                                />
                            </div>

                            <div className="flex flex-col md:flex-row justify-between items-start md:items-center gap-4">
                                <Space direction="vertical">
                                    <Radio.Group value={generateMode} onChange={e => setGenerateMode(e.target.value)} buttonStyle="solid">
                                        <Radio.Button value="single"><FormattedMessage id="tools.qrCodeTool.singleMode" /></Radio.Button>
                                        <Radio.Button value="batch"><FormattedMessage id="tools.qrCodeTool.batchMode" /></Radio.Button>
                                    </Radio.Group>
                                    <Text className="text-slate-500 text-xs">
                                        {generateMode === 'single' ? intl.formatMessage({ id: 'tools.qrCodeTool.singleDesc' }) : intl.formatMessage({ id: 'tools.qrCodeTool.batchDesc' })}
                                    </Text>
                                </Space>

                                <Button type="primary" onClick={handleGenerate} size="large" icon={<QrcodeOutlined />}>
                                    <FormattedMessage id="tools.qrCodeTool.generate" />
                                </Button>
                            </div>
                        </Space>
                    </Card>

                    {generatedQRCodes.length > 0 && (
                        <Card
                            className="bg-white/5 border-slate-700"
                            title={<FormattedMessage id="tools.qrCodeTool.results" values={{ count: generatedQRCodes.length }} />}
                            extra={
                                <Button icon={<DownloadOutlined />} onClick={downloadAll} type="primary" ghost>
                                    <FormattedMessage id="tools.qrCodeTool.downloadZip" />
                                </Button>
                            }
                        >
                            <div className="grid grid-cols-1 sm:grid-cols-2 md:grid-cols-3 lg:grid-cols-4 gap-6">
                                {generatedQRCodes.map((qr, idx) => (
                                    <div key={idx} className="p-4 rounded-lg border border-slate-700/50 text-center group hover:border-primary-500/50 transition-colors bg-slate-900/50">
                                        <div className="bg-white p-2 rounded mb-3 inline-block">
                                            <img
                                                referrerPolicy='no-referrer'
                                                src={qr.dataUrl} alt="QR"
                                                className="w-48 h-48 object-contain" />
                                        </div>
                                        <Paragraph className="text-xs truncate mb-3 text-slate-300" copyable={{ text: qr.text }} title={qr.text}>
                                            {qr.text}
                                        </Paragraph>
                                        <Space size="small">
                                            <Tooltip title={intl.formatMessage({ id: 'tools.qrCodeTool.copyImage' })}>
                                                <Button size="small" icon={<CopyOutlined />} onClick={() => copyImage(qr.dataUrl)} />
                                            </Tooltip>
                                            <Tooltip title={intl.formatMessage({ id: 'common.download' })}>
                                                <Button size="small" icon={<DownloadOutlined />} type="primary" onClick={() => downloadSingle(qr, idx)} />
                                            </Tooltip>
                                        </Space>
                                    </div>
                                ))}
                            </div>
                        </Card>
                    )}
                </div>
            ) : (
                <div className="animate-fade-in space-y-8">
                    <Card className="bg-white/5 border-slate-700">
                        <Dragger
                            customRequest={handleUploadRequest}
                            multiple
                            showUploadList={false}
                            accept="image/*"
                            className="bg-transparent border-slate-600 hover:border-primary-500"
                        >
                            <p className="ant-upload-drag-icon">
                                <FileImageOutlined className="text-5xl text-slate-500" />
                            </p>
                            <p className="ant-upload-text text-xl font-medium mt-4 text-slate-200">
                                <FormattedMessage id="tools.qrCodeTool.scanTitle" />
                            </p>
                            <p className="ant-upload-hint text-slate-400 mt-2">
                                <FormattedMessage id="tools.qrCodeTool.scanHint" />
                            </p>
                        </Dragger>
                    </Card>

                    {recognizedResults.length > 0 && (
                        <Card
                            className="bg-white/5 border-slate-700"
                            title={<FormattedMessage id="tools.qrCodeTool.scanResults" values={{ count: recognizedResults.length }} />}
                            extra={
                                <Space>
                                    <Button onClick={() => setRecognizedResults([])} icon={<DeleteOutlined />}>
                                        <FormattedMessage id="common.clear" />
                                    </Button>
                                    <Button type="primary" icon={<CopyOutlined />} onClick={copyAllResults}>
                                        <FormattedMessage id="tools.qrCodeTool.copyAllResults" />
                                    </Button>
                                </Space>
                            }
                        >
                            <div className="space-y-4">
                                {recognizedResults.map((res, idx) => (
                                    <div key={idx} className={`p-4 rounded-lg border ${res.status === 'success' ? 'bg-green-500/10 border-green-500/20' : 'bg-red-500/10 border-red-500/20'} flex items-start gap-4 transition-all hover:bg-white/5`}>
                                        {res.preview && (
                                            <img
                                                referrerPolicy='no-referrer'
                                                src={res.preview} className="w-16 h-16 object-cover rounded border border-white/10" />
                                        )}
                                        <div className="flex-1 min-w-0">
                                            <Text strong className="text-slate-200 block mb-1">{res.fileName}</Text>
                                            {res.status === 'success' ? (
                                                <Paragraph className="text-green-300 font-mono text-sm break-all mb-0" copyable>
                                                    {res.data}
                                                </Paragraph>
                                            ) : (
                                                <Text className="text-red-400">{res.error}</Text>
                                            )}
                                        </div>
                                    </div>
                                ))}
                            </div>
                        </Card>
                    )}
                </div>
            )}
        </div>
    );
};

export default QrCodeTool;

// src/tools/qrcode/QrCodeTool.vue
<template>
  <div class="min-h-screen bg-gray-50">
    <div class="max-w-7xl mx-auto px-4 sm:px-6 lg:px-8 py-8">
      <!-- Hero Section -->
      <div class="text-center mb-12">
        <h1 class="text-4xl font-bold text-gray-900 mb-4">
          {{ $t('tools.qrCodeTool.title') }}
        </h1>
        <p class="text-xl text-gray-600 max-w-3xl mx-auto">
          {{ $t('tools.qrCodeTool.description') }}
        </p>
      </div>

      <!-- Toggle Switch -->
      <div class="flex justify-center mb-6">
        <div class="inline-flex rounded-md shadow-sm" role="group">
          <button
            type="button"
            @click="activeTab = 'generate'"
            :class="[
              'px-4 py-2 text-sm font-medium rounded-l-lg',
              activeTab === 'generate'
                ? 'bg-blue-600 text-white'
                : 'bg-white text-gray-700 hover:bg-gray-100',
            ]"
          >
            {{ $t('tools.qrCodeTool.tabs.generate') }}
          </button>
          <button
            type="button"
            @click="activeTab = 'recognize'"
            :class="[
              'px-4 py-2 text-sm font-medium rounded-r-lg border-l border-gray-200',
              activeTab === 'recognize'
                ? 'bg-blue-600 text-white'
                : 'bg-white text-gray-700 hover:bg-gray-100',
            ]"
          >
            {{ $t('tools.qrCodeTool.tabs.recognize') }}
          </button>
        </div>
      </div>

      <!-- Features -->
      <div class="grid md:grid-cols-3 gap-6 mb-8">
        <div class="bg-white p-6 rounded-lg shadow-sm border">
          <div class="text-2xl mb-3">🔄</div>
          <h3 class="text-lg font-semibold mb-2">
            {{ $t('tools.qrCodeTool.features.batch.title') }}
          </h3>
          <p class="text-gray-600 text-sm">
            {{ $t('tools.qrCodeTool.features.batch.description') }}
          </p>
        </div>
        <div class="bg-white p-6 rounded-lg shadow-sm border">
          <div class="text-2xl mb-3">📱</div>
          <h3 class="text-lg font-semibold mb-2">
            {{ $t('tools.qrCodeTool.features.generate.title') }}
          </h3>
          <p class="text-gray-600 text-sm">
            {{ $t('tools.qrCodeTool.features.generate.description') }}
          </p>
        </div>
        <div class="bg-white p-6 rounded-lg shadow-sm border">
          <div class="text-2xl mb-3">🔍</div>
          <h3 class="text-lg font-semibold mb-2">
            {{ $t('tools.qrCodeTool.features.recognize.title') }}
          </h3>
          <p class="text-gray-600 text-sm">
            {{ $t('tools.qrCodeTool.features.recognize.description') }}
          </p>
        </div>
      </div>

      <!-- Generate Tab -->
      <div v-show="activeTab === 'generate'" class="space-y-8">
        <!-- Text Input Section -->
        <div class="bg-white rounded-lg shadow-md p-6">
          <h3 class="text-lg font-semibold text-gray-900 mb-4">
            {{ $t('tools.qrCodeTool.generate.inputTitle') }}
          </h3>
          <div class="mb-4">
            <label class="block text-sm font-medium text-gray-700 mb-2">
              {{ $t('tools.qrCodeTool.generate.textInputLabel') }}
            </label>
            <textarea
              v-model="generateText"
              :placeholder="$t('tools.qrCodeTool.generate.textInputPlaceholder')"
              class="w-full h-40 px-3 py-2 border border-gray-300 rounded-lg focus:ring-2 focus:ring-blue-500 focus:border-blue-500"
            ></textarea>
          </div>

          <!-- Mode Toggle -->
          <div class="mb-4">
            <label class="block text-sm font-medium text-gray-700 mb-2">
              {{ $t('tools.qrCodeTool.generate.modeLabel') }}
            </label>
            <div class="flex items-center">
              <label class="inline-flex items-center">
                <input
                  type="radio"
                  v-model="generateMode"
                  value="single"
                  class="rounded border-gray-300 text-blue-600 focus:ring-blue-500"
                />
                <span class="ml-2">{{ $t('tools.qrCodeTool.generate.singleMode') }}</span>
              </label>
              <label class="inline-flex items-center ml-6">
                <input
                  type="radio"
                  v-model="generateMode"
                  value="batch"
                  class="rounded border-gray-300 text-blue-600 focus:ring-blue-500"
                />
                <span class="ml-2">{{ $t('tools.qrCodeTool.generate.batchMode') }}</span>
              </label>
            </div>
            <p class="mt-2 text-sm text-gray-500">
              {{
                generateMode === 'single'
                  ? $t('tools.qrCodeTool.generate.singleModeHint')
                  : $t('tools.qrCodeTool.generate.batchModeHint')
              }}
            </p>
          </div>

          <div class="flex flex-wrap gap-4">
            <button
              @click="generateQR"
              :disabled="!generateText.trim()"
              class="px-4 py-2 bg-blue-600 text-white rounded-lg hover:bg-blue-700 transition-colors disabled:opacity-50 disabled:cursor-not-allowed"
            >
              {{
                generateMode === 'single'
                  ? $t('tools.qrCodeTool.generate.generateSingleButton')
                  : $t('tools.qrCodeTool.generate.generateBatchButton')
              }}
            </button>
            <button
              @click="clearGenerated"
              class="px-4 py-2 bg-gray-600 text-white rounded-lg hover:bg-gray-700 transition-colors"
            >
              {{ $t('common.clear') }}
            </button>
          </div>
        </div>

        <!-- Generated QR Codes -->
        <div v-if="generatedQRCodes.length > 0" class="bg-white rounded-lg shadow-md p-6">
          <div class="flex justify-between items-center mb-6">
            <h3 class="text-lg font-semibold text-gray-900">
              {{
                generateMode === 'single'
                  ? $t('tools.qrCodeTool.generate.singleGeneratedTitle')
                  : $t('tools.qrCodeTool.generate.batchGeneratedTitle', {
                      count: generatedQRCodes.length,
                    })
              }}
            </h3>
            <button
              @click="downloadAllGenerated"
              class="px-4 py-2 bg-green-600 text-white rounded-lg hover:bg-green-700 transition-colors"
            >
              {{ $t('tools.qrCodeTool.generate.downloadAll') }}
            </button>
          </div>
          <div class="grid grid-cols-1 sm:grid-cols-2 md:grid-cols-3 lg:grid-cols-4 gap-6">
            <div
              v-for="(qr, index) in generatedQRCodes"
              :key="index"
              class="border border-gray-200 rounded-lg p-4 text-center"
            >
              <div class="mb-3">
                <img :src="qr.dataUrl" :alt="qr.text" class="w-full h-auto mx-auto" />
              </div>
              <p class="text-sm text-gray-600 truncate mb-3">{{ qr.text }}</p>
              <div class="flex flex-wrap justify-center gap-2">
                <button
                  @click="downloadQR(index)"
                  class="px-3 py-1 text-xs bg-blue-600 text-white rounded hover:bg-blue-700 transition-colors"
                >
                  {{ $t('common.download') }}
                </button>
                <button
                  @click="copyQR(index)"
                  class="px-3 py-1 text-xs bg-gray-600 text-white rounded hover:bg-gray-700 transition-colors"
                >
                  {{ $t('common.copy') }}
                </button>
              </div>
            </div>
          </div>
        </div>
      </div>

      <!-- Recognize Tab -->
      <div v-show="activeTab === 'recognize'" class="space-y-8">
        <!-- File Upload Section -->
        <div class="bg-white rounded-lg shadow-md p-6">
          <h3 class="text-lg font-semibold text-gray-900 mb-4">
            {{ $t('tools.qrCodeTool.recognize.uploadTitle') }}
          </h3>
          <div
            @drop="handleDrop"
            @dragover.prevent
            @dragenter.prevent
            @click="openFileSelector"
            :class="[
              'border-2 border-dashed rounded-lg p-8 text-center cursor-pointer transition-colors',
              isDragging ? 'border-blue-500 bg-blue-50' : 'border-gray-300 hover:border-gray-400',
            ]"
          >
            <input
              ref="fileInput"
              type="file"
              multiple
              accept="image/*"
              @change="handleFileSelect"
              class="hidden"
            />
            <div class="space-y-4">
              <div class="text-4xl text-gray-400">📷</div>
              <div>
                <h3 class="text-lg font-medium text-gray-900 mb-2">
                  {{ $t('tools.qrCodeTool.recognize.uploadInstruction') }}
                </h3>
                <p class="text-gray-600">
                  {{ $t('tools.qrCodeTool.recognize.uploadDescription') }}
                </p>
                <p class="text-sm text-gray-500 mt-2">
                  {{ $t('tools.qrCodeTool.recognize.pasteHint') }}
                </p>
              </div>
              <button
                class="px-4 py-2 bg-blue-600 text-white rounded-lg hover:bg-blue-700 transition-colors"
              >
                {{ $t('tools.qrCodeTool.recognize.selectFiles') }}
              </button>
            </div>
          </div>
        </div>

        <!-- Recognized Results -->
        <div v-if="recognizedResults.length > 0" class="bg-white rounded-lg shadow-md p-6">
          <div class="flex justify-between items-center mb-6">
            <h3 class="text-lg font-semibold text-gray-900">
              {{ $t('tools.qrCodeTool.recognize.resultsTitle') }} ({{ recognizedResults.length }})
            </h3>
            <div class="flex flex-wrap gap-3">
              <button
                @click="copyAllResults"
                class="px-4 py-2 bg-blue-600 text-white rounded-lg hover:bg-blue-700 transition-colors"
              >
                {{ $t('tools.qrCodeTool.recognize.copyAll') }}
              </button>
              <button
                @click="clearRecognized"
                class="px-4 py-2 bg-gray-600 text-white rounded-lg hover:bg-gray-700 transition-colors"
              >
                {{ $t('common.clear') }}
              </button>
            </div>
          </div>
          <div class="space-y-4">
            <div
              v-for="(result, index) in recognizedResults"
              :key="index"
              class="border border-gray-200 rounded-lg p-4"
            >
              <div class="flex items-start space-x-4">
                <div v-if="result.preview" class="flex-shrink-0">
                  <img
                    :src="result.preview"
                    :alt="result.fileName"
                    class="w-16 h-16 object-cover rounded-lg border border-gray-200"
                  />
                </div>
                <div class="flex-1 min-w-0">
                  <h4 class="text-sm font-medium text-gray-900 truncate">{{ result.fileName }}</h4>
                  <div class="mt-2">
                    <p v-if="result.status === 'success'" class="text-sm text-gray-600 break-all">
                      {{ result.data }}
                    </p>
                    <p v-else class="text-sm text-red-600">
                      {{ result.error || $t('tools.qrCodeTool.recognize.recognitionFailed') }}
                    </p>
                  </div>
                </div>
                <div class="flex-shrink-0">
                  <div
                    :class="[
                      'w-3 h-3 rounded-full',
                      result.status === 'success' ? 'bg-green-400' : 'bg-red-400',
                    ]"
                  ></div>
                </div>
              </div>
            </div>
          </div>
        </div>
      </div>
    </div>
  </div>
</template>

<script setup lang="ts">
import { ref, computed, onMounted, onUnmounted } from 'vue'
import { useI18n } from 'vue-i18n'
import { useToast } from '@/composables/useToast'
import QRCode from 'qrcode'
import jsQR from 'jsqr'

interface GeneratedQR {
  text: string
  dataUrl: string
}

interface RecognizedResult {
  fileName: string
  preview?: string
  data?: string
  error?: string
  status: 'success' | 'error'
}

const { t } = useI18n()
const { success, error: showError } = useToast()

// Tabs
const activeTab = ref<'generate' | 'recognize'>('generate')

// Generate tab
const generateText = ref('')
const generateMode = ref<'single' | 'batch'>('single')
const generatedQRCodes = ref<GeneratedQR[]>([])

// Recognize tab
const fileInput = ref<HTMLInputElement>()
const isDragging = ref(false)
const recognizedResults = ref<RecognizedResult[]>([])

// Generate QR codes based on mode
async function generateQR() {
  if (!generateText.value.trim()) return

  try {
    if (generateMode.value === 'single') {
      // Generate single QR code
      const dataUrl = await QRCode.toDataURL(generateText.value.trim(), {
        width: 300,
        margin: 2,
        color: {
          dark: '#000000',
          light: '#ffffff',
        },
      })

      generatedQRCodes.value = [
        {
          text: generateText.value.trim(),
          dataUrl,
        },
      ]

      success(t('tools.qrCodeTool.messages.generateSuccess'))
    } else {
      // Generate batch QR codes
      const lines = generateText.value
        .split('\n')
        .map((line) => line.trim())
        .filter((line) => line.length > 0)

      if (lines.length === 0) {
        showError(t('tools.qrCodeTool.errors.emptyBatch'))
        return
      }

      const newQRCodes: GeneratedQR[] = []

      for (const line of lines) {
        const dataUrl = await QRCode.toDataURL(line, {
          width: 300,
          margin: 2,
          color: {
            dark: '#000000',
            light: '#ffffff',
          },
        })

        newQRCodes.push({
          text: line,
          dataUrl,
        })
      }

      generatedQRCodes.value = newQRCodes
      success(t('tools.qrCodeTool.messages.batchGenerateSuccess', { count: lines.length }))
    }
  } catch (err) {
    console.error('QR Code generation error:', err)
    showError(
      generateMode.value === 'single'
        ? t('tools.qrCodeTool.errors.generateFailed')
        : t('tools.qrCodeTool.errors.batchGenerateFailed'),
    )
  }
}

// Clear generated QR codes
function clearGenerated() {
  generatedQRCodes.value = []
  generateText.value = ''
}

// Download single QR code
function downloadQR(index: number) {
  const qr = generatedQRCodes.value[index]
  if (!qr) return

  const link = document.createElement('a')
  link.href = qr.dataUrl
  link.download = `qr-code-${index + 1}.png`
  document.body.appendChild(link)
  link.click()
  document.body.removeChild(link)
}

// Download all generated QR codes
async function downloadAllGenerated() {
  const { default: JSZip } = await import('jszip')

  try {
    const zip = new JSZip()

    for (let i = 0; i < generatedQRCodes.value.length; i++) {
      const qr = generatedQRCodes.value[i]
      const response = await fetch(qr.dataUrl)
      const blob = await response.blob()
      zip.file(`qr-code-${i + 1}.png`, blob)
    }

    const content = await zip.generateAsync({ type: 'blob' })
    const url = URL.createObjectURL(content)
    const link = document.createElement('a')
    link.href = url
    link.download = `qr-codes-${new Date().toISOString().split('T')[0]}.zip`
    document.body.appendChild(link)
    link.click()
    document.body.removeChild(link)
    URL.revokeObjectURL(url)

    success(t('tools.qrCodeTool.messages.downloadAllSuccess'))
  } catch (err) {
    console.error('Download all error:', err)
    showError(t('tools.qrCodeTool.errors.downloadAllFailed'))
  }
}

// Copy QR code to clipboard
async function copyQR(index: number) {
  const qr = generatedQRCodes.value[index]
  if (!qr) return

  try {
    const response = await fetch(qr.dataUrl)
    const blob = await response.blob()
    await navigator.clipboard.write([
      new ClipboardItem({
        [blob.type]: blob,
      }),
    ])
    success(t('tools.qrCodeTool.messages.copySuccess'))
  } catch (err) {
    console.error('Copy error:', err)
    showError(t('tools.qrCodeTool.errors.copyFailed'))
  }
}

// File handling
function openFileSelector() {
  fileInput.value?.click()
}

function handleFileSelect(event: Event) {
  const files = (event.target as HTMLInputElement).files
  if (files) {
    recognizeFiles(Array.from(files))
  }
  // Reset the input value to allow selecting the same file again
  if (fileInput.value) {
    fileInput.value.value = ''
  }
}

function handleDrop(event: DragEvent) {
  event.preventDefault()
  isDragging.value = false

  const files = event.dataTransfer?.files
  if (files) {
    recognizeFiles(Array.from(files))
  }
}

// Handle paste event for clipboard images
function handlePaste(event: ClipboardEvent) {
  const items = event.clipboardData?.items
  if (!items) return

  const files: File[] = []
  for (const item of items) {
    if (item.type.startsWith('image/')) {
      const file = item.getAsFile()
      if (file) files.push(file)
    }
  }

  if (files.length > 0) {
    recognizeFiles(files)
    success(t('tools.qrCodeTool.messages.pasteSuccess'))
  }
}

// Recognize QR codes from files
async function recognizeFiles(files: File[]) {
  const imageFiles = files.filter((file) => file.type.startsWith('image/'))

  if (imageFiles.length === 0) {
    showError(t('tools.qrCodeTool.errors.noValidImages'))
    return
  }

  for (const file of imageFiles) {
    const result: RecognizedResult = {
      fileName: file.name,
      status: 'error',
    }

    try {
      // Create preview
      const preview = await createImagePreview(file)
      result.preview = preview

      // Recognize QR code
      const imageData = await getImageData(file)
      const code = jsQR(imageData.data, imageData.width, imageData.height)

      if (code) {
        result.data = code.data
        result.status = 'success'
      } else {
        result.error = t('tools.qrCodeTool.errors.noQRCodeFound')
      }
    } catch (err) {
      console.error('Recognition error:', err)
      result.error = t('tools.qrCodeTool.errors.recognitionFailed')
    }

    recognizedResults.value.push(result)
  }

  success(t('tools.qrCodeTool.messages.recognitionComplete'))
}

// Image processing utilities
function createImagePreview(file: File): Promise<string> {
  return new Promise((resolve, reject) => {
    const reader = new FileReader()
    reader.onload = (e) => resolve(e.target?.result as string)
    reader.onerror = reject
    reader.readAsDataURL(file)
  })
}

function getImageData(
  file: File,
): Promise<{ data: Uint8ClampedArray; width: number; height: number }> {
  return new Promise((resolve, reject) => {
    const img = new Image()
    img.onload = () => {
      const canvas = document.createElement('canvas')
      canvas.width = img.width
      canvas.height = img.height
      const ctx = canvas.getContext('2d')
      if (!ctx) {
        reject(new Error('Could not get canvas context'))
        return
      }
      ctx.drawImage(img, 0, 0)
      const imageData = ctx.getImageData(0, 0, canvas.width, canvas.height)
      resolve({
        data: imageData.data,
        width: imageData.width,
        height: imageData.height,
      })
    }
    img.onerror = reject
    img.src = URL.createObjectURL(file)
  })
}

// Copy all recognition results
function copyAllResults() {
  const successfulResults = recognizedResults.value
    .filter((result) => result.status === 'success')
    .map((result) => result.data)
    .join('\n')

  if (!successfulResults) {
    showError(t('tools.qrCodeTool.errors.noResultsToCopy'))
    return
  }

  navigator.clipboard
    .writeText(successfulResults)
    .then(() => {
      success(t('tools.qrCodeTool.messages.copyAllSuccess'))
    })
    .catch(() => {
      showError(t('tools.qrCodeTool.errors.copyAllFailed'))
    })
}

// Clear recognized results
function clearRecognized() {
  recognizedResults.value = []
}

// Lifecycle hooks
onMounted(() => {
  document.addEventListener('paste', handlePaste)

  // Drag and drop for whole page
  document.addEventListener('dragenter', (e) => {
    e.preventDefault()
    isDragging.value = true
  })

  document.addEventListener('dragleave', (e) => {
    if (!e.relatedTarget) {
      isDragging.value = false
    }
  })
})

onUnmounted(() => {
  document.removeEventListener('paste', handlePaste)
})
</script>

<style scoped>
/* Add any component-specific styles here */
</style>
