// src/tools/json/ExcelToJson.vue
<template>
  <div class="min-h-screen bg-gray-50 p-6">
    <div class="max-w-6xl mx-auto space-y-6">
      <!-- Header -->
      <div class="text-center mb-8">
        <h1 class="text-3xl font-bold text-gray-900 mb-2">{{ $t('tools.excelToJson.title') }}</h1>
        <p class="text-gray-600">{{ $t('tools.excelToJson.description') }}</p>
      </div>

      <!-- Features -->
      <div class="grid md:grid-cols-3 gap-6 mb-8">
        <div class="bg-white p-6 rounded-lg shadow-sm border">
          <div class="text-2xl mb-3">📊</div>
          <h3 class="text-lg font-semibold mb-2">
            {{ $t('tools.excelToJson.features.parsing.title') }}
          </h3>
          <p class="text-gray-600 text-sm">
            {{ $t('tools.excelToJson.features.parsing.description') }}
          </p>
        </div>
        <div class="bg-white p-6 rounded-lg shadow-sm border">
          <div class="text-2xl mb-3">🔄</div>
          <h3 class="text-lg font-semibold mb-2">
            {{ $t('tools.excelToJson.features.conversion.title') }}
          </h3>
          <p class="text-gray-600 text-sm">
            {{ $t('tools.excelToJson.features.conversion.description') }}
          </p>
        </div>
        <div class="bg-white p-6 rounded-lg shadow-sm border">
          <div class="text-2xl mb-3">⚙️</div>
          <h3 class="text-lg font-semibold mb-2">
            {{ $t('tools.excelToJson.features.options.title') }}
          </h3>
          <p class="text-gray-600 text-sm">
            {{ $t('tools.excelToJson.features.options.description') }}
          </p>
        </div>
      </div>

      <div class="grid lg:grid-cols-2 gap-6">
        <!-- Input Section -->
        <div class="bg-white p-6 rounded-lg shadow-sm border">
          <div class="flex items-center justify-between mb-4">
            <h3 class="text-lg font-semibold text-gray-900">
              {{ $t('tools.excelToJson.inputTitle') }}
            </h3>
            <button
              @click="clearInput"
              class="px-3 py-1 text-sm bg-gray-100 text-gray-700 rounded hover:bg-gray-200 transition-colors"
            >
              {{ $t('common.clear') }}
            </button>
          </div>

          <!-- File Upload -->
          <div class="border-2 border-dashed border-gray-300 rounded-lg p-8 text-center mb-4">
            <input
              ref="fileInput"
              type="file"
              accept=".xlsx,.xls,.csv,.ods"
              @change="handleFileSelect"
              class="hidden"
            />
            <div class="text-4xl text-gray-400 mb-4">📁</div>
            <p class="text-gray-600 mb-2">{{ $t('tools.excelToJson.uploadDescription') }}</p>
            <button
              @click="($refs.fileInput as HTMLInputElement)?.click()"
              class="px-4 py-2 bg-blue-600 text-white rounded-lg hover:bg-blue-700 transition-colors"
            >
              {{ $t('tools.excelToJson.selectFile') }}
            </button>
            <p class="text-sm text-gray-500 mt-2">{{ $t('tools.excelToJson.supportedFormats') }}</p>
          </div>

          <!-- Options -->
          <div class="space-y-3">
            <h4 class="font-medium text-gray-900">{{ $t('tools.excelToJson.options.title') }}</h4>

            <div class="grid grid-cols-2 gap-4">
              <label class="flex items-center">
                <input
                  v-model="options.firstRowAsHeaders"
                  type="checkbox"
                  class="mr-2 rounded border-gray-300 text-blue-600 focus:ring-blue-500"
                />
                {{ $t('tools.excelToJson.options.firstRowAsHeaders') }}
              </label>

              <label class="flex items-center">
                <input
                  v-model="options.skipEmptyRows"
                  type="checkbox"
                  class="mr-2 rounded border-gray-300 text-blue-600 focus:ring-blue-500"
                />
                {{ $t('tools.excelToJson.options.skipEmptyRows') }}
              </label>
            </div>

            <div class="flex items-center space-x-4">
              <label class="text-sm font-medium text-gray-700">
                {{ $t('tools.excelToJson.options.sheetIndex') }}:
              </label>
              <select
                v-model="options.sheetIndex"
                class="px-3 py-1 border border-gray-300 rounded text-sm focus:ring-2 focus:ring-blue-500 focus:border-transparent"
              >
                <option v-for="(sheet, index) in availableSheets" :key="index" :value="index">
                  {{ sheet.name || `Sheet ${index + 1}` }}
                </option>
              </select>
            </div>
          </div>

          <button
            @click="convertToJson"
            :disabled="!selectedFile || isLoading"
            class="w-full mt-4 px-4 py-2 bg-blue-600 text-white rounded-lg hover:bg-blue-700 disabled:bg-gray-300 disabled:cursor-not-allowed transition-colors font-medium"
          >
            <span v-if="isLoading" class="flex items-center justify-center">
              <svg
                class="animate-spin -ml-1 mr-3 h-5 w-5 text-white"
                xmlns="http://www.w3.org/2000/svg"
                fill="none"
                viewBox="0 0 24 24"
              >
                <circle
                  class="opacity-25"
                  cx="12"
                  cy="12"
                  r="10"
                  stroke="currentColor"
                  stroke-width="4"
                ></circle>
                <path
                  class="opacity-75"
                  fill="currentColor"
                  d="M4 12a8 8 0 018-8V0C5.373 0 0 5.373 0 12h4zm2 5.291A7.962 7.962 0 014 12H0c0 3.042 1.135 5.824 3 7.938l3-2.647z"
                ></path>
              </svg>
              {{ $t('common.loading') }}
            </span>
            <span v-else>
              {{ $t('tools.excelToJson.convert') }}
            </span>
          </button>
        </div>

        <!-- Output Section -->
        <div class="bg-white p-6 rounded-lg shadow-sm border">
          <div class="flex items-center justify-between mb-4">
            <h3 class="text-lg font-semibold text-gray-900">
              {{ $t('tools.excelToJson.outputTitle') }}
            </h3>
            <div class="flex space-x-2">
              <button
                v-if="outputJson"
                @click="copyToClipboard"
                class="px-3 py-1 text-sm bg-blue-100 text-blue-700 rounded hover:bg-blue-200 transition-colors"
              >
                {{ $t('common.copy') }}
              </button>
              <button
                v-if="outputJson"
                @click="downloadJson"
                class="px-3 py-1 text-sm bg-green-100 text-green-700 rounded hover:bg-green-200 transition-colors"
              >
                {{ $t('common.download') }}
              </button>
            </div>
          </div>

          <div
            v-if="!outputJson && !error"
            class="h-80 flex items-center justify-center text-gray-500 border-2 border-dashed border-gray-200 rounded-lg"
          >
            <div class="text-center">
              <div class="text-3xl mb-2">📄</div>
              <p>{{ $t('tools.excelToJson.noResults') }}</p>
            </div>
          </div>

          <div v-if="error" class="h-80 flex items-center justify-center">
            <div class="text-center text-red-600">
              <div class="text-3xl mb-2">❌</div>
              <p class="font-medium">{{ $t('toast.error') }}</p>
              <p class="text-sm">{{ error }}</p>
            </div>
          </div>

          <div v-if="outputJson && !error" class="space-y-4">
            <div class="bg-green-50 border border-green-200 rounded-lg p-4">
              <div class="flex items-center">
                <div class="text-green-600 text-2xl mr-3">✅</div>
                <div>
                  <p class="font-medium text-green-800">
                    {{ $t('tools.excelToJson.conversionComplete') }}
                  </p>
                  <p class="text-sm text-green-600">
                    {{
                      $t('tools.excelToJson.recordsCount', { count: JSON.parse(outputJson).length })
                    }}
                  </p>
                </div>
              </div>
            </div>

            <textarea
              :value="outputJson"
              readonly
              class="w-full h-64 p-4 border border-gray-300 rounded-lg font-mono text-sm resize-none bg-gray-50 focus:ring-2 focus:ring-blue-500 focus:border-transparent"
            ></textarea>
          </div>
        </div>
      </div>
    </div>
  </div>
</template>

<script setup lang="ts">
import { ref, reactive } from 'vue'
import { useI18n } from 'vue-i18n'
import { useToast } from '@/composables/useToast'
import * as XLSX from 'xlsx'

const { t } = useI18n()
const { success, error: showError, copySuccess, copyError, downloadSuccess } = useToast()

const selectedFile = ref<File | null>(null)
const outputJson = ref('')
const error = ref('')
const isLoading = ref(false)
const availableSheets = ref<Array<{ name: string }>>([])

const options = reactive({
  firstRowAsHeaders: true,
  skipEmptyRows: true,
  sheetIndex: 0,
})

async function handleFileSelect(event: Event) {
  const target = event.target as HTMLInputElement
  if (target.files && target.files.length > 0) {
    const file = target.files[0]

    // Validate file type
    const validExtensions = ['.xlsx', '.xls', '.csv', '.ods']
    const fileName = file.name.toLowerCase()
    const isValidFile = validExtensions.some((ext) => fileName.endsWith(ext))

    if (!isValidFile) {
      error.value = 'Please select a valid Excel file (.xlsx, .xls, .csv, .ods)'
      showError(error.value)
      return
    }

    // Validate file size (max 50MB)
    const maxSize = 50 * 1024 * 1024 // 50MB
    if (file.size > maxSize) {
      error.value = 'File size must be less than 50MB'
      showError(error.value)
      return
    }

    selectedFile.value = file
    error.value = ''
    outputJson.value = ''

    try {
      // Read the file to get sheet information
      const arrayBuffer = await file.arrayBuffer()
      const workbook = XLSX.read(arrayBuffer, { type: 'array' })

      // Update available sheets
      availableSheets.value = workbook.SheetNames.map((name) => ({ name }))
      options.sheetIndex = 0

      success(t('tools.excelToJson.fileSelected'))
    } catch (err: unknown) {
      const errorMessage =
        err instanceof Error ? err.message : t('tools.excelToJson.errors.conversionFailed')
      error.value = errorMessage
      showError(error.value)
      selectedFile.value = null
      availableSheets.value = []
    }
  }
}

function clearInput() {
  selectedFile.value = null
  outputJson.value = ''
  error.value = ''
  isLoading.value = false
  availableSheets.value = []
  options.sheetIndex = 0
}

async function convertToJson() {
  if (isLoading.value) return

  isLoading.value = true

  try {
    error.value = ''
    outputJson.value = ''

    if (!selectedFile.value) {
      throw new Error(t('tools.excelToJson.errors.noFileSelected'))
    }

    // Check if we have any sheets available
    if (availableSheets.value.length === 0) {
      throw new Error('No sheets found in the Excel file')
    }

    // Read the Excel file
    const arrayBuffer = await selectedFile.value.arrayBuffer()
    const workbook = XLSX.read(arrayBuffer, { type: 'array' })

    // Get the selected sheet
    const sheetName = workbook.SheetNames[options.sheetIndex]
    if (!sheetName) {
      throw new Error('Selected sheet not found')
    }

    const worksheet = workbook.Sheets[sheetName]

    // Check if worksheet is empty
    if (!worksheet || Object.keys(worksheet).length === 0) {
      throw new Error('Selected sheet is empty')
    }

    // Convert sheet to JSON with options
    const jsonData = XLSX.utils.sheet_to_json(worksheet, {
      header: options.firstRowAsHeaders ? 1 : 'A',
      defval: '',
      blankrows: !options.skipEmptyRows,
      raw: false,
    })

    // Check if we got any data
    if (!Array.isArray(jsonData) || jsonData.length === 0) {
      throw new Error('No data found in the selected sheet')
    }

    // Format the JSON output
    outputJson.value = JSON.stringify(jsonData, null, 2)

    success(t('tools.excelToJson.conversionComplete'))
  } catch (err: unknown) {
    const errorMessage =
      err instanceof Error ? err.message : t('tools.excelToJson.errors.conversionFailed')
    error.value = errorMessage
    showError(error.value)
  } finally {
    isLoading.value = false
  }
}

function copyToClipboard() {
  if (!outputJson.value) return

  navigator.clipboard
    .writeText(outputJson.value)
    .then(() => {
      copySuccess()
    })
    .catch(() => {
      copyError()
    })
}

function downloadJson() {
  if (!outputJson.value) return

  const blob = new Blob([outputJson.value], { type: 'application/json' })
  const url = URL.createObjectURL(blob)
  const link = document.createElement('a')
  link.href = url
  link.download = `converted_data_${Date.now()}.json`
  document.body.appendChild(link)
  link.click()
  document.body.removeChild(link)
  URL.revokeObjectURL(url)

  downloadSuccess()
}
</script>

// src/pages/tools/Json/ExcelToJson.tsx
import React, { useState, useEffect, useCallback } from 'react';
import { Card, Input, Button, Select, Checkbox, Typography, Space, Row, Col, Tag, message, Upload, Radio } from 'antd';
import {
    DownloadOutlined,
    CopyOutlined,
    InboxOutlined,
    FileTextOutlined,
    FileExcelOutlined,
    DeleteOutlined
} from '@ant-design/icons';
import { useCopy } from '@/hooks/useCopy';
import * as XLSX from 'xlsx';
import { FormattedMessage, useIntl } from 'react-intl';

const { TextArea } = Input;
const { Title, Text } = Typography;
const { Option } = Select;
const { Dragger } = Upload;

type Mode = 'file' | 'text';
type OutputFormat = 'object' | 'array';

interface FileOptions {
    firstRowAsHeaders: boolean;
    skipEmptyRows: boolean;
    sheetIndex: number;
}

interface TextOptions {
    delimiter: string;
    outputFormat: OutputFormat;
    hasHeaders: boolean;
    skipEmptyLines: boolean;
    autoDetectNumbers: boolean;
    autoDetectBooleans: boolean;
}

const excelToJson: React.FC = () => {
    const intl = useIntl();
    const copy = useCopy();

    // Mode
    const [mode, setMode] = useState<Mode>('file');

    // File Mode State
    const [fileList, setFileList] = useState<any[]>([]);
    const [availableSheets, setAvailableSheets] = useState<string[]>([]);
    const [isLoading, setIsLoading] = useState(false);
    const [fileOutputJson, setFileOutputJson] = useState('');
    const [fileOptions, setFileOptions] = useState<FileOptions>({
        firstRowAsHeaders: true,
        skipEmptyRows: true,
        sheetIndex: 0
    });

    // Text Mode State
    const [inputText, setInputText] = useState('');
    const [textOutputJson, setTextOutputJson] = useState('');
    const [previewRows, setPreviewRows] = useState<string[][]>([]);
    const [headers, setHeaders] = useState<string[]>([]);
    const [textOptions, setTextOptions] = useState<TextOptions>({
        delimiter: '\t',
        outputFormat: 'object',
        hasHeaders: true,
        skipEmptyLines: true,
        autoDetectNumbers: true,
        autoDetectBooleans: true
    });

    // -------------------------------------------------------------------------
    // File Mode Logic
    // -------------------------------------------------------------------------

    const handleFileChange = async (info: any) => {
        const file = info.file;
        // Don't actually upload, just read locally
        setFileList([file]);
        setAvailableSheets([]);
        setFileOutputJson('');

        if (file.status === 'removed') return;

        // Read sheets
        try {
            const arrayBuffer = await file.originFileObj.arrayBuffer();
            const workbook = XLSX.read(arrayBuffer, { type: 'array' });
            setAvailableSheets(workbook.SheetNames);
            setFileOptions(prev => ({ ...prev, sheetIndex: 0 }));
            message.success(`Loaded ${file.name}`);
        } catch (err) {
            message.error('Failed to read file');
        }
    };

    const convertFileToJson = async () => {
        if (!fileList.length) return;
        setIsLoading(true);
        try {
            const file = fileList[0].originFileObj;
            const arrayBuffer = await file.arrayBuffer();
            const workbook = XLSX.read(arrayBuffer, { type: 'array' });

            const sheetName = workbook.SheetNames[fileOptions.sheetIndex];
            if (!sheetName) throw new Error('Sheet not found');

            const worksheet = workbook.Sheets[sheetName];

            const jsonData = XLSX.utils.sheet_to_json(worksheet, {
                header: fileOptions.firstRowAsHeaders ? undefined : 1, // 1 means array of arrays
                defval: "",
                blankrows: !fileOptions.skipEmptyRows,
                raw: false
            });

            setFileOutputJson(JSON.stringify(jsonData, null, 2));
            message.success(intl.formatMessage({ id: 'toast.success' }));

        } catch (err: any) {
            message.error(err.message || 'Conversion failed');
        } finally {
            setIsLoading(false);
        }
    };

    // -------------------------------------------------------------------------
    // Text Mode Logic
    // -------------------------------------------------------------------------

    const parseLine = useCallback((line: string): string[] => {
        const result: string[] = [];
        let current = '';
        let inQuotes = false;
        let i = 0;

        while (i < line.length) {
            const char = line[i];
            const nextChar = line[i + 1];

            if ((char === '"' || char === "'") && !inQuotes) {
                inQuotes = true;
                i++;
            } else if ((char === '"' || char === "'") && inQuotes) {
                if (nextChar === char) {
                    current += char;
                    i += 2;
                } else {
                    inQuotes = false;
                    i++;
                }
            } else if (char === textOptions.delimiter && !inQuotes) {
                result.push(current.trim());
                current = '';
                i++;
            } else {
                current += char;
                i++;
            }
        }
        result.push(current.trim());
        return result;
    }, [textOptions.delimiter]);

    const updatePreview = useCallback(() => {
        if (!inputText.trim()) {
            setPreviewRows([]);
            setHeaders([]);
            return;
        }

        const lines = inputText.split('\n')
            .map(l => l.trim())
            .filter(l => textOptions.skipEmptyLines ? l : true);

        if (lines.length === 0) return;

        const parsedLines = lines.map(parseLine);

        if (textOptions.hasHeaders && parsedLines.length > 0) {
            setHeaders(parsedLines[0]);
            setPreviewRows(parsedLines.slice(1));
        } else {
            const maxCols = Math.max(...parsedLines.map(r => r.length));
            setHeaders(Array.from({ length: maxCols }, (_, i) => `Column${i + 1}`));
            setPreviewRows(parsedLines);
        }
    }, [inputText, textOptions.skipEmptyLines, textOptions.hasHeaders, parseLine]);

    useEffect(() => {
        updatePreview();
    }, [updatePreview]);

    const convertValue = (value: string): string | number | boolean => {
        if (value === '') return '';
        if (textOptions.autoDetectBooleans) {
            if (value.toLowerCase() === 'true') return true;
            if (value.toLowerCase() === 'false') return false;
        }
        if (textOptions.autoDetectNumbers) {
            const num = Number(value);
            if (!isNaN(num) && value.trim() !== '') return num;
        }
        return value;
    };

    const convertTextToJson = () => {
        if (!inputText.trim() || previewRows.length === 0) return;

        let result: any;

        if (textOptions.outputFormat === 'object' && textOptions.hasHeaders) {
            result = previewRows.map(row => {
                const obj: Record<string, any> = {};
                headers.forEach((h, i) => {
                    obj[h] = convertValue(row[i] || '');
                });
                return obj;
            });
        } else {
            // Array format
            const dataRows = previewRows.map(row => row.map(convertValue));
            if (textOptions.hasHeaders) {
                result = [headers, ...dataRows];
            } else {
                result = dataRows;
            }
        }

        setTextOutputJson(JSON.stringify(result, null, 2));
    };

    // -------------------------------------------------------------------------
    // Actions
    // -------------------------------------------------------------------------

    const handleDownload = (content: string) => {
        if (!content) return;
        const blob = new Blob([content], { type: 'application/json' });
        const url = URL.createObjectURL(blob);
        const link = document.createElement('a');
        link.href = url;
        link.download = `converted_${Date.now()}.json`;
        document.body.appendChild(link);
        link.click();
        document.body.removeChild(link);
        URL.revokeObjectURL(url);
    };

    const handleExampleText = () => {
        setInputText("name\tage\tscore\nJohn\t25\t89\nAlice\t22\t95\nBob\t30\t78");
        setTextOptions(prev => ({ ...prev, delimiter: '\t' })); // Set tab delimiter for example
    };

    // -------------------------------------------------------------------------
    // Render
    // -------------------------------------------------------------------------

    return (
        <div className="max-w-7xl mx-auto px-4">
            {/* Header */}
            <div className="text-center mb-2">
                <Title level={1} className="text-white mb-2">
                    <FormattedMessage id="tools.excelToJson.name" />
                </Title>
                <Text className="text-slate-400 text-lg">
                    <FormattedMessage id="tools.excelToJson.description" />
                </Text>
            </div>
            {/* Mode Switcher */}
            <div className="flex justify-center mb-6">
                <Radio.Group
                    value={mode}
                    onChange={e => setMode(e.target.value)}
                    optionType="button"
                    buttonStyle="solid"
                >
                    <Radio.Button value="file"><FileExcelOutlined /> <FormattedMessage id="tools.excelToJson.mode.file" /></Radio.Button>
                    <Radio.Button value="text"><FileTextOutlined /> <FormattedMessage id="tools.excelToJson.mode.text" /></Radio.Button>
                </Radio.Group>
            </div>

            <Row gutter={[24, 24]}>
                {/* ----------------- LEFT: INPUT ----------------- */}
                <Col xs={24} lg={12}>
                    <Card
                        className="border-none bg-white/5 h-full"
                        title={<FormattedMessage id="tools.excelToJson.inputTitle" />}
                        extra={
                            mode === 'text' && (
                                <Space>
                                    <Button size="small" onClick={handleExampleText} className="border-none hover:text-white"><FormattedMessage id="common.loadExample" /></Button>
                                    <Button size="small" onClick={() => { setInputText(''); setTextOutputJson(''); }} icon={<DeleteOutlined />} className="border-none hover:text-white"><FormattedMessage id="common.clear" /></Button>
                                </Space>
                            )
                        }
                    >
                        {mode === 'file' ? (
                            <div className="space-y-4">
                                <Dragger
                                    fileList={fileList}
                                    beforeUpload={() => false} // Prevent auto upload
                                    onChange={handleFileChange}
                                    maxCount={1}
                                    accept=".xlsx,.xls,.csv,.ods"
                                    className="border-slate-700 hover:border-primary-500"
                                >
                                    <p className="ant-upload-drag-icon">
                                        <InboxOutlined className="text-primary-500" />
                                    </p>
                                    <p className="ant-upload-text"><FormattedMessage id="tools.excelToJson.uploadText" /></p>
                                    <p className="ant-upload-hint text-slate-500">
                                        <FormattedMessage id="tools.excelToJson.uploadHint" />
                                    </p>
                                </Dragger>

                                {availableSheets.length > 0 && (
                                    <div className="p-4 rounded-lg border border-slate-700/30 space-y-4">
                                        <div className="flex items-center gap-4">
                                            <Text className="text-slate-300"><FormattedMessage id="tools.excelToJson.sheet" />:</Text>
                                            <Select
                                                value={fileOptions.sheetIndex}
                                                onChange={v => setFileOptions({ ...fileOptions, sheetIndex: v })}
                                                className="w-full"
                                            >
                                                {availableSheets.map((s, i) => <Option key={s} value={i}>{s}</Option>)}
                                            </Select>
                                        </div>
                                        <Checkbox checked={fileOptions.firstRowAsHeaders} onChange={e => setFileOptions({ ...fileOptions, firstRowAsHeaders: e.target.checked })} className="text-slate-300"><FormattedMessage id="tools.excelToJson.firstRowHeaders" /></Checkbox>
                                        <Checkbox checked={fileOptions.skipEmptyRows} onChange={e => setFileOptions({ ...fileOptions, skipEmptyRows: e.target.checked })} className="text-slate-300"><FormattedMessage id="tools.excelToJson.skipEmptyRows" /></Checkbox>

                                        <Button type="primary" block onClick={convertFileToJson} loading={isLoading} disabled={!fileList.length}>
                                            <FormattedMessage id="tools.excelToJson.convertAction" />
                                        </Button>
                                    </div>
                                )}
                            </div>
                        ) : (
                            // Text Mode Input
                            <div className="space-y-4">
                                <TextArea
                                    value={inputText}
                                    onChange={e => setInputText(e.target.value)}
                                    placeholder={intl.formatMessage({ id: 'tools.excelToJson.textPlaceholder' })}
                                    className="font-mono text-sm border-slate-700/50 text-slate-100 placeholder-slate-500 rounded-lg"
                                    style={{ minHeight: '200px' }}
                                />

                                <div className="p-4 rounded-lg border border-slate-700/30 space-y-4">
                                    <Row gutter={16}>
                                        <Col span={12}>
                                            <Text className="text-slate-400 text-xs mb-1 block"><FormattedMessage id="tools.jsonToExcel.delimiter" /></Text>
                                            <Select value={textOptions.delimiter} onChange={v => setTextOptions({ ...textOptions, delimiter: v })} className="w-full">
                                                <Option value="\t"><FormattedMessage id="tools.jsonFormatter.tab" /></Option>
                                                <Option value=",">Comma (,)</Option>
                                                <Option value=";">Semicolon (;)</Option>
                                                <Option value="|">Pipe (|)</Option>
                                                <Option value=" ">Space</Option>
                                            </Select>
                                        </Col>
                                        <Col span={12}>
                                            <Text className="text-slate-400 text-xs mb-1 block"><FormattedMessage id="tools.excelToJson.outputFormat" /></Text>
                                            <Select value={textOptions.outputFormat} onChange={v => setTextOptions({ ...textOptions, outputFormat: v })} className="w-full">
                                                <Option value="object"><FormattedMessage id="tools.jsonExtractor.outputFormat.array" /> of Objects</Option>
                                                <Option value="array"><FormattedMessage id="tools.jsonExtractor.outputFormat.array" /> of Arrays</Option>
                                            </Select>
                                        </Col>
                                    </Row>

                                    <Row gutter={16}>
                                        <Col span={12}><Checkbox checked={textOptions.hasHeaders} onChange={e => setTextOptions({ ...textOptions, hasHeaders: e.target.checked })} className="text-slate-300"><FormattedMessage id="tools.excelToJson.firstRowHeaders" /></Checkbox></Col>
                                        <Col span={12}><Checkbox checked={textOptions.skipEmptyLines} onChange={e => setTextOptions({ ...textOptions, skipEmptyLines: e.target.checked })} className="text-slate-300"><FormattedMessage id="tools.jsonExtractor.options.removeEmpty" /></Checkbox></Col>
                                        <Col span={12}><Checkbox checked={textOptions.autoDetectNumbers} onChange={e => setTextOptions({ ...textOptions, autoDetectNumbers: e.target.checked })} className="text-slate-300"><FormattedMessage id="tools.excelToJson.detectNumbers" /></Checkbox></Col>
                                        <Col span={12}><Checkbox checked={textOptions.autoDetectBooleans} onChange={e => setTextOptions({ ...textOptions, autoDetectBooleans: e.target.checked })} className="text-slate-300"><FormattedMessage id="tools.excelToJson.detectBooleans" /></Checkbox></Col>
                                    </Row>

                                    <Button type="primary" block onClick={convertTextToJson} disabled={!inputText.trim()}>
                                        <FormattedMessage id="tools.excelToJson.convertAction" />
                                    </Button>
                                </div>
                            </div>
                        )}
                    </Card>
                </Col>

                {/* ----------------- RIGHT: OUTPUT ----------------- */}
                <Col xs={24} lg={12}>
                    <Card
                        className="border-none bg-white/5 h-full"
                        title={<FormattedMessage id="tools.excelToJson.outputTitle" />}
                        extra={
                            <Space>
                                {(fileOutputJson || textOutputJson) && (
                                    <>
                                        <Button size="small" onClick={() => copy(mode === 'file' ? fileOutputJson : textOutputJson)} icon={<CopyOutlined />}><FormattedMessage id="common.copy" /></Button>
                                        <Button size="small" onClick={() => handleDownload(mode === 'file' ? fileOutputJson : textOutputJson)} icon={<DownloadOutlined />} className="text-green-400 border-green-400/30"><FormattedMessage id="common.download" /></Button>
                                    </>
                                )}
                            </Space>
                        }
                    >
                        {/* Wrapper for output content */}
                        {(mode === 'file' && !fileOutputJson) || (mode === 'text' && !textOutputJson) ? (
                            <div className="h-96 flex flex-col items-center justify-center text-slate-500 border-2 border-dashed border-slate-700/30 rounded-xl">
                                <FileTextOutlined className="text-4xl mb-4 opacity-50" />
                                <p><FormattedMessage id="tools.excelToJson.noResults" defaultMessage="JSON output will appear here" /></p>
                            </div>
                        ) : (
                            <div className="animate-fade-in relative">
                                <div className="absolute top-2 right-2 z-10">
                                    <Tag color="green">
                                        <FormattedMessage id="tools.excelToJson.recordsFound" values={{ count: mode === 'file' ? JSON.parse(fileOutputJson).length : JSON.parse(textOutputJson).length }} />
                                    </Tag>
                                </div>
                                <TextArea
                                    value={mode === 'file' ? fileOutputJson : textOutputJson}
                                    readOnly
                                    className="font-mono text-sm border-slate-700 text-green-400 rounded-lg"
                                    style={{ height: 'calc(100vh - 400px)', minHeight: '400px', resize: 'none' }}
                                />
                            </div>
                        )}

                        {/* Text Mode Preview Table - Only show if not converted yet or optionally? 
                            Let's show a small preview if input text exists in text mode.
                        */}
                        {mode === 'text' && inputText && previewRows.length > 0 && !textOutputJson && (
                            <div className="mt-4 border border-slate-700/50 rounded-lg overflow-hidden">
                                <div className="px-3 py-2 border-b border-slate-700/50 text-xs text-slate-400 uppercase tracking-wider">
                                    Input {textOptions.hasHeaders ? 'Headers' : 'Columns'} Detected: {headers.length}
                                </div>
                                <div className="p-2 flex gap-2 flex-wrap">
                                    {headers.map(h => <Tag key={h} className="m-0 border-slate-600">{h}</Tag>)}
                                </div>
                            </div>
                        )}

                    </Card>
                </Col>
            </Row>
        </div>
    );
};

export default excelToJson;
