// src/pages/tools/gif-editor/index.tsx
import { useState, useEffect } from "react";
import {
  Film,
  Download,
  Trash2,
  ChevronUp,
  ChevronDown,
  ArrowLeftRight,
  Shuffle,
  Eraser,
  Loader2,
  TriangleAlert,
  Info,
} from "lucide-react";
// @ts-expect-error No type definitions available for gif.js
import GIF from "gif.js";
import { parseGIF, decompressFrames } from "gifuct-js";



import { Button } from "@/components/ui/button";
import { Input } from "@/components/ui/input";
import { Label } from "@/components/ui/label";
import { UploadDropZone } from "@/components/ui/upload-dropzone";
import {
  Select,
  SelectContent,
  SelectItem,
  SelectTrigger,
  SelectValue,
} from "@/components/ui/select";
import { type SiteDefination } from "@/lib/site";

interface SelectedGif {
  file: File;
  url: string;
  name: string;
  width: number;
  height: number;
}

interface GifFrame {
  dataUrl: string;
  delay: number;
  left: number;
  top: number;
  width: number;
  height: number;
}

const QUALITY_MAP: Record<string, number> = { high: 1, medium: 10, low: 20 };

export default function GifEditorPage({ title, description }: SiteDefination) {
  const [isProcessing, setIsProcessing] = useState(false);
  const [progress, setProgress] = useState(0);
  const [generatedGif, setGeneratedGif] = useState("");
  const [selectedGif, setSelectedGif] = useState<SelectedGif | null>(null);
  const [frames, setFrames] = useState<GifFrame[]>([]);
  const [error, setError] = useState("");
  const [quality, setQuality] = useState("medium");

  useEffect(() => {
    return () => {
      if (selectedGif?.url) URL.revokeObjectURL(selectedGif.url);
      if (generatedGif) URL.revokeObjectURL(generatedGif);
    };
  }, [selectedGif, generatedGif]);

  const getImageDimensions = (file: File): Promise<{ width: number; height: number }> => {
    return new Promise((resolve) => {
      const img = new Image();
      img.onload = () => resolve({ width: img.naturalWidth || 0, height: img.naturalHeight || 0 });
      img.onerror = () => resolve({ width: 0, height: 0 });
      img.src = URL.createObjectURL(file);
    });
  };

  const parseGifFrames = async (file: File, gifWidth: number, gifHeight: number) => {
    try {
      const arrayBuffer = await file.arrayBuffer();
      const gif = parseGIF(arrayBuffer);
      // Try to get dimensions from lsd, fallback to passed-in values
      const w = gif?.lsd?.width || gifWidth || 0;
      const h = gif?.lsd?.height || gifHeight || 0;

      const decompressedFrames = decompressFrames(gif, true);
      const newFrames: GifFrame[] = [];

      for (const frame of decompressedFrames) {
        if (frame.dims.width <= 0 || frame.dims.height <= 0) continue;
        const canvas = document.createElement("canvas");
        canvas.width = w || frame.dims.width;
        canvas.height = h || frame.dims.height;
        const ctx = canvas.getContext("2d", { willReadFrequently: true });
        if (ctx) {
          const imageData = new ImageData(new Uint8ClampedArray(frame.patch), frame.dims.width, frame.dims.height);
          ctx.putImageData(imageData, frame.dims.left || 0, frame.dims.top || 0);
          newFrames.push({
            dataUrl: canvas.toDataURL("image/png"),
            delay: frame.delay,
            left: frame.dims.left || 0,
            top: frame.dims.top || 0,
            width: frame.dims.width,
            height: frame.dims.height,
          });
        }
      }
      setFrames(newFrames);

      const finalW = w || newFrames[0]?.width || 0;
      const finalH = h || newFrames[0]?.height || 0;
      setSelectedGif((prev) => prev ? { ...prev, width: finalW, height: finalH } : prev);
    } catch {
      setError("GIF 帧解析失败");
    }
  };

  const handleGifFile = async (file: File) => {
    setError("");
    if (file.type !== "image/gif") { setError("请上传 GIF 格式文件"); return; }
    if (file.size > 50 * 1024 * 1024) { setError("文件大小不能超过 50MB"); return; }
    clearAll();
    const url = URL.createObjectURL(file);
    // Get dimensions from Image element (more reliable than GIF parsing)
    const { width, height } = await getImageDimensions(file);
    setSelectedGif({ file, url, name: file.name, width, height });
    await parseGifFrames(file, width, height);
  };

  const removeFrame = (index: number) => setFrames((prev) => prev.filter((_, i) => i !== index));

  const clearAll = () => {
    if (selectedGif?.url) URL.revokeObjectURL(selectedGif.url);
    if (generatedGif) URL.revokeObjectURL(generatedGif);
    setSelectedGif(null);
    setFrames([]);
    setGeneratedGif("");
    setProgress(0);
    setError("");
  };

  const updateFrameDelay = (index: number, delay: number) => {
    if (!isNaN(delay) && delay >= 20) {
      setFrames((prev) => prev.map((f, i) => i === index ? { ...f, delay } : f));
    }
  };

  const moveFrameUp = () => {
    if (frames.length <= 1) return;
    const arr = [...frames]; const first = arr.shift();
    if (first) { arr.push(first); setFrames(arr); }
  };

  const moveFrameDown = () => {
    if (frames.length <= 1) return;
    const arr = [...frames]; const last = arr.pop();
    if (last) { arr.unshift(last); setFrames(arr); }
  };

  const reverseFrames = () => frames.length > 1 && setFrames((prev) => [...prev].reverse());

  const shuffleFrames = () => {
    if (frames.length <= 1) return;
    const shuffled = [...frames];
    for (let i = shuffled.length - 1; i > 0; i--) {
      const j = Math.floor(Math.random() * (i + 1));
      [shuffled[i], shuffled[j]] = [shuffled[j], shuffled[i]];
    }
    setFrames(shuffled);
  };

  const generateGif = async () => {
    if (!selectedGif || frames.length === 0) { setError("没有可用的帧"); return; }
    if (!selectedGif.width || !selectedGif.height) { setError("GIF 尺寸无效"); return; }
    setIsProcessing(true);
    setProgress(0);
    setError("");

    try {
      await new Promise<void>((resolve, reject) => {
        const canvas = document.createElement("canvas");
        const ctx = canvas.getContext("2d", { willReadFrequently: true });
        if (!ctx) { reject(new Error("无法获取 Canvas 上下文")); return; }
        canvas.width = selectedGif.width;
        canvas.height = selectedGif.height;

        const gif = new GIF({
          workers: 2, quality: QUALITY_MAP[quality],
          width: selectedGif.width, height: selectedGif.height,
          workerScript: "/gif.worker.js", transparent: 0x00000000,
        });

        const total = frames.length;
        let processed = 0;

        const processNext = (index: number) => {
          if (index >= frames.length) {
            if (processed === 0) { reject(new Error("没有可处理的帧")); return; }
            gif.on("finished", (blob: Blob) => {
              setGeneratedGif(URL.createObjectURL(blob));
              setProgress(100);
              resolve();
            });
            gif.on("abort", () => reject(new Error("已取消")));
            gif.on("error", (e: Error) => reject(new Error("生成错误: " + e.message)));
            try { gif.render(); } catch (e) { reject(new Error("渲染失败: " + (e as Error).message)); }
            return;
          }
          const img = new Image();
          img.onload = () => {
            try {
              if (img.width > 0 && img.height > 0) {
                ctx.drawImage(img, 0, 0);
                gif.addFrame(canvas, { copy: true, delay: frames[index].delay });
                processed++;
                setProgress(Math.round((processed / total) * 100));
              }
            } catch { /* skip */ }
            processNext(index + 1);
          };
          img.onerror = () => processNext(index + 1);
          img.src = frames[index].dataUrl;
        };
        processNext(0);
      });
    } catch (e) {
      setError((e as Error).message || "生成失败");
    } finally {
      setIsProcessing(false);
    }
  };

  const downloadGif = () => {
    if (!generatedGif) return;
    const a = document.createElement("a");
    a.href = generatedGif; a.download = `edited-gif-${Date.now()}.gif`;
    document.body.appendChild(a); a.click(); document.body.removeChild(a);
  };

  return (
    <>
            <div>
        <div className="max-w-6xl mx-auto px-4 py-6 space-y-4">
          <div className="flex items-center gap-3">
            <div className="w-10 h-10 rounded-lg bg-primary flex items-center justify-center text-white">
              <Film className="size-5" />
            </div>
            <div>
              <h1 className="text-xl font-bold text-gray-900">{title}</h1>
              <p className="text-sm text-gray-500">{description}</p>
            </div>
          </div>

          {/* Upload */}
          <div className="rounded-xl border border-gray-200 bg-white p-5 space-y-4">
            <UploadDropZone
              accept="image/gif"
              maxSize={50 * 1024 * 1024}
              onError={setError}
              onFiles={(files) => files[0] && handleGifFile(files[0])}
              className="rounded-lg"
              emptyHint="点击或拖拽上传 GIF 文件"
              emptySubHint="最大 50MB"
            />

            {/* Settings */}
            <div className="flex items-center gap-4">
              <div className="flex items-center gap-2">
                <Label className="text-xs text-gray-500">质量</Label>
                <Select value={quality} onValueChange={setQuality}>
                  <SelectTrigger className="h-8 w-28"><SelectValue /></SelectTrigger>
                  <SelectContent>
                    <SelectItem value="high">高</SelectItem>
                    <SelectItem value="medium">中</SelectItem>
                    <SelectItem value="low">低</SelectItem>
                  </SelectContent>
                </Select>
              </div>
              {selectedGif && (
                <span className="text-xs text-gray-400">原始尺寸: {selectedGif.width}×{selectedGif.height}</span>
              )}
            </div>
          </div>

          {error && (
            <div className="flex items-center gap-2 rounded-lg border border-red-200 bg-red-50 p-3 text-sm text-red-600">
              <TriangleAlert className="size-4 shrink-0" />{error}
            </div>
          )}

          {/* Preview & Frames */}
          {selectedGif && (
            <div className="grid gap-4 lg:grid-cols-2">
              <div className="rounded-xl border border-gray-200 bg-white p-4">
                <Label className="text-sm font-medium mb-3 block">原始 GIF</Label>
                <div className="flex items-center justify-center h-64 rounded-lg border border-gray-200 bg-gray-50">
                  <img src={selectedGif.url} alt={selectedGif.name} className="max-h-full max-w-full object-contain" />
                </div>
              </div>

              <div className="rounded-xl border border-gray-200 bg-white p-4">
                <div className="flex items-center justify-between mb-3">
                  <Label className="text-sm font-medium">帧列表 ({frames.length})</Label>
                  <div className="flex flex-wrap gap-1">
                    <Button variant="outline" size="sm" onClick={moveFrameUp} disabled={frames.length <= 1}><ChevronUp className="size-3.5" /></Button>
                    <Button variant="outline" size="sm" onClick={moveFrameDown} disabled={frames.length <= 1}><ChevronDown className="size-3.5" /></Button>
                    <Button variant="outline" size="sm" onClick={reverseFrames} disabled={frames.length <= 1}><ArrowLeftRight className="size-3.5" /></Button>
                    <Button variant="outline" size="sm" onClick={shuffleFrames} disabled={frames.length <= 1}><Shuffle className="size-3.5" /></Button>
                  </div>
                </div>

                <div className="space-y-2 max-h-64 overflow-y-auto">
                  {frames.map((frame, index) => (
                    <div key={index} className="flex items-center gap-3 p-2 border border-gray-100 rounded-lg">
                      <div className="w-12 h-12 shrink-0 rounded overflow-hidden border border-gray-200">
                        <img src={frame.dataUrl} alt={`帧 ${index + 1}`} className="w-full h-full object-cover" />
                      </div>
                      <span className="text-xs text-gray-500 w-12">帧 {index + 1}</span>
                      <div className="flex items-center gap-1">
                        <Input type="number" value={frame.delay} onChange={(e) => updateFrameDelay(index, Number(e.target.value))} min={20} max={5000} step={10} className="h-8 w-16 text-xs" />
                        <span className="text-xs text-gray-400">ms</span>
                      </div>
                      <Button variant="ghost" size="sm" onClick={() => removeFrame(index)} className="ml-auto text-red-500 hover:text-red-600"><Trash2 className="size-3.5" /></Button>
                    </div>
                  ))}
                </div>

                <div className="mt-4 flex gap-2">
                  <Button onClick={generateGif} disabled={frames.length === 0 || isProcessing} className="flex-1">
                    {isProcessing ? <><Loader2 className="size-4 animate-spin" /> 生成中... {progress}%</> : <><Film className="size-4" /> 生成 GIF</>}
                  </Button>
                  <Button variant="outline" onClick={clearAll}><Eraser className="size-4" /> 清空</Button>
                </div>
              </div>
            </div>
          )}

          {/* Result */}
          {generatedGif && (
            <div className="rounded-xl border border-gray-200 bg-white p-5">
              <Label className="text-sm font-medium mb-3 block">生成结果</Label>
              <div className="text-center">
                <img src={generatedGif} alt="生成的 GIF" className="max-w-full h-auto mx-auto rounded-lg mb-4" style={{ maxHeight: "400px" }} />
                <div className="flex justify-center gap-2">
                  <Button onClick={downloadGif}><Download className="size-4" /> 下载 GIF</Button>
                  <Button variant="outline" onClick={clearAll}>重新开始</Button>
                </div>
              </div>
            </div>
          )}

          {/* How to use */}
          <div className="rounded-xl border border-gray-200 bg-gray-50 p-5">
            <div className="flex items-center gap-2 mb-3">
              <Info className="size-4 text-gray-400" />
              <Label className="text-sm font-medium">使用说明</Label>
            </div>
            <ol className="list-decimal list-inside space-y-1.5 text-sm text-gray-600">
              <li>上传一个 GIF 文件（支持拖拽和粘贴）</li>
              <li>查看解析出的所有帧，可调整每帧的延迟时间</li>
              <li>使用上移、下移、反转、打乱等操作调整帧顺序</li>
              <li>删除不需要的帧后点击生成 GIF</li>
            </ol>
          </div>
        </div>
      </div>
          </>
  );
}

// src/tools/image/GifEditor.vue
<template>
  <ToolLayout
    :title="$t('tools.gifEditor.title')"
    :description="$t('tools.gifEditor.description')"
    icon="🎞️"
    :features="[
      $t('tools.gifEditor.features.frameEditing.title'),
      $t('tools.gifEditor.features.customization.title'),
      $t('tools.gifEditor.features.animation.title'),
    ]"
  >
    <!-- How to Use Section -->
    <div class="glass rounded-xl border border-slate-700/30 p-6 mb-6">
      <h3 class="text-lg font-semibold text-slate-100 mb-3">
        {{ $t('tools.gifEditor.howToUse.title') }}
      </h3>
      <ol class="list-decimal list-inside space-y-2 text-slate-300 ml-4">
        <li>{{ $t('tools.gifEditor.howToUse.step1') }}</li>
        <li>{{ $t('tools.gifEditor.howToUse.step2') }}</li>
        <li>{{ $t('tools.gifEditor.howToUse.step3') }}</li>
        <li>{{ $t('tools.gifEditor.howToUse.step4') }}</li>
      </ol>
    </div>

    <!-- Upload Section -->
    <div class="glass rounded-xl border border-slate-700/30 p-6 mb-6">
      <h3 class="text-lg font-semibold text-slate-100 mb-4 border-b border-slate-700/30 pb-2">
        {{ $t('tools.gifEditor.upload.title') }}
      </h3>

      <!-- File Upload -->
      <div class="mb-6">
        <div
          @drop="handleFileDrop"
          @dragover.prevent
          @dragenter.prevent
          class="border-2 border-dashed border-slate-600/50 rounded-lg p-8 text-center hover:border-primary-500/50 transition-colors cursor-pointer"
          :class="{ 'border-primary-500/50 bg-primary-500/10': isDragging }"
          @click="fileInput!.click()"
        >
          <div class="text-slate-400 text-4xl mb-4">🎞️</div>
          <p class="text-slate-400 mb-4">
            {{ $t('tools.gifEditor.upload.dragDrop') }}
          </p>
          <input
            type="file"
            ref="fileInput"
            @change="handleFileSelect"
            accept="image/gif"
            class="hidden"
          />
          <button
            class="px-6 py-2 bg-primary-600 text-white rounded-lg hover:bg-primary-700 transition-colors"
          >
            {{ $t('tools.gifEditor.upload.selectFile') }}
          </button>
          <p class="text-xs text-slate-500 mt-2">
            {{ $t('tools.gifEditor.upload.supportedFormats') }}
          </p>
        </div>
      </div>

      <!-- GIF Settings -->
      <div class="grid grid-cols-1 md:grid-cols-3 gap-4 mb-6">
        <div>
          <label class="block text-sm font-medium text-slate-300 mb-2">
            {{ $t('tools.gifEditor.settings.width') }}
          </label>
          <input
            v-model.number="gifSettings.width"
            type="number"
            min="100"
            max="800"
            class="w-full px-3 py-2 bg-slate-800/50 border border-slate-700/50 text-slate-100 rounded-lg focus:ring-2 focus:ring-primary-500 focus:border-transparent transition-all duration-200"
            disabled
          />
          <p class="text-xs text-slate-500 mt-1">
            {{ $t('tools.gifEditor.settings.preserveOriginal') }}
          </p>
        </div>
        <div>
          <label class="block text-sm font-medium text-slate-300 mb-2">
            {{ $t('tools.gifEditor.settings.quality') }}
          </label>
          <select
            v-model="gifSettings.quality"
            class="w-full px-3 py-2 bg-slate-800/50 border border-slate-700/50 text-slate-100 rounded-lg focus:ring-2 focus:ring-primary-500 focus:border-transparent transition-all duration-200"
          >
            <option value="high">
              {{ $t('tools.gifEditor.settings.qualityOptions.high') }}
            </option>
            <option value="medium">
              {{ $t('tools.gifEditor.settings.qualityOptions.medium') }}
            </option>
            <option value="low">
              {{ $t('tools.gifEditor.settings.qualityOptions.low') }}
            </option>
          </select>
        </div>
        <div>
          <label class="block text-sm font-medium text-slate-300 mb-2">
            {{ $t('tools.gifEditor.settings.fps') }}
          </label>
          <input
            v-model.number="gifSettings.fps"
            type="number"
            min="1"
            max="30"
            class="w-full px-3 py-2 bg-slate-800/50 border border-slate-700/50 text-slate-100 rounded-lg focus:ring-2 focus:ring-primary-500 focus:border-transparent transition-all duration-200"
          />
        </div>
      </div>
    </div>

    <!-- GIF Preview Section -->
    <div v-if="selectedGif" class="glass rounded-xl border border-slate-700/30 p-6 mb-6">
      <h3 class="text-lg font-semibold text-slate-100 mb-4 border-b border-slate-700/30 pb-2">
        {{ $t('tools.gifEditor.preview.title') }}
      </h3>

      <div class="grid grid-cols-1 lg:grid-cols-2 gap-6">
        <!-- GIF Preview -->
        <div>
          <h4 class="text-md font-semibold text-slate-200 mb-3">
            {{ $t('tools.gifEditor.preview.originalGif') }}
          </h4>
          <div class="flex items-center justify-center w-full h-64 bg-slate-800/50 rounded-lg">
            <img
              v-if="selectedGif.url"
              :src="selectedGif.url"
              :alt="selectedGif.name"
              class="max-h-full max-w-full object-contain"
            />
            <div v-else class="text-center">
              <div
                class="animate-spin rounded-full h-8 w-8 border-b-2 border-primary-500 mx-auto"
              ></div>
              <p class="mt-2 text-slate-400">{{ $t('tools.gifEditor.loadingGif') }}</p>
            </div>
          </div>
          <div class="mt-2 text-sm text-slate-400">
            {{ $t('tools.gifEditor.preview.dimensions') }}: {{ selectedGif.width }} ×
            {{ selectedGif.height }} {{ $t('tools.gifEditor.preview.pixels') }}
          </div>
        </div>

        <!-- Frame Controls -->
        <div>
          <h4 class="text-md font-semibold text-slate-200 mb-3">
            {{ $t('tools.gifEditor.preview.frames') }} ({{ frames.length }})
          </h4>

          <div class="space-y-3 max-h-96 overflow-y-auto">
            <div
              v-for="(frame, index) in frames"
              :key="index"
              class="flex items-center p-3 border border-slate-700/50 rounded-lg bg-slate-800/30"
            >
              <div class="flex-shrink-0 w-16 h-16 bg-slate-800/50 rounded-md overflow-hidden">
                <img
                  :src="frame.dataUrl"
                  :alt="`Frame ${index + 1}`"
                  class="w-full h-full object-cover"
                />
              </div>
              <div class="ml-3 flex-grow min-w-0">
                <p class="text-sm font-medium text-slate-100">
                  {{ $t('tools.gifEditor.preview.frame') }} {{ index + 1 }}
                </p>
                <p class="text-xs text-slate-400">
                  {{ $t('tools.gifEditor.preview.delay') }}: {{ frame.delay }}ms
                </p>
                <p class="text-xs text-slate-400">
                  Position: ({{ frame.left }}, {{ frame.top }}) {{ frame.width }}×{{ frame.height }}
                </p>
              </div>
              <div class="flex items-center">
                <input
                  v-model.number="frame.delay"
                  type="number"
                  min="20"
                  max="5000"
                  step="10"
                  class="w-16 px-2 py-1 bg-slate-800/50 border border-slate-700/50 text-slate-100 rounded text-xs focus:ring-2 focus:ring-primary-500 focus:border-transparent transition-all duration-200"
                  @input="updateFrameDelay(index, $event)"
                />
                <span class="ml-1 text-xs text-slate-400">ms</span>
                <button @click="removeFrame(index)" class="ml-2 text-red-500 hover:text-red-400">
                  <svg
                    xmlns="http://www.w3.org/2000/svg"
                    class="h-5 w-5"
                    viewBox="0 0 20 20"
                    fill="currentColor"
                  >
                    <path
                      fill-rule="evenodd"
                      d="M9 2a1 1 0 00-.894.553L7.382 4H4a1 1 0 000 2v10a2 2 0 002 2h8a2 2 0 002-2V6a1 1 0 100-2h-3.382l-.724-1.447A1 1 0 0011 2H9zM7 8a1 1 0 012 0v6a1 1 0 11-2 0V8zm5-1a1 1 0 00-1 1v6a1 1 0 102 0V8a1 1 0 00-1-1z"
                      clip-rule="evenodd"
                    />
                  </svg>
                </button>
              </div>
            </div>
          </div>

          <div class="mt-4 flex flex-wrap gap-2">
            <button
              @click="moveFrameUp"
              :disabled="frames.length <= 1"
              class="px-3 py-1 bg-slate-800/50 text-slate-300 rounded text-sm hover:bg-slate-700/50 disabled:opacity-50 border border-slate-700/50 transition-colors"
            >
              {{ $t('tools.gifEditor.preview.moveUp') }}
            </button>
            <button
              @click="moveFrameDown"
              :disabled="frames.length <= 1"
              class="px-3 py-1 bg-slate-800/50 text-slate-300 rounded text-sm hover:bg-slate-700/50 disabled:opacity-50 border border-slate-700/50 transition-colors"
            >
              {{ $t('tools.gifEditor.preview.moveDown') }}
            </button>
            <button
              @click="reverseFrames"
              :disabled="frames.length <= 1"
              class="px-3 py-1 bg-slate-800/50 text-slate-300 rounded text-sm hover:bg-slate-700/50 disabled:opacity-50 border border-slate-700/50 transition-colors"
            >
              {{ $t('tools.gifEditor.preview.reverse') }}
            </button>
            <button
              @click="shuffleFrames"
              :disabled="frames.length <= 1"
              class="px-3 py-1 bg-slate-800/50 text-slate-300 rounded text-sm hover:bg-slate-700/50 disabled:opacity-50 border border-slate-700/50 transition-colors"
            >
              {{ $t('tools.gifEditor.preview.shuffle') }}
            </button>
          </div>
        </div>
      </div>

      <!-- Action Buttons -->
      <div class="mt-6 flex flex-wrap gap-3">
        <button
          @click="generateGif"
          :disabled="isProcessing || frames.length === 0"
          class="px-4 py-2 bg-primary-600 text-white rounded-lg hover:bg-primary-700 disabled:bg-slate-700 disabled:cursor-not-allowed transition-colors font-medium"
        >
          {{ isProcessing ? $t('common.loading') : $t('tools.gifEditor.actions.generateGif') }}
        </button>
        <button
          @click="clearAll"
          class="px-4 py-2 bg-red-600/10 text-red-300 rounded-lg hover:bg-red-600/20 border border-red-600/30 hover:border-red-600/50 transition-colors font-medium"
        >
          {{ $t('common.clear') }}
        </button>
      </div>
    </div>

    <!-- Processing Status -->
    <div v-if="isProcessing" class="glass rounded-xl border border-slate-700/30 p-6 mb-6">
      <div class="text-center">
        <div
          class="animate-spin rounded-full h-12 w-12 border-b-2 border-primary-500 mx-auto mb-4"
        ></div>
        <h3 class="text-lg font-semibold text-slate-100 mb-2">
          {{ $t('tools.gifEditor.processing.title') }}
        </h3>
        <p class="text-slate-400">
          {{ $t('tools.gifEditor.processing.description') }}
        </p>
        <div class="mt-4 bg-slate-700 rounded-full h-2">
          <div
            class="bg-primary-500 h-2 rounded-full transition-all duration-300"
            :style="{ width: processingProgress + '%' }"
          ></div>
        </div>
        <p class="text-sm text-slate-400 mt-2">{{ processingProgress }}%</p>

        <!-- Preview of generated GIF -->
        <div v-if="generatedGif" class="mt-6">
          <h4 class="text-md font-medium text-slate-200 mb-2">
            {{ $t('tools.gifEditor.processing.preview') }}
          </h4>
          <img
            :src="generatedGif"
            alt="GIF Preview"
            class="max-w-full h-auto mx-auto rounded-lg shadow-lg"
            style="max-height: 200px"
          />
        </div>
      </div>
    </div>

    <!-- Result Section -->
    <div v-if="generatedGif" class="glass rounded-xl border border-slate-700/30 p-6 mb-6">
      <h3 class="text-lg font-semibold text-slate-100 mb-4 border-b border-slate-700/30 pb-2">
        {{ $t('tools.gifEditor.result.title') }}
      </h3>

      <div class="text-center">
        <img
          :src="generatedGif"
          alt="Generated GIF"
          class="max-w-full h-auto mx-auto rounded-lg shadow-lg mb-4"
        />

        <div class="flex justify-center gap-4 flex-wrap">
          <button
            @click="downloadGif"
            class="px-6 py-2 bg-green-600/10 text-green-300 rounded-lg hover:bg-green-600/20 border border-green-600/30 hover:border-green-600/50 transition-colors font-medium"
          >
            {{ $t('tools.gifEditor.result.download') }}
          </button>
          <button
            @click="resetTool"
            class="px-6 py-2 bg-slate-800/50 text-slate-300 rounded-lg hover:bg-slate-700/50 border border-slate-700/50 transition-colors font-medium"
          >
            {{ $t('tools.gifEditor.result.createNew') }}
          </button>
        </div>
      </div>
    </div>

    <!-- Tips Section -->
    <div class="glass rounded-xl border border-slate-700/30 p-6 mb-6">
      <h3 class="text-lg font-semibold text-slate-100 mb-3">
        💡 {{ $t('tools.gifEditor.tips.title') }}
      </h3>
      <ul class="space-y-2 text-slate-300">
        <li class="flex items-start">
          <span class="mr-2">•</span>
          <span>{{ $t('tools.gifEditor.tips.tip1') }}</span>
        </li>
        <li class="flex items-start">
          <span class="mr-2">•</span>
          <span>{{ $t('tools.gifEditor.tips.tip2') }}</span>
        </li>
        <li class="flex items-start">
          <span class="mr-2">•</span>
          <span>{{ $t('tools.gifEditor.tips.tip3') }}</span>
        </li>
        <li class="flex items-start">
          <span class="mr-2">•</span>
          <span>{{ $t('tools.gifEditor.tips.tip4') }}</span>
        </li>
      </ul>
    </div>
  </ToolLayout>
</template>

<script setup lang="ts">
import { useToast } from '@/composables/useToast'
import { onMounted, onUnmounted, reactive, ref } from 'vue'
import { useI18n } from 'vue-i18n'
import ToolLayout from '@/components/ToolLayout.vue'
// @ts-expect-error No type definitions available for gif.js
import GIF from 'gif.js'
import { parseGIF, decompressFrames } from 'gifuct-js'

interface GifSettings {
  width: number
  quality: 'high' | 'medium' | 'low'
  fps: number
}

interface SelectedGif {
  file: File
  url: string
  name: string
  width: number
  height: number
}

interface GifFrame {
  dataUrl: string
  delay: number
  imageData: ImageData
  // Add frame metadata for proper reconstruction
  left: number
  top: number
  width: number
  height: number
  dispose: number
}

// Type definitions for gifuct-js
interface FrameDims {
  width: number
  height: number
}

interface Frame {
  dims: FrameDims
  delay: number
  dispose: number
  transparentIndex: number
  patch: Uint8ClampedArray
  palette: number[][]
}

// Type guard function to check if an object is a Frame
function isFrame(obj: unknown): obj is Frame {
  return obj != null && typeof obj === 'object' && 'dims' in obj && 'delay' in obj
}

const { t } = useI18n()
const { success, error: showError } = useToast()

// Use showError when displaying error messages
function showErrorToast(message: string) {
  showError(message)
}

// Clipboard paste support
onMounted(() => {
  document.addEventListener('paste', handlePaste)
})

onUnmounted(() => {
  document.removeEventListener('paste', handlePaste)
  // Clean up object URLs
  if (selectedGif.value?.url) {
    URL.revokeObjectURL(selectedGif.value.url)
  }
  if (generatedGif.value) {
    URL.revokeObjectURL(generatedGif.value)
  }
})

async function handlePaste(event: ClipboardEvent) {
  const items = event.clipboardData?.items
  if (!items) return

  for (let i = 0; i < items.length; i++) {
    const item = items[i]
    if (item.type === 'image/gif') {
      const blob = item.getAsFile()
      if (blob) {
        // Create a File object from the blob
        const file = new File([blob], `pasted-gif-${Date.now()}.gif`, {
          type: blob.type,
        })
        await handleGifFile(file)
        success(t('tools.gifEditor.messages.filePasted'))
        break
      }
    }
  }
}

// Reactive data
const fileInput = ref<HTMLInputElement>()
const isDragging = ref(false)
const isProcessing = ref(false)
const processingProgress = ref(0)
const generatedGif = ref('')
const selectedGif = ref<SelectedGif | null>(null)
const frames = ref<GifFrame[]>([])

const gifSettings = reactive<GifSettings>({
  width: 300,
  quality: 'medium',
  fps: 10,
})

// File handling
function handleFileDrop(event: DragEvent) {
  event.preventDefault()
  isDragging.value = false

  const files = event.dataTransfer?.files
  if (files && files.length > 0) {
    const gifFiles = Array.from(files).filter((file) => file.type === 'image/gif')
    if (gifFiles.length > 0) {
      handleGifFile(gifFiles[0])
    } else {
      showErrorToast(t('tools.gifEditor.errors.noGif'))
    }
  }
}

function handleFileSelect(event: Event) {
  const target = event.target as HTMLInputElement
  const files = target.files
  if (files && files.length > 0) {
    const gifFiles = Array.from(files).filter((file) => file.type === 'image/gif')
    if (gifFiles.length > 0) {
      handleGifFile(gifFiles[0])
    } else {
      showErrorToast(t('tools.gifEditor.errors.noGif'))
    }
  }

  // Reset input to allow selecting the same file again
  if (target) {
    target.value = ''
  }
}

async function handleGifFile(file: File) {
  if (file.type !== 'image/gif') {
    showErrorToast(t('tools.gifEditor.errors.invalidFile'))
    return
  }

  if (file.size > 50 * 1024 * 1024) {
    // 50MB limit
    showErrorToast(t('tools.gifEditor.errors.fileTooLarge'))
    return
  }

  try {
    // Clear previous data
    clearAll()

    // Set selected GIF
    const url = URL.createObjectURL(file)
    selectedGif.value = {
      file,
      url,
      name: file.name,
      width: 0,
      height: 0,
    }

    // Parse GIF frames
    await parseGifFrames(file)

    success(t('tools.gifEditor.messages.fileLoaded'))
  } catch (err) {
    console.error('Error handling GIF file:', err)
    showErrorToast(t('tools.gifEditor.errors.fileProcessing'))
  }
}

async function parseGifFrames(file: File) {
  try {
    const arrayBuffer = await file.arrayBuffer()
    const gif = parseGIF(arrayBuffer)

    // Get dimensions from the GIF header
    if (gif && gif.lsd) {
      if (selectedGif.value) {
        selectedGif.value.width = gif.lsd.width
        selectedGif.value.height = gif.lsd.height
      }
    }

    // Decompress frames with buildPatch = true to get full RGBA frame data
    const decompressedFrames = decompressFrames(gif, true)

    // Convert frames to data URLs
    frames.value = []
    for (const frame of decompressedFrames) {
      // Validate frame dimensions
      if (frame.dims.width <= 0 || frame.dims.height <= 0) {
        console.warn('Skipping frame with invalid dimensions')
        continue
      }

      // Create a full canvas for this frame to preserve positioning
      const canvas = document.createElement('canvas')
      canvas.width = selectedGif.value?.width || frame.dims.width
      canvas.height = selectedGif.value?.height || frame.dims.height

      const ctx = canvas.getContext('2d', { willReadFrequently: true })
      if (ctx) {
        // Clear canvas with transparent background
        // ctx.clearRect(0, 0, canvas.width, canvas.height)

        // Create ImageData directly from the patch (which is full RGBA data when buildPatch=true)
        const imageData = new ImageData(
          new Uint8ClampedArray(frame.patch),
          frame.dims.width,
          frame.dims.height,
        )

        // Draw the frame at its correct position
        ctx.putImageData(imageData, frame.dims.left || 0, frame.dims.top || 0)

        // Convert to data URL with transparency preserved
        const dataUrl = canvas.toDataURL('image/png')

        frames.value.push({
          dataUrl,
          delay: frame.delay,
          imageData,
          left: frame.dims.left || 0,
          top: frame.dims.top || 0,
          width: frame.dims.width,
          height: frame.dims.height,
          dispose: frame.disposalType || 0,
        })
      }
    }

    // If we still don't have GIF dimensions but have frames, set from first frame
    if (
      selectedGif.value &&
      (!selectedGif.value.width || !selectedGif.value.height) &&
      frames.value.length > 0
    ) {
      selectedGif.value.width = frames.value[0].imageData.width
      selectedGif.value.height = frames.value[0].imageData.height
    }
  } catch (err) {
    console.error('Error parsing GIF frames:', err)
    showErrorToast(t('tools.gifEditor.errors.frameParsingFailed'))
  }
}

function removeFrame(index: number) {
  frames.value.splice(index, 1)
}

function clearAll() {
  // Revoke object URLs
  if (selectedGif.value?.url) {
    URL.revokeObjectURL(selectedGif.value.url)
  }
  if (generatedGif.value) {
    URL.revokeObjectURL(generatedGif.value)
  }

  selectedGif.value = null
  frames.value = []
  generatedGif.value = ''
  processingProgress.value = 0
}

function updateFrameDelay(index: number, event: Event) {
  const target = event.target as HTMLInputElement
  const delay = parseInt(target.value)
  if (!isNaN(delay) && delay >= 20) {
    frames.value[index].delay = delay
  }
}

// Frame ordering functions
function moveFrameUp() {
  if (frames.value.length <= 1) return

  const first = frames.value[0]
  frames.value.shift()
  frames.value.push(first)
}

function moveFrameDown() {
  if (frames.value.length <= 1) return

  const last = frames.value.pop()
  if (last) {
    frames.value.unshift(last)
  }
}

function reverseFrames() {
  if (frames.value.length <= 1) return

  frames.value.reverse()
}

function shuffleFrames() {
  if (frames.value.length <= 1) return

  // Fisher-Yates shuffle algorithm
  for (let i = frames.value.length - 1; i > 0; i--) {
    const j = Math.floor(Math.random() * (i + 1))
    ;[frames.value[i], frames.value[j]] = [frames.value[j], frames.value[i]]
  }
}

// GIF generation
async function generateGif() {
  if (!selectedGif.value || frames.value.length === 0) {
    showErrorToast(t('tools.gifEditor.errors.noFrames'))
    return
  }

  // Additional validation to ensure we have valid frames
  if (!frames.value.some((frame) => frame.dataUrl && frame.delay > 0)) {
    showErrorToast(t('tools.gifEditor.errors.noFrames'))
    return
  }

  isProcessing.value = true
  processingProgress.value = 0

  try {
    await createGifFromFrames()
    success(t('tools.gifEditor.messages.gifGenerated'))
  } catch (err) {
    console.error('Error generating GIF:', err)
    showErrorToast(t('tools.gifEditor.errors.processingFailed') + ': ' + (err as Error).message)
  } finally {
    isProcessing.value = false
  }
}

async function createGifFromFrames() {
  if (!selectedGif.value) return

  // Validate that we have frames to process
  if (frames.value.length === 0) {
    throw new Error('No frames to process. Please try another GIF file.')
  }

  // Use original GIF dimensions
  const gifWidth = selectedGif.value.width
  const gifHeight = selectedGif.value.height

  // Validate dimensions
  if (!gifWidth || !gifHeight || gifWidth <= 0 || gifHeight <= 0) {
    throw new Error('Invalid GIF dimensions. Please try another GIF file.')
  }

  const canvas = document.createElement('canvas')
  const ctx = canvas.getContext('2d', { willReadFrequently: true })

  if (!ctx) {
    throw new Error('Unable to get canvas context. Your browser may not support this feature.')
  }

  // Set canvas dimensions to match original GIF exactly
  canvas.width = gifWidth
  canvas.height = gifHeight

  // Configure GIF quality based on settings
  const qualityMap = {
    high: 1,
    medium: 10,
    low: 20,
  }

  // Create GIF with original dimensions and transparency support
  const gif = new GIF({
    workers: 2,
    quality: qualityMap[gifSettings.quality],
    width: gifWidth,
    height: gifHeight,
    workerScript: '/gif.worker.js',
    transparent: 0x00000000, // Explicitly set transparent color as 0x00000000 (RGBA)
  })

  const totalFrames = frames.value.length
  let processedFrames = 0

  // Process each frame
  for (const frame of frames.value) {
    try {
      // Clear canvas with transparent background
      // ctx.clearRect(0, 0, canvas.width, canvas.height)

      // Draw frame on canvas
      const img = new Image()
      const imageLoaded = new Promise<void>((resolve, reject) => {
        img.onload = () => resolve()
        img.onerror = () => reject(new Error('Failed to load frame image'))
        img.src = frame.dataUrl
      })

      // Wait for image to load
      await imageLoaded

      // Validate that the image has valid dimensions
      if (img.width <= 0 || img.height <= 0) {
        console.warn('Skipping frame with invalid dimensions')
        continue
      }

      // Draw the image on the full canvas
      ctx.drawImage(img, 0, 0)

      // Add frame to GIF with delay in milliseconds
      gif.addFrame(canvas, { copy: true, delay: frame.delay })

      processedFrames++
      processingProgress.value = Math.round((processedFrames / totalFrames) * 100)
    } catch (err) {
      console.error('Error processing frame:', err)
      // Continue with next frame instead of stopping the whole process
    }
  }

  // If no frames were processed, throw an error
  if (processedFrames === 0) {
    throw new Error('No frames could be processed. Please try another GIF file.')
  }

  // Render GIF
  return new Promise<void>((resolve, reject) => {
    gif.on('finished', (blob: Blob) => {
      const url = URL.createObjectURL(blob)
      generatedGif.value = url
      processingProgress.value = 100
      resolve()
    })

    gif.on('abort', () => {
      reject(new Error('GIF generation was aborted'))
    })

    gif.on('error', (error: Error) => {
      reject(new Error('GIF generation error: ' + error.message))
    })

    try {
      gif.render()
    } catch (error) {
      reject(new Error('Failed to start GIF rendering: ' + (error as Error).message))
    }
  })
}

function downloadGif() {
  if (!generatedGif.value) return

  const link = document.createElement('a')
  link.href = generatedGif.value
  link.download = `edited-gif-${Date.now()}.gif`
  document.body.appendChild(link)
  link.click()
  document.body.removeChild(link)
}

function resetTool() {
  clearAll()

  // Reset settings to defaults
  gifSettings.width = 300
  gifSettings.quality = 'medium'
  gifSettings.fps = 10

  // Reset file input
  if (fileInput.value) {
    fileInput.value.value = ''
  }
}
</script>

<style scoped>
/* Custom styles */
img {
  background-color: #1e293b;
}

/* Loading animation */
.animate-spin {
  animation: spin 1s linear infinite;
}

@keyframes spin {
  from {
    transform: rotate(0deg);
  }
  to {
    transform: rotate(360deg);
  }
}
</style>
