// src/pages/tools/image-list-processor/index.tsx
import { Button } from "@/components/ui/button";
import { Label } from "@/components/ui/label";
import { type SiteDefination } from "@/lib/site";
import JSZip from "jszip";
import {
  Copy,
  DownloadCloud,
  Eraser,
  FileText,
  Images,
  Star
} from "lucide-react";
import { useCallback, useState } from "react";

import MonacoEditor from "@/components/MonacoEditor"

interface ImageInfo { url: string; filename: string }

const extractFilename = (url: string): string => {
  try { return new URL(url).pathname.split("/").pop() || url; }
  catch { return url.split("/").pop() || url; }
};

export default function ImageListProcessorPage({ title, description }: SiteDefination) {
  const [input, setInput] = useState("");
  const [images, setImages] = useState<ImageInfo[]>([]);
  const [isDownloading, setIsDownloading] = useState(false);

  const processImages = useCallback((value: string) => {
    setInput(value);
    if (!value.trim()) { setImages([]); return; }
    const lines = value.split("\n").map((l) => l.trim()).filter((l) => l && !l.startsWith("#") && (l.startsWith("http://") || l.startsWith("https://")));
    const unique = lines.filter((url, i, self) => self.indexOf(url) === i);
    setImages(unique.map((url) => ({ url, filename: extractFilename(url) })));
  }, []);

  const handleDownloadAll = async () => {
    if (!images.length) return;
    setIsDownloading(true);
    try {
      const zip = new JSZip();
      await Promise.all(images.map(async (img, i) => {
        try {
          const res = await fetch(img.url);
          if (!res.ok) throw new Error("fetch failed");
          const blob = await res.blob();
          let ext = img.url.split(".").pop()?.split(/[?#]/)[0] || "";
          if (!ext || ext.length > 4) { const ct = res.headers.get("content-type"); ext = ct?.includes("image/") ? ct.split("/")[1] : "png"; }
          const name = img.filename?.split(".")[0] || `image-${i + 1}`;
          zip.file(`${name}.${ext}`, blob);
        } catch { }
      }));
      const blob = await zip.generateAsync({ type: "blob" });
      const url = URL.createObjectURL(blob);
      const a = document.createElement("a"); a.href = url; a.download = `images-${Date.now()}.zip`; a.click();
      URL.revokeObjectURL(url);
    } finally { setIsDownloading(false); }
  };

  const handleExportScript = (format: "bat" | "sh") => {
    const cmds = images.map((img, i) => {
      const fn = img.filename || `image-${i + 1}.png`;
      const dot = fn.lastIndexOf(".");
      const name = dot !== -1 ? `${fn.substring(0, dot)}_${i + 1}${fn.substring(dot)}` : `${fn}_${i + 1}.png`;
      return `curl -L -k -o "${name}" "${img.url}"`;
    });
    const content = format === "bat"
      ? `@echo off\necho Downloading ${images.length} images...\n${cmds.join("\n")}\necho Done!\npause`
      : `#!/bin/bash\necho "Downloading ${images.length} images..."\n${cmds.join("\n")}\necho "Done!"`;
    const blob = new Blob([content], { type: "text/plain" });
    const url = URL.createObjectURL(blob);
    const a = document.createElement("a"); a.href = url; a.download = format === "bat" ? "download_images.bat" : "download_images.sh"; a.click();
    URL.revokeObjectURL(url);
  };

  return (
    <>
      <div>
        <div className="max-w-6xl mx-auto px-4 py-6 space-y-4">
          <div className="flex items-center gap-3">
            <div className="w-10 h-10 rounded-lg bg-primary flex items-center justify-center text-white">
              <Images className="size-5" />
            </div>
            <div>
              <h1 className="text-xl font-bold text-gray-900">{title}</h1>
              <p className="text-sm text-gray-500">{description}</p>
            </div>
          </div>

          <div className="flex flex-col gap-2">
            <div className="flex items-center justify-between h-10">
              <Label className="text-sm font-medium">图片 URL 列表 {images.length > 0 && `(${images.length} 张)`}</Label>
              <div className="flex gap-2">
                <Button variant="outline" size="sm" onClick={() => processImages(Array.from({ length: 8 }, (_, i) => `https://picsum.photos/400/300?random=${i + 1}`).join("\n"))}><Star className="size-3.5" /> 示例</Button>
                <Button variant="outline" size="sm" onClick={() => processImages("")} disabled={!input}><Eraser className="size-3.5" /> 清空</Button>
                {images.length > 0 && <Button variant="outline" size="sm" onClick={() => navigator.clipboard.writeText(images.map((i) => i.url).join("\n"))}><Copy className="size-3.5" /> 复制 URL</Button>}
              </div>
            </div>
            <div className="h-[200px]">
              <MonacoEditor value={input} onChange={processImages} language="plaintext" height="100%" showLineNumbersToggle showWordWrapToggle />
            </div>
            {images.length > 0 && (
              <div className="flex gap-2">
                <Button size="sm" onClick={handleDownloadAll} disabled={isDownloading}><DownloadCloud className="size-3.5" /> {isDownloading ? "下载中..." : "下载全部 ZIP"}</Button>
                <Button variant="outline" size="sm" onClick={() => handleExportScript("bat")}><FileText className="size-3.5" /> Windows 脚本</Button>
                <Button variant="outline" size="sm" onClick={() => handleExportScript("sh")}><FileText className="size-3.5" /> Linux 脚本</Button>
              </div>
            )}
          </div>

          {images.length > 0 && (
            <div className="grid grid-cols-1 sm:grid-cols-2 lg:grid-cols-3 gap-4">
              {images.map((img, i) => (
                <div key={i} className="rounded-lg border border-gray-200 bg-white p-2 hover:border-indigo-300 transition-colors">
                  <div className="rounded overflow-hidden bg-gray-50 flex items-center justify-center mb-2 min-h-32">
                    <img src={img.url} alt="" referrerPolicy="no-referrer" className="max-w-full max-h-48 object-contain" onError={(e) => ((e.target as HTMLImageElement).style.opacity = "0.2")} />
                  </div>
                  <p className="text-xs truncate text-gray-600" title={img.filename}>{img.filename}</p>
                  <p className="text-[10px] truncate text-gray-400" title={img.url}>{img.url}</p>
                </div>
              ))}
            </div>
          )}
        </div>
      </div>
    </>
  );
}

// src/tools/image/ImageListProcessor.vue
<template>
  <div class="min-h-screen bg-gray-50 py-8">
    <div class="max-w-7xl mx-auto px-4 sm:px-6 lg:px-8">
      <!-- Header -->
      <div class="bg-white rounded-lg shadow-md p-6 mb-8">
        <h1 class="text-3xl font-bold text-gray-900 mb-4">
          🖼️ {{ $t('tools.imageListProcessor.title') }}
        </h1>
        <p class="text-gray-600 text-lg">
          {{ $t('tools.imageListProcessor.description') }}
        </p>
      </div>

      <!-- Input Section -->
      <div class="bg-white rounded-lg shadow-md p-6 mb-8">
        <h3 class="text-lg font-semibold text-gray-900 mb-4 border-b border-gray-200 pb-2">
          {{ $t('tools.imageListProcessor.inputTitle') }}
        </h3>
        <p class="text-sm text-gray-600 mb-4">
          {{ $t('tools.imageListProcessor.inputNote') }}
        </p>
        <textarea
          v-model="inputData"
          @input="processImages"
          class="w-full h-64 p-4 border border-gray-300 rounded-lg resize-vertical focus:ring-2 focus:ring-blue-500 focus:border-blue-500 font-mono text-sm"
          :placeholder="$t('tools.imageListProcessor.inputPlaceholder')"
        ></textarea>
      </div>

      <!-- Actions -->
      <div class="bg-white rounded-lg shadow-md p-6 mb-8" v-if="imageList.length > 0">
        <div class="flex flex-wrap items-center gap-4">
          <button
            @click="clearAll"
            class="px-6 py-2 bg-gray-600 text-white rounded-lg hover:bg-gray-700 transition-colors"
          >
            🗑️ {{ $t('common.clear') }}
          </button>
          <button
            @click="copyUrls"
            class="px-6 py-2 bg-blue-600 text-white rounded-lg hover:bg-blue-700 transition-colors"
          >
            📋 {{ $t('common.copy') }} URLs
          </button>
          <div class="text-sm text-gray-600">
            {{ $t('common.total') }}: {{ imageList.length }} {{ $t('common.items') }}
          </div>
        </div>
      </div>

      <!-- Image Gallery -->
      <div class="bg-white rounded-lg shadow-md p-6 mb-8" v-if="imageList.length > 0">
        <h3 class="text-lg font-semibold text-gray-900 mb-6 border-b border-gray-200 pb-2">
          {{ $t('tools.imageListProcessor.imagePreview') }}
        </h3>
        <div class="grid grid-cols-1 sm:grid-cols-2 lg:grid-cols-4 gap-6">
          <div
            v-for="(image, index) in imageList"
            :key="index"
            class="bg-gray-50 rounded-lg overflow-hidden shadow-sm hover:shadow-md transition-shadow"
          >
            <div class="aspect-square relative bg-gray-100">
              <img
                referrerpolicy="no-referrer"
                :src="image.url"
                :alt="image.alt || `Image ${index + 1}`"
                @error="handleImageError"
                @load="handleImageLoad"
                class="w-full h-full object-cover cursor-pointer hover:scale-105 transition-transform duration-200"
                @click="openImageModal(image)"
              />
              <div
                v-if="image.loading"
                class="absolute inset-0 bg-gray-200 animate-pulse flex items-center justify-center"
              >
                <div class="text-gray-500 text-sm">{{ $t('common.loading') }}</div>
              </div>
              <div
                v-if="image.error"
                class="absolute inset-0 bg-red-50 flex items-center justify-center p-4"
              >
                <div class="text-red-500 text-sm text-center">
                  ❌ {{ $t('tools.imageListProcessor.imageError') }}
                </div>
              </div>
            </div>
            <div class="p-3">
              <div class="text-xs text-gray-600 truncate" :title="image.url">
                {{ image.filename || extractFilename(image.url) }}
              </div>
              <div class="text-xs text-gray-400 mt-1 truncate" :title="image.url">
                {{ image.url }}
              </div>
            </div>
          </div>
        </div>
      </div>

      <!-- No Results -->
      <div
        v-if="imageList.length === 0 && inputData.trim()"
        class="bg-yellow-50 border border-yellow-200 rounded-lg p-6 text-center"
      >
        <div class="text-yellow-600 text-lg mb-2">⚠️</div>
        <p class="text-yellow-800">{{ $t('tools.imageListProcessor.noResults') }}</p>
      </div>

      <!-- Empty State -->
      <div
        v-if="!inputData.trim()"
        class="bg-gray-50 border-2 border-dashed border-gray-300 rounded-lg p-12 text-center"
      >
        <div class="text-gray-400 text-6xl mb-4">🖼️</div>
        <h3 class="text-lg font-medium text-gray-900 mb-2">
          {{ $t('tools.imageListProcessor.emptyState.title') }}
        </h3>
        <p class="text-gray-600 mb-4">
          {{ $t('tools.imageListProcessor.emptyState.description') }}
        </p>
        <button
          @click="loadExampleUrls"
          class="px-6 py-2 bg-blue-600 text-white rounded-lg hover:bg-blue-700 transition-colors"
        >
          {{ $t('common.loadExample') }}
        </button>
      </div>

      <!-- Features Section -->
      <div class="grid grid-cols-1 md:grid-cols-3 gap-8 mt-12">
        <div class="bg-white p-6 rounded-lg shadow-md border-l-4 border-blue-500">
          <h3 class="text-lg font-semibold text-gray-900 mb-3">
            🔗 {{ $t('tools.imageListProcessor.features.simple.title') }}
          </h3>
          <p class="text-gray-600 text-sm">
            {{ $t('tools.imageListProcessor.features.simple.description') }}
          </p>
        </div>

        <div class="bg-white p-6 rounded-lg shadow-md border-l-4 border-green-500">
          <h3 class="text-lg font-semibold text-gray-900 mb-3">
            🖼️ {{ $t('tools.imageListProcessor.features.gallery.title') }}
          </h3>
          <p class="text-gray-600 text-sm">
            {{ $t('tools.imageListProcessor.features.gallery.description') }}
          </p>
        </div>

        <div class="bg-white p-6 rounded-lg shadow-md border-l-4 border-purple-500">
          <h3 class="text-lg font-semibold text-gray-900 mb-3">
            ⚡ {{ $t('tools.imageListProcessor.features.fast.title') }}
          </h3>
          <p class="text-gray-600 text-sm">
            {{ $t('tools.imageListProcessor.features.fast.description') }}
          </p>
        </div>
      </div>
    </div>
  </div>

  <!-- Image Modal -->
  <div
    v-if="selectedImage"
    class="fixed inset-0 bg-black bg-opacity-75 flex items-center justify-center z-50 p-4"
    @click="closeImageModal"
  >
    <div class="max-w-4xl max-h-full relative">
      <button
        @click="closeImageModal"
        class="absolute -top-10 right-0 text-white hover:text-gray-300 text-2xl"
      >
        ✕
      </button>
      <img
        :src="selectedImage.url"
        :alt="selectedImage.alt || 'Selected image'"
        class="max-w-full max-h-full object-contain"
        @click.stop
      />
      <div class="absolute bottom-0 left-0 right-0 bg-black bg-opacity-75 text-white p-4">
        <div class="text-sm truncate">{{ selectedImage.url }}</div>
      </div>
    </div>
  </div>
</template>

<script setup lang="ts">
import { ref, reactive } from 'vue'
import { useI18n } from 'vue-i18n'
import { useToast } from '@/composables/useToast'

interface ImageInfo {
  url: string
  alt?: string
  filename?: string
  loading?: boolean
  error?: boolean
}

const { t } = useI18n()
const { copySuccess, copyError } = useToast()

const inputData = ref('')
const imageList = ref<ImageInfo[]>([])
const selectedImage = ref<ImageInfo | null>(null)

// Process input data to extract image URLs
function processImages() {
  if (!inputData.value.trim()) {
    imageList.value = []
    return
  }

  const lines = inputData.value
    .split('\n')
    .map((line) => line.trim())
    .filter((line) => line && !line.startsWith('#')) // Filter out empty lines and comments

  const images: ImageInfo[] = []

  for (const line of lines) {
    if (isValidImageUrl(line)) {
      images.push({
        url: line,
        filename: extractFilename(line),
        loading: true,
        error: false,
      })
    }
  }

  // Remove duplicates based on URL
  const uniqueImages = images.filter(
    (image, index, self) => index === self.findIndex((t) => t.url === image.url),
  )

  imageList.value = uniqueImages
}

// Validate if URL is likely an image
function isValidImageUrl(url: string): boolean {
  if (!url) return false

  // Remove whitespace
  url = url.trim()
  if (!url) return false

  // Check if it starts with http/https
  if (!url.startsWith('http://') && !url.startsWith('https://')) {
    return false
  }

  return true
}

function extractFilename(url: string): string {
  try {
    const pathname = new URL(url).pathname
    return pathname.split('/').pop() || ''
  } catch {
    return url.split('/').pop() || url
  }
}

function handleImageError(event: Event) {
  const img = event.target as HTMLImageElement
  const url = img.src
  const imageIndex = imageList.value.findIndex((image) => image.url === url)
  if (imageIndex !== -1) {
    imageList.value[imageIndex].error = true
    imageList.value[imageIndex].loading = false
  }
}

function handleImageLoad(event: Event) {
  const img = event.target as HTMLImageElement
  const url = img.src
  const imageIndex = imageList.value.findIndex((image) => image.url === url)
  if (imageIndex !== -1) {
    imageList.value[imageIndex].loading = false
    imageList.value[imageIndex].error = false
  }
}

function openImageModal(image: ImageInfo) {
  selectedImage.value = image
}

function closeImageModal() {
  selectedImage.value = null
}

// Action functions
function clearAll() {
  inputData.value = ''
  imageList.value = []
}

function copyUrls() {
  if (imageList.value.length === 0) return

  const urls = imageList.value.map((image) => image.url).join('\n')
  navigator.clipboard
    .writeText(urls)
    .then(() => {
      copySuccess()
    })
    .catch(() => {
      copyError()
    })
}

function loadExampleUrls() {
  inputData.value = `https://picsum.photos/400/300?random=1
https://picsum.photos/400/300?random=2
https://picsum.photos/400/300?random=3
https://picsum.photos/400/300?random=4
https://picsum.photos/400/300?random=5
https://picsum.photos/400/300?random=6
https://picsum.photos/400/300?random=7
https://picsum.photos/400/300?random=8`
  processImages()
}
</script>
