// src/pages/tools/Json/JsonExtractor.tsx
import { useState, useEffect, useMemo } from "react";
import { FormattedMessage, useIntl } from "react-intl";
import { JSONPath } from "jsonpath-plus";
import {
  CheckOutlined,
  CopyOutlined,
  DownloadOutlined,
  ExclamationCircleOutlined,
  StarOutlined,
  FileTextOutlined,
  FilterOutlined,
  KeyOutlined,
  AppstoreOutlined,
} from "@ant-design/icons";
import {
  Button,
  Card,
  Tabs,
  Input,
  Switch,
  Tag,
  Select,
  Divider,
  Typography,
  Checkbox,
  Space,
} from "antd";

import { useCopy } from "@/hooks/useCopy";

const { TextArea } = Input;
const { Text } = Typography;

type Mode = "path" | "field" | "keys";
type OutputFormat = "array" | "list";

const JsonExtractor = () => {
  const intl = useIntl();
  const copy = useCopy();

  const [mode, setMode] = useState<Mode>("path");
  const [inputJson, setInputJson] = useState("");
  const [parsedJson, setParsedJson] = useState<any>(null);
  const [isValidJson, setIsValidJson] = useState(false);
  const [jsonError, setJsonError] = useState("");

  const [jsonPath, setJsonPath] = useState("$");

  const [availableFields, setAvailableFields] = useState<string[]>([]);
  const [selectedFields, setSelectedFields] = useState<string[]>([]);
  const [preserveStructure, setPreserveStructure] = useState(true);
  const [removeEmpty, setRemoveEmpty] = useState(false);

  const [keysMode, setKeysMode] = useState<"keys" | "values">("keys");
  const [includeNested, setIncludeNested] = useState(true);
  const [sortResults, setSortResults] = useState(true);
  const [outputFormat, setOutputFormat] = useState<OutputFormat>("array");

  const [extractedData, setExtractedData] = useState<any>(null);
  const [extractionError, setExtractionError] = useState("");

  const quickPaths = [
    { label: "$", desc: "Root" },
    { label: "$.*", desc: "All Props" },
    { label: "$[0]", desc: "First" },
    { label: "$[*]", desc: "All Items" },
    { label: "$[-1]", desc: "Last" },
    { label: "$..id", desc: "Recursive" },
  ];

  useEffect(() => {
    setJsonError("");
    setIsValidJson(false);
    setParsedJson(null);
    if (!inputJson.trim()) return;
    try {
      const parsed = JSON.parse(inputJson);
      setParsedJson(parsed);
      setIsValidJson(true);
      analyzeFields(parsed);
    } catch (err: any) {
      setJsonError(err.message);
    }
  }, [inputJson]);

  useEffect(() => {
    if (!isValidJson || !parsedJson) return;
    setExtractionError("");
    try {
      if (mode === "path" && jsonPath.trim()) {
        const results = JSONPath({ path: jsonPath, json: parsedJson, wrap: false });
        setExtractedData(results);
      } else if (mode === "field" && selectedFields.length > 0) {
        extractFields();
      } else if (mode === "keys") {
        extractKeysValues();
      }
    } catch (err: any) {
      setExtractionError(err.message);
      setExtractedData(null);
    }
  }, [mode, jsonPath, selectedFields, preserveStructure, removeEmpty, keysMode, includeNested, sortResults, outputFormat, parsedJson, isValidJson]);

  const analyzeFields = (data: any) => {
    const fields = new Set<string>();
    const traverse = (obj: any, prefix = "") => {
      if (Array.isArray(obj)) {
        obj.forEach(item => {
          if (typeof item === "object" && item !== null) traverse(item, prefix);
        });
      } else if (obj !== null && typeof obj === "object") {
        Object.keys(obj).forEach(key => {
          const fullKey = prefix ? `${prefix}.${key}` : key;
          fields.add(fullKey);
          if (typeof obj[key] === "object" && obj[key] !== null) traverse(obj[key], fullKey);
        });
      }
    };
    traverse(data);
    setAvailableFields(Array.from(fields).sort());
  };

  const extractFields = () => {
    if (!parsedJson) return;
    const dataArray = Array.isArray(parsedJson) ? parsedJson : [parsedJson];
    const result = dataArray.map((item: any) => {
      const extracted: any = {};
      selectedFields.forEach(field => {
        const getNestedValue = (obj: any, keys: string[]): any => {
          if (keys.length === 0) return obj;
          const [head, ...rest] = keys;
          if (obj === null || obj === undefined) return undefined;
          if (Array.isArray(obj)) {
            const results = obj.map(el => getNestedValue(el, keys)).filter(v => v !== undefined);
            return results.length > 0 ? results : undefined;
          }
          return getNestedValue(obj[head], rest);
        };
        const value = getNestedValue(item, field.split("."));
        if (removeEmpty && (value === null || value === undefined || value === "")) return;
        if (preserveStructure) {
          const keys = field.split(".");
          let current = extracted;
          for (let i = 0; i < keys.length - 1; i++) {
            current[keys[i]] = current[keys[i]] || {};
            current = current[keys[i]];
          }
          current[keys[keys.length - 1]] = value;
        } else {
          extracted[field] = value;
        }
      });
      return extracted;
    });
    setExtractedData(Array.isArray(parsedJson) ? result : result[0]);
  };

  const extractKeysValues = () => {
    if (!parsedJson) return;
    if (keysMode === "keys") {
      const keys = new Set<string>();
      const traverse = (obj: any, path = "") => {
        if (Array.isArray(obj)) {
          obj.forEach(item => {
            if (typeof item === "object" && item !== null) traverse(item, path);
          });
        } else if (obj !== null && typeof obj === "object") {
          Object.keys(obj).forEach(key => {
            const fullPath = includeNested && path ? `${path}.${key}` : key;
            keys.add(fullPath);
            if (typeof obj[key] === "object" && obj[key] !== null) traverse(obj[key], fullPath);
          });
        }
      };
      traverse(parsedJson);
      let keysArray = Array.from(keys);
      if (sortResults) keysArray.sort();
      setExtractedData(outputFormat === "list" ? keysArray.join("\n") : keysArray);
    } else {
      const values: any[] = [];
      const traverse = (obj: any) => {
        if (Array.isArray(obj)) {
          obj.forEach(item => {
            if (typeof item === "object" && item !== null) traverse(item);
            else values.push(item);
          });
        } else if (obj !== null && typeof obj === "object") {
          Object.values(obj).forEach(value => {
            if (typeof value === "object" && value !== null) traverse(value);
            else values.push(value);
          });
        }
      };
      traverse(parsedJson);
      const uniqueValues = Array.from(new Set(values));
      if (sortResults) uniqueValues.sort();
      setExtractedData(outputFormat === "list" ? uniqueValues.join("\n") : uniqueValues);
    }
  };

  const formattedOutput = useMemo(() => {
    if (extractedData === null || extractedData === undefined) return "";
    if (typeof extractedData === "string") return extractedData;
    try {
      return JSON.stringify(extractedData, null, 2);
    } catch {
      return String(extractedData);
    }
  }, [extractedData]);

  const loadExample = () => {
    const example = [
      { id: 1, name: "John Doe", email: "john@example.com", address: { city: "New York", country: "USA" } },
      { id: 2, name: "Jane Smith", email: "jane@example.com", address: { city: "London", country: "UK" } },
      { id: 3, name: "Bob Johnson", email: "bob@example.com", address: { city: "Tokyo", country: "Japan" } },
    ];
    setInputJson(JSON.stringify(example, null, 2));
    setJsonPath("$[*].name");
  };

  const handleDownload = () => {
    if (!formattedOutput) return;
    const blob = new Blob([formattedOutput], { type: "application/json" });
    const url = URL.createObjectURL(blob);
    const link = document.createElement("a");
    link.href = url;
    link.download = `extracted_${mode}_${Date.now()}.json`;
    link.click();
    URL.revokeObjectURL(url);
  };

  const tabItems = [
    {
      key: "path",
      label: <span className="flex items-center gap-1.5"><AppstoreOutlined />Path</span>,
      children: (
        <div className="space-y-4">
          <div className="space-y-2">
            <label className="text-sm font-medium">JSONPath Expression</label>
            <Input
              value={jsonPath}
              onChange={(e) => setJsonPath(e.target.value)}
              placeholder="$.store.book[*].author"
              className="font-mono"
            />
          </div>
          <div className="space-y-2">
            <label className="text-xs text-gray-400">Quick Paths</label>
            <div className="flex flex-wrap gap-2">
              {quickPaths.map((qp) => (
                <Button key={qp.label} size="small" onClick={() => setJsonPath(qp.label)} className="font-mono text-xs">
                  {qp.label}<span className="ml-1.5 text-gray-400">· {qp.desc}</span>
                </Button>
              ))}
            </div>
          </div>
        </div>
      ),
    },
    {
      key: "field",
      label: <span className="flex items-center gap-1.5"><FilterOutlined />Fields</span>,
      children: (
        <div className="space-y-4">
          <div className="space-y-2">
            <div className="flex items-center justify-between">
              <label className="text-sm font-medium">Available Fields ({availableFields.length})</label>
              <Space size="small">
                <Button size="small" type="link" onClick={() => setSelectedFields([...availableFields])}>All</Button>
                <Button size="small" type="link" onClick={() => setSelectedFields([])}>None</Button>
              </Space>
            </div>
            <div className="h-48 overflow-y-auto rounded-lg border border-gray-200 dark:border-gray-700 p-3">
              {availableFields.length > 0 ? (
                <div className="space-y-2">
                  {availableFields.map((field) => (
                    <div key={field} className="flex items-center gap-2">
                      <Checkbox
                        checked={selectedFields.includes(field)}
                        onChange={(e) => {
                          if (e.target.checked) {
                            setSelectedFields([...selectedFields, field]);
                          } else {
                            setSelectedFields(selectedFields.filter(f => f !== field));
                          }
                        }}
                      />
                      <span className="text-sm font-mono cursor-pointer flex-1">{field}</span>
                    </div>
                  ))}
                </div>
              ) : (
                <div className="flex h-full items-center justify-center text-sm text-gray-400">
                  No fields detected
                </div>
              )}
            </div>
          </div>
          <div className="space-y-3">
            <div className="flex items-center justify-between">
              <Text className="text-sm">Preserve Structure</Text>
              <Switch checked={preserveStructure} onChange={setPreserveStructure} size="small" />
            </div>
            <div className="flex items-center justify-between">
              <Text className="text-sm">Remove Empty Values</Text>
              <Switch checked={removeEmpty} onChange={setRemoveEmpty} size="small" />
            </div>
          </div>
        </div>
      ),
    },
    {
      key: "keys",
      label: <span className="flex items-center gap-1.5"><KeyOutlined />Keys</span>,
      children: (
        <div className="space-y-4">
          <div className="space-y-2">
            <label className="text-sm font-medium">Extract</label>
            <div className="grid grid-cols-2 gap-2">
              <Button type={keysMode === "keys" ? "primary" : "default"} onClick={() => setKeysMode("keys")} block>Keys</Button>
              <Button type={keysMode === "values" ? "primary" : "default"} onClick={() => setKeysMode("values")} block>Values</Button>
            </div>
          </div>
          <div className="space-y-3">
            {keysMode === "keys" && (
              <div className="flex items-center justify-between">
                <Text className="text-sm">Include Nested Paths</Text>
                <Switch checked={includeNested} onChange={setIncludeNested} size="small" />
              </div>
            )}
            <div className="flex items-center justify-between">
              <Text className="text-sm">Sort Results</Text>
              <Switch checked={sortResults} onChange={setSortResults} size="small" />
            </div>
            <div className="space-y-2">
              <label className="text-sm font-medium">Output Format</label>
              <Select
                value={outputFormat}
                onChange={(v) => setOutputFormat(v as OutputFormat)}
                className="w-full"
                options={[
                  { value: "array", label: "Array" },
                  { value: "list", label: "List (Line-separated)" },
                ]}
              />
            </div>
          </div>
        </div>
      ),
    },
  ];

  return (
    <div className="mx-auto max-w-7xl space-y-6">
      <div className="grid gap-6 lg:grid-cols-2 h-[calc(100vh-10rem)]">
        {/* Left: Input */}
        <Card
          className="rounded-2xl flex flex-col"
          styles={{ body: { display: "flex", flexDirection: "column", flex: 1, overflow: "hidden", padding: "16px 24px 24px" } }}
        >
          <div className="flex items-center justify-between mb-4 shrink-0">
            <div className="flex items-center gap-2">
              <FileTextOutlined className="text-primary text-lg" />
              <span className="text-lg font-semibold">
                <FormattedMessage id="tools.jsonExtractor.inputSection.title" />
              </span>
            </div>
            <Space>
              <Button size="small" icon={<StarOutlined />} onClick={loadExample}>Example</Button>
              <Button size="small" onClick={() => { setInputJson(""); setExtractedData(null); }}>Clear</Button>
            </Space>
          </div>

          <div className="flex-1 flex flex-col min-h-0 space-y-2">
            <label className="text-sm font-medium">JSON Data</label>
            <TextArea
              value={inputJson}
              onChange={(e) => setInputJson(e.target.value)}
              placeholder='{"name": "John", "age": 30}'
              className="font-mono text-sm resize-none"
              spellCheck={false}
              style={{ flex: 1, minHeight: 0 }}
            />
            {inputJson.trim() && (
              <div className="flex items-center gap-2">
                {isValidJson ? (
                  <Tag color="success" icon={<CheckOutlined />}>Valid JSON</Tag>
                ) : (
                  <div className="flex items-start gap-2 rounded-lg bg-red-50 dark:bg-red-900/20 p-3 text-sm text-red-600 dark:text-red-400">
                    <ExclamationCircleOutlined className="mt-0.5 shrink-0" />
                    <div>
                      <p className="font-medium">Invalid JSON</p>
                      <p className="text-xs mt-1 opacity-90">{jsonError}</p>
                    </div>
                  </div>
                )}
              </div>
            )}
          </div>

          <Divider className="my-3" />

          <div className="shrink-0">
            <Tabs activeKey={mode} onChange={(v) => setMode(v as Mode)} items={tabItems} size="small" />
          </div>
        </Card>

        {/* Right: Output */}
        <Card
          className="rounded-2xl flex flex-col"
          styles={{ body: { display: "flex", flexDirection: "column", flex: 1, overflow: "hidden", padding: "16px 24px 24px" } }}
        >
          <div className="flex items-center justify-between mb-2 shrink-0">
            <span className="text-lg font-semibold">
              <FormattedMessage id="tools.jsonExtractor.outputSection.title" />
            </span>
            {extractedData && (
              <Space>
                <Button size="small" icon={<CopyOutlined />} onClick={() => copy(formattedOutput)}>Copy</Button>
                <Button size="small" icon={<DownloadOutlined />} onClick={handleDownload}>Download</Button>
              </Space>
            )}
          </div>
          {extractedData && (
            <div className="mb-3 shrink-0">
              <Text type="secondary" className="text-sm">
                {Array.isArray(extractedData) ? `${extractedData.length} items extracted` : "Object extracted"}
              </Text>
            </div>
          )}

          <div className="flex-1 min-h-0">
            {!isValidJson ? (
              <div className="flex flex-1 h-full flex-col items-center justify-center rounded-lg border-2 border-dashed text-gray-400">
                <FileTextOutlined style={{ fontSize: 48 }} className="mb-4 opacity-50" />
                <p className="text-sm">Waiting for valid JSON...</p>
              </div>
            ) : extractionError ? (
              <div className="flex items-start gap-3 rounded-lg bg-red-50 dark:bg-red-900/20 p-4 text-red-600 dark:text-red-400">
                <ExclamationCircleOutlined className="mt-0.5 shrink-0" />
                <div>
                  <p className="font-medium">Extraction Error</p>
                  <p className="text-sm mt-1 opacity-90">{extractionError}</p>
                </div>
              </div>
            ) : !extractedData ? (
              <div className="flex flex-1 h-full flex-col items-center justify-center rounded-lg border-2 border-dashed text-gray-400">
                <FilterOutlined style={{ fontSize: 48 }} className="mb-4 opacity-50" />
                <p className="text-sm">Configure extraction settings</p>
              </div>
            ) : (
              <TextArea
                value={formattedOutput}
                readOnly
                className="font-mono text-sm resize-none h-full"
                style={{ flex: 1, minHeight: 0, height: "100%", backgroundColor: "var(--color-muted)" }}
              />
            )}
          </div>
        </Card>
      </div>
    </div>
  );
};

export default JsonExtractor;

// src/tools/JsonExtractor.vue
<template>
  <div class="min-h-screen bg-gray-50">
    <div class="max-w-7xl mx-auto px-4 sm:px-6 lg:px-8 py-8">
      <!-- Hero Section -->
      <div class="text-center mb-12">
        <h1 class="text-4xl font-bold text-gray-900 mb-4">JSON Field Extractor</h1>
        <p class="text-xl text-gray-600 max-w-3xl mx-auto">
          Extract specific fields from JSON array data with one click
        </p>
      </div>

      <!-- Field Selection -->
      <div v-if="availableFields.length > 0" class="bg-white rounded-lg shadow-md p-6 mb-8">
        <h3 class="text-lg font-semibold text-gray-900 mb-4 border-b border-gray-200 pb-2">
          Available Fields
        </h3>
        <div class="grid grid-cols-2 md:grid-cols-3 lg:grid-cols-4 gap-4 mb-4">
          <label
            v-for="field in availableFields"
            :key="field"
            class="flex items-center space-x-3 p-3 bg-gray-50 rounded-lg hover:bg-gray-100 transition-colors cursor-pointer"
          >
            <input
              type="checkbox"
              :value="field"
              v-model="selectedFields"
              @change="extractFields"
              class="h-4 w-4 text-blue-600 focus:ring-blue-500 border-gray-300 rounded"
            />
            <span class="text-sm font-medium text-gray-700">{{ field }}</span>
          </label>
        </div>
        <div class="flex gap-3">
          <button
            @click="selectAllFields"
            class="px-4 py-2 bg-blue-600 text-white rounded-lg hover:bg-blue-700 transition-colors font-medium"
          >
            Select All
          </button>
          <button
            @click="clearSelection"
            class="px-4 py-2 bg-gray-600 text-white rounded-lg hover:bg-gray-700 transition-colors font-medium"
          >
            Clear Selection
          </button>
        </div>
      </div>

      <!-- Options -->
      <div class="bg-white rounded-lg shadow-md p-6 mb-8">
        <h3 class="text-lg font-semibold text-gray-900 mb-4 border-b border-gray-200 pb-2">
          Options
        </h3>
        <div class="flex flex-wrap items-center gap-6">
          <label class="flex items-center space-x-3">
            <input
              type="checkbox"
              v-model="options.preserveStructure"
              @change="extractFields"
              class="h-4 w-4 text-blue-600 focus:ring-blue-500 border-gray-300 rounded"
            />
            <span class="text-sm font-medium text-gray-700">🏗️ Preserve Object Structure</span>
          </label>
          <label class="flex items-center space-x-3">
            <input
              type="checkbox"
              v-model="options.removeEmpty"
              @change="extractFields"
              class="h-4 w-4 text-blue-600 focus:ring-blue-500 border-gray-300 rounded"
            />
            <span class="text-sm font-medium text-gray-700">🧹 Remove Empty Values</span>
          </label>
          <div class="flex gap-3 ml-auto">
            <button
              @click="copyResults"
              :disabled="extractedData.length === 0"
              class="px-4 py-2 bg-green-600 text-white rounded-lg hover:bg-green-700 transition-colors font-medium disabled:opacity-50 disabled:cursor-not-allowed"
            >
              Copy Results
            </button>
            <button
              @click="downloadResults"
              :disabled="extractedData.length === 0"
              class="px-4 py-2 bg-purple-600 text-white rounded-lg hover:bg-purple-700 transition-colors font-medium disabled:opacity-50 disabled:cursor-not-allowed"
            >
              Download JSON
            </button>
            <button
              @click="loadExample"
              class="px-4 py-2 bg-gray-600 text-white rounded-lg hover:bg-gray-700 transition-colors font-medium"
            >
              Load Example
            </button>
            <button
              @click="clearContent"
              class="px-4 py-2 bg-red-600 text-white rounded-lg hover:bg-red-700 transition-colors font-medium"
            >
              Clear
            </button>
          </div>
        </div>
      </div>

      <!-- Input Section -->
      <div class="bg-white rounded-lg shadow-md p-6 mb-8">
        <h2 class="text-xl font-semibold text-gray-900 mb-4 border-b border-gray-200 pb-2">
          Input JSON Array
        </h2>
        <div class="mb-4">
          <p class="text-sm text-gray-600 mb-2">
            📋 Please paste JSON array data in the format:
            <code class="bg-gray-100 px-1 rounded">[{},{},...]</code>
          </p>
          <p class="text-sm text-gray-500">
            The tool will automatically parse the JSON and list all available fields for selection.
          </p>
        </div>
        <textarea
          v-model="jsonInput"
          @input="parseJson"
          placeholder='Paste your JSON array here, e.g.:\n[\n  {"name": "John", "age": 30, "city": "New York"},\n  {"name": "Jane", "age": 25, "city": "London"}\n]'
          class="w-full h-64 px-3 py-2 border border-gray-300 rounded-lg focus:ring-2 focus:ring-blue-500 focus:border-blue-500 font-mono text-sm resize-none"
        ></textarea>
        <div v-if="parseError" class="mt-2 text-red-600 text-sm">⚠️ {{ parseError }}</div>
      </div>

      <!-- Results Section -->
      <div class="bg-white rounded-lg shadow-md p-6">
        <h2 class="text-xl font-semibold text-gray-900 mb-4 border-b border-gray-200 pb-2">
          Extraction Results
        </h2>
        <div class="mb-3 px-3 py-2 bg-blue-50 rounded-md border-l-4 border-blue-400">
          <span class="text-blue-800 font-medium text-sm">
            {{ extractedData.length }} items extracted with {{ selectedFields.length }} fields
          </span>
        </div>

        <div v-if="extractedData.length === 0" class="text-center py-12">
          <div class="text-gray-400 text-lg mb-2">📊</div>
          <p class="text-gray-500">
            No extraction results yet. Please input JSON array data and select fields to extract.
          </p>
        </div>

        <div v-else class="space-y-4">
          <!-- Results Preview -->
          <div class="border border-gray-200 rounded-lg overflow-hidden">
            <h3 class="bg-gray-800 text-white px-3 py-2 font-medium flex items-center text-sm">
              <span class="mr-2">📊</span>
              EXTRACTED DATA ({{ extractedData.length }} items)
            </h3>
            <div class="p-4">
              <pre
                class="bg-gray-50 p-3 rounded border text-sm overflow-x-auto max-h-96 overflow-y-auto"
                >{{ JSON.stringify(extractedData, null, 2) }}</pre
              >
            </div>
          </div>

          <!-- Field Statistics -->
          <div
            v-if="fieldStats.length > 0"
            class="border border-gray-200 rounded-lg overflow-hidden"
          >
            <h3 class="bg-gray-800 text-white px-3 py-2 font-medium flex items-center text-sm">
              <span class="mr-2">📈</span>
              FIELD STATISTICS
            </h3>
            <div class="divide-y divide-gray-200">
              <div v-for="stat in fieldStats" :key="stat.field" class="px-3 py-2 hover:bg-gray-50">
                <div class="flex justify-between items-center">
                  <span class="font-medium text-sm">{{ stat.field }}</span>
                  <div class="flex gap-4 text-xs text-gray-600">
                    <span>Total: {{ stat.total }}</span>
                    <span>Non-empty: {{ stat.nonEmpty }}</span>
                    <span>Unique: {{ stat.unique }}</span>
                  </div>
                </div>
              </div>
            </div>
          </div>
        </div>
      </div>

      <!-- Feature Descriptions -->
      <div class="grid grid-cols-1 md:grid-cols-3 gap-8 mt-12">
        <div class="bg-white p-6 rounded-lg shadow-md border-l-4 border-blue-500">
          <h3 class="text-lg font-semibold text-gray-900 mb-3">📊 Field Extraction</h3>
          <p class="text-gray-600 text-sm">
            Automatically parse JSON array and extract selected fields. Supports nested objects and
            preserves data types for accurate extraction.
          </p>
        </div>

        <div class="bg-white p-6 rounded-lg shadow-md border-l-4 border-green-500">
          <h3 class="text-lg font-semibold text-gray-900 mb-3">🎯 Smart Filtering</h3>
          <p class="text-gray-600 text-sm">
            Choose specific fields to include in the output. Option to remove empty values and
            preserve original object structure for clean results.
          </p>
        </div>

        <div class="bg-white p-6 rounded-lg shadow-md border-l-4 border-purple-500">
          <h3 class="text-lg font-semibold text-gray-900 mb-3">💾 Export Options</h3>
          <p class="text-gray-600 text-sm">
            Copy extracted data to clipboard or download as JSON file. Includes field statistics and
            data analysis for better understanding of your dataset.
          </p>
        </div>
      </div>
    </div>
  </div>
</template>

<script setup lang="ts">
import { ref, computed } from 'vue'

interface ExtractionOptions {
  preserveStructure: boolean
  removeEmpty: boolean
}

interface FieldStat {
  field: string
  total: number
  nonEmpty: number
  unique: number
}

const jsonInput = ref('')
const parseError = ref('')
const originalData = ref<any[]>([])
const availableFields = ref<string[]>([])
const selectedFields = ref<string[]>([])
const extractedData = ref<any[]>([])
const options = ref<ExtractionOptions>({
  preserveStructure: true,
  removeEmpty: false,
})

// Parse JSON input and extract available fields
function parseJson() {
  parseError.value = ''
  availableFields.value = []
  selectedFields.value = []
  originalData.value = []
  extractedData.value = []

  if (!jsonInput.value.trim()) {
    return
  }

  try {
    const parsed = JSON.parse(jsonInput.value)

    if (!Array.isArray(parsed)) {
      parseError.value = 'Input must be a JSON array in format: [{},{},...]'
      return
    }

    if (parsed.length === 0) {
      parseError.value = 'JSON array cannot be empty'
      return
    }

    originalData.value = parsed

    // Extract all available fields from all objects
    const fieldSet = new Set<string>()

    function extractFieldsFromObject(obj: any, prefix = '') {
      if (typeof obj === 'object' && obj !== null && !Array.isArray(obj)) {
        Object.keys(obj).forEach((key) => {
          const fieldName = prefix ? `${prefix}.${key}` : key
          fieldSet.add(fieldName)

          // Recursively extract nested fields (limit depth to avoid infinite recursion)
          if (prefix.split('.').length < 3) {
            extractFieldsFromObject(obj[key], fieldName)
          }
        })
      }
    }

    parsed.forEach((item) => {
      extractFieldsFromObject(item)
    })

    availableFields.value = Array.from(fieldSet).sort()

    if (availableFields.value.length === 0) {
      parseError.value = 'No fields found in the JSON objects'
    }
  } catch (error) {
    parseError.value = `Invalid JSON format: ${(error as Error).message}`
  }
}

// Extract selected fields from the data
function extractFields() {
  if (originalData.value.length === 0 || selectedFields.value.length === 0) {
    extractedData.value = []
    return
  }

  extractedData.value = originalData.value
    .map((item) => {
      const extracted: any = {}

      selectedFields.value.forEach((field) => {
        const value = getNestedValue(item, field)

        if (!options.value.removeEmpty || (value !== null && value !== undefined && value !== '')) {
          if (options.value.preserveStructure) {
            setNestedValue(extracted, field, value)
          } else {
            extracted[field] = value
          }
        }
      })

      return extracted
    })
    .filter((item) => Object.keys(item).length > 0) // Remove completely empty objects
}

// Helper function to get nested value from object
function getNestedValue(obj: any, path: string): any {
  return path.split('.').reduce((current, key) => {
    return current && typeof current === 'object' ? current[key] : undefined
  }, obj)
}

// Helper function to set nested value in object
function setNestedValue(obj: any, path: string, value: any): void {
  const keys = path.split('.')
  const lastKey = keys.pop()!

  const target = keys.reduce((current, key) => {
    if (!current[key] || typeof current[key] !== 'object') {
      current[key] = {}
    }
    return current[key]
  }, obj)

  target[lastKey] = value
}

// Select all available fields
function selectAllFields() {
  selectedFields.value = [...availableFields.value]
  extractFields()
}

// Clear field selection
function clearSelection() {
  selectedFields.value = []
  extractFields()
}

// Computed field statistics
const fieldStats = computed((): FieldStat[] => {
  if (originalData.value.length === 0 || selectedFields.value.length === 0) {
    return []
  }

  return selectedFields.value.map((field) => {
    const values = originalData.value.map((item) => getNestedValue(item, field))
    const nonEmptyValues = values.filter((v) => v !== null && v !== undefined && v !== '')
    const uniqueValues = new Set(nonEmptyValues)

    return {
      field,
      total: originalData.value.length,
      nonEmpty: nonEmptyValues.length,
      unique: uniqueValues.size,
    }
  })
})

// Load example data
function loadExample() {
  jsonInput.value = `[
  {
    "id": 1,
    "name": "John Doe",
    "email": "john.doe@example.com",
    "age": 30,
    "department": "Engineering",
    "salary": 75000,
    "address": {
      "city": "New York",
      "country": "USA"
    },
    "skills": ["JavaScript", "Python", "React"]
  },
  {
    "id": 2,
    "name": "Jane Smith",
    "email": "jane.smith@example.com",
    "age": 28,
    "department": "Marketing",
    "salary": 65000,
    "address": {
      "city": "London",
      "country": "UK"
    },
    "skills": ["SEO", "Content Marketing", "Analytics"]
  },
  {
    "id": 3,
    "name": "Bob Johnson",
    "email": "bob.johnson@example.com",
    "age": 35,
    "department": "Engineering",
    "salary": 85000,
    "address": {
      "city": "San Francisco",
      "country": "USA"
    },
    "skills": ["Java", "Spring", "Microservices"]
  }
]`
  parseJson()
}

// Clear all content
function clearContent() {
  jsonInput.value = ''
  parseError.value = ''
  originalData.value = []
  availableFields.value = []
  selectedFields.value = []
  extractedData.value = []
}

// Copy results to clipboard
function copyResults() {
  if (extractedData.value.length === 0) return

  const text = JSON.stringify(extractedData.value, null, 2)
  navigator.clipboard
    .writeText(text)
    .then(() => {
      alert('Results copied to clipboard!')
    })
    .catch(() => {
      alert('Failed to copy to clipboard')
    })
}

// Download results as JSON file
function downloadResults() {
  if (extractedData.value.length === 0) return

  const data = JSON.stringify(extractedData.value, null, 2)
  const blob = new Blob([data], { type: 'application/json' })
  const url = URL.createObjectURL(blob)

  const link = document.createElement('a')
  link.href = url
  link.download = `extracted-fields-${new Date().toISOString().split('T')[0]}.json`
  document.body.appendChild(link)
  link.click()
  document.body.removeChild(link)

  URL.revokeObjectURL(url)
}
</script>
